export const pagesRoutes = [
  ["v-01560935","/timeline/",{"title":""},["/timeline/index.html"]],
  ["v-695ed729","/categories/coding/1/",{"title":""},["/categories/coding/1/index.html"]],
  ["v-104518d0","/tags/git/1/",{"title":""},["/tags/git/1/index.html"]],
  ["v-03d52fd3","/posts/1/",{"title":""},["/posts/1/index.html"]],
  ["v-13fe50c9","/README.en.html",{"title":"Hblog"},["/README.en","/README.en.md"]],
  ["v-8daa1a0e","/",{"title":""},["/index.html","/README.md"]],
  ["v-5f35402f","/docs/Basics/WebBasics.html",{"title":""},["/docs/Basics/WebBasics","/docs/Basics/WebBasics.md"]],
  ["v-380c62c8","/docs/Compontents/BlogHome.html",{"title":""},["/docs/Compontents/BlogHome","/docs/Compontents/BlogHome.md"]],
  ["v-77df0062","/docs/Compontents/ChargingAnimation.html",{"title":""},["/docs/Compontents/ChargingAnimation","/docs/Compontents/ChargingAnimation.md"]],
  ["v-f0c47d04","/docs/Compontents/ChargingAnimation2.html",{"title":""},["/docs/Compontents/ChargingAnimation2","/docs/Compontents/ChargingAnimation2.md"]],
  ["v-683004ef","/docs/Compontents/Check-Box.html",{"title":""},["/docs/Compontents/Check-Box","/docs/Compontents/Check-Box.md"]],
  ["v-30911082","/docs/Compontents/CodeBackground.html",{"title":""},["/docs/Compontents/CodeBackground","/docs/Compontents/CodeBackground.md"]],
  ["v-8a99b23e","/docs/Compontents/Evaluation.html",{"title":""},["/docs/Compontents/Evaluation","/docs/Compontents/Evaluation.md"]],
  ["v-8d413d4a","/docs/Compontents/GradientButton.html",{"title":""},["/docs/Compontents/GradientButton","/docs/Compontents/GradientButton.md"]],
  ["v-31abb803","/docs/Compontents/InputAnimation.html",{"title":""},["/docs/Compontents/InputAnimation","/docs/Compontents/InputAnimation.md"]],
  ["v-7472ddf0","/docs/Compontents/LikeAnimation.html",{"title":""},["/docs/Compontents/LikeAnimation","/docs/Compontents/LikeAnimation.md"]],
  ["v-39d2fc22","/docs/Compontents/Loading-CodeStyle.html",{"title":""},["/docs/Compontents/Loading-CodeStyle","/docs/Compontents/Loading-CodeStyle.md"]],
  ["v-39ee1d1e","/docs/Compontents/Loading-LiquidStyle.html",{"title":""},["/docs/Compontents/Loading-LiquidStyle","/docs/Compontents/Loading-LiquidStyle.md"]],
  ["v-95c69932","/docs/Compontents/Loading-LoveStyle.html",{"title":""},["/docs/Compontents/Loading-LoveStyle","/docs/Compontents/Loading-LoveStyle.md"]],
  ["v-ebc58e60","/docs/Compontents/MenuAnimation.html",{"title":""},["/docs/Compontents/MenuAnimation","/docs/Compontents/MenuAnimation.md"]],
  ["v-0cab1a30","/docs/Compontents/MergeText.html",{"title":""},["/docs/Compontents/MergeText","/docs/Compontents/MergeText.md"]],
  ["v-46eec34e","/docs/Compontents/RingMenu.html",{"title":""},["/docs/Compontents/RingMenu","/docs/Compontents/RingMenu.md"]],
  ["v-32a6e07a","/docs/Compontents/RingTrack.html",{"title":""},["/docs/Compontents/RingTrack","/docs/Compontents/RingTrack.md"]],
  ["v-3aa39a76","/docs/Compontents/Round3D.html",{"title":""},["/docs/Compontents/Round3D","/docs/Compontents/Round3D.md"]],
  ["v-db305b2a","/docs/Compontents/test.html",{"title":""},["/docs/Compontents/test","/docs/Compontents/test.md"]],
  ["v-38739e92","/docs/Compontents/Title-effect.html",{"title":""},["/docs/Compontents/Title-effect","/docs/Compontents/Title-effect.md"]],
  ["v-41cff211","/docs/Compontents/TitleAnimation.html",{"title":""},["/docs/Compontents/TitleAnimation","/docs/Compontents/TitleAnimation.md"]],
  ["v-cf7e8f2a","/docs/Guide/guide.html",{"title":"VuePress-guide"},["/docs/Guide/guide","/docs/Guide/guide.md"]],
  ["v-6ec390a4","/docs/JavaScript/v-for.html",{"title":""},["/docs/JavaScript/v-for","/docs/JavaScript/v-for.md"]],
  ["v-01f485e2","/docs/JAVAStudyNote/1.Javagaishu.html",{"title":"01 JAVA概述"},["/docs/JAVAStudyNote/1.Javagaishu","/docs/JAVAStudyNote/1.Java概述.html","/docs/JAVAStudyNote/1.Java%E6%A6%82%E8%BF%B0.html","/docs/JAVAStudyNote/1.Java概述.md","/docs/JAVAStudyNote/1.Java%E6%A6%82%E8%BF%B0.md"]],
  ["v-6d91a85e","/docs/JAVAStudyNote/2.bianliangyuyunsuanfu.html",{"title":"02 变量与运算符"},["/docs/JAVAStudyNote/2.bianliangyuyunsuanfu","/docs/JAVAStudyNote/2.变量与运算符.html","/docs/JAVAStudyNote/2.%E5%8F%98%E9%87%8F%E4%B8%8E%E8%BF%90%E7%AE%97%E7%AC%A6.html","/docs/JAVAStudyNote/2.变量与运算符.md","/docs/JAVAStudyNote/2.%E5%8F%98%E9%87%8F%E4%B8%8E%E8%BF%90%E7%AE%97%E7%AC%A6.md"]],
  ["v-3a71eae2","/docs/Python/1、bianliang_nazhihanshu.html",{"title":"01 变量和内置函数"},["/docs/Python/1、bianliang_nazhihanshu","/docs/Python/1、变量,内置函数.html","/docs/Python/1%E3%80%81%E5%8F%98%E9%87%8F,%E5%86%85%E7%BD%AE%E5%87%BD%E6%95%B0.html","/docs/Python/1、变量,内置函数.md","/docs/Python/1%E3%80%81%E5%8F%98%E9%87%8F,%E5%86%85%E7%BD%AE%E5%87%BD%E6%95%B0.md"]],
  ["v-c02ec0e2","/docs/Python/2、yunsuanfu.html",{"title":"02 运算符"},["/docs/Python/2、yunsuanfu","/docs/Python/2、运算符.html","/docs/Python/2%E3%80%81%E8%BF%90%E7%AE%97%E7%AC%A6.html","/docs/Python/2、运算符.md","/docs/Python/2%E3%80%81%E8%BF%90%E7%AE%97%E7%AC%A6.md"]],
  ["v-08743384","/docs/Python/3、zifuchuan.html",{"title":"03 字符串"},["/docs/Python/3、zifuchuan","/docs/Python/3、字符串.html","/docs/Python/3%E3%80%81%E5%AD%97%E7%AC%A6%E4%B8%B2.html","/docs/Python/3、字符串.md","/docs/Python/3%E3%80%81%E5%AD%97%E7%AC%A6%E4%B8%B2.md"]],
  ["v-51b390d6","/docs/Python/4%E3%80%81%E5%88%97%E8%A1%A8.html",{"title":"04 集合"},["/docs/Python/4、列表.html","/docs/Python/4%E3%80%81%E5%88%97%E8%A1%A8","/docs/Python/4、列表.md","/docs/Python/4%E3%80%81%E5%88%97%E8%A1%A8.md"]],
  ["v-acdd9360","/docs/theme-reco/api.html",{"title":"api"},["/docs/theme-reco/api","/docs/theme-reco/api.md"]],
  ["v-48c1226e","/docs/theme-reco/guide.html",{"title":"vuepress-theme-reco"},["/docs/theme-reco/guide","/docs/theme-reco/guide.md"]],
  ["v-5cd03a29","/docs/theme-reco/home.html",{"title":"theme-reco"},["/docs/theme-reco/home","/docs/theme-reco/home.md"]],
  ["v-456cc6d6","/docs/theme-reco/plugin.html",{"title":"plugin"},["/docs/theme-reco/plugin","/docs/theme-reco/plugin.md"]],
  ["v-65959fc1","/docs/theme-reco/theme.html",{"title":"theme"},["/docs/theme-reco/theme","/docs/theme-reco/theme.md"]],
  ["v-b30fe9a8","/blogs/coding/gitxiangguan/Git ziwenjianjiayudulifenzhiguanli.html",{"title":"Git 子文件夹与独立分支管理"},["/blogs/coding/gitxiangguan/Git ziwenjianjiayudulifenzhiguanli","/blogs/coding/git相关/Git 子文件夹与独立分支管理.html","/blogs/coding/git%E7%9B%B8%E5%85%B3/Git%20%E5%AD%90%E6%96%87%E4%BB%B6%E5%A4%B9%E4%B8%8E%E7%8B%AC%E7%AB%8B%E5%88%86%E6%94%AF%E7%AE%A1%E7%90%86.html","/blogs/coding/git相关/Git 子文件夹与独立分支管理.md","/blogs/coding/git%E7%9B%B8%E5%85%B3/Git%20%E5%AD%90%E6%96%87%E4%BB%B6%E5%A4%B9%E4%B8%8E%E7%8B%AC%E7%AB%8B%E5%88%86%E6%94%AF%E7%AE%A1%E7%90%86.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
]
