export const pagesRoutes = [
  ["v-01560935","/timeline/",{"title":""},["/timeline/index.html"]],
  ["v-290a88b4","/categories/category1/1/",{"title":""},["/categories/category1/1/index.html"]],
  ["v-290afd13","/categories/category2/1/",{"title":""},["/categories/category2/1/index.html"]],
  ["v-b5b53d90","/tags/tag2/1/",{"title":""},["/tags/tag2/1/index.html"]],
  ["v-b5b6264e","/tags/tag1/1/",{"title":""},["/tags/tag1/1/index.html"]],
  ["v-b5b36c14","/tags/tag4/1/",{"title":""},["/tags/tag4/1/index.html"]],
  ["v-b5b454d2","/tags/tag3/1/",{"title":""},["/tags/tag3/1/index.html"]],
  ["v-03d52fd3","/posts/1/",{"title":""},["/posts/1/index.html"]],
  ["v-13fe50c9","/README.en.html",{"title":"Hblog"},["/README.en","/README.en.md"]],
  ["v-8daa1a0e","/",{"title":""},["/index.html","/README.md"]],
  ["v-5f35402f","/docs/Basics/WebBasics.html",{"title":""},["/docs/Basics/WebBasics","/docs/Basics/WebBasics.md"]],
  ["v-380c62c8","/docs/Compontents/BlogHome.html",{"title":""},["/docs/Compontents/BlogHome","/docs/Compontents/BlogHome.md"]],
  ["v-77df0062","/docs/Compontents/ChargingAnimation.html",{"title":""},["/docs/Compontents/ChargingAnimation","/docs/Compontents/ChargingAnimation.md"]],
  ["v-f0c47d04","/docs/Compontents/ChargingAnimation2.html",{"title":""},["/docs/Compontents/ChargingAnimation2","/docs/Compontents/ChargingAnimation2.md"]],
  ["v-683004ef","/docs/Compontents/Check-Box.html",{"title":""},["/docs/Compontents/Check-Box","/docs/Compontents/Check-Box.md"]],
  ["v-30911082","/docs/Compontents/CodeBackground.html",{"title":""},["/docs/Compontents/CodeBackground","/docs/Compontents/CodeBackground.md"]],
  ["v-8a99b23e","/docs/Compontents/Evaluation.html",{"title":""},["/docs/Compontents/Evaluation","/docs/Compontents/Evaluation.md"]],
  ["v-8d413d4a","/docs/Compontents/GradientButton.html",{"title":""},["/docs/Compontents/GradientButton","/docs/Compontents/GradientButton.md"]],
  ["v-31abb803","/docs/Compontents/InputAnimation.html",{"title":""},["/docs/Compontents/InputAnimation","/docs/Compontents/InputAnimation.md"]],
  ["v-7472ddf0","/docs/Compontents/LikeAnimation.html",{"title":""},["/docs/Compontents/LikeAnimation","/docs/Compontents/LikeAnimation.md"]],
  ["v-39d2fc22","/docs/Compontents/Loading-CodeStyle.html",{"title":""},["/docs/Compontents/Loading-CodeStyle","/docs/Compontents/Loading-CodeStyle.md"]],
  ["v-39ee1d1e","/docs/Compontents/Loading-LiquidStyle.html",{"title":""},["/docs/Compontents/Loading-LiquidStyle","/docs/Compontents/Loading-LiquidStyle.md"]],
  ["v-95c69932","/docs/Compontents/Loading-LoveStyle.html",{"title":""},["/docs/Compontents/Loading-LoveStyle","/docs/Compontents/Loading-LoveStyle.md"]],
  ["v-ebc58e60","/docs/Compontents/MenuAnimation.html",{"title":""},["/docs/Compontents/MenuAnimation","/docs/Compontents/MenuAnimation.md"]],
  ["v-0cab1a30","/docs/Compontents/MergeText.html",{"title":""},["/docs/Compontents/MergeText","/docs/Compontents/MergeText.md"]],
  ["v-46eec34e","/docs/Compontents/RingMenu.html",{"title":""},["/docs/Compontents/RingMenu","/docs/Compontents/RingMenu.md"]],
  ["v-32a6e07a","/docs/Compontents/RingTrack.html",{"title":""},["/docs/Compontents/RingTrack","/docs/Compontents/RingTrack.md"]],
  ["v-3aa39a76","/docs/Compontents/Round3D.html",{"title":""},["/docs/Compontents/Round3D","/docs/Compontents/Round3D.md"]],
  ["v-db305b2a","/docs/Compontents/test.html",{"title":""},["/docs/Compontents/test","/docs/Compontents/test.md"]],
  ["v-38739e92","/docs/Compontents/Title-effect.html",{"title":""},["/docs/Compontents/Title-effect","/docs/Compontents/Title-effect.md"]],
  ["v-41cff211","/docs/Compontents/TitleAnimation.html",{"title":""},["/docs/Compontents/TitleAnimation","/docs/Compontents/TitleAnimation.md"]],
  ["v-cf7e8f2a","/docs/Guide/guide.html",{"title":"VuePress-guide"},["/docs/Guide/guide","/docs/Guide/guide.md"]],
  ["v-6ec390a4","/docs/JavaScript/v-for.html",{"title":""},["/docs/JavaScript/v-for","/docs/JavaScript/v-for.md"]],
  ["v-01f485e2","/docs/JAVAStudyNote/1.Javagaishu.html",{"title":""},["/docs/JAVAStudyNote/1.Javagaishu","/docs/JAVAStudyNote/1.Java概述.html","/docs/JAVAStudyNote/1.Java%E6%A6%82%E8%BF%B0.html","/docs/JAVAStudyNote/1.Java概述.md","/docs/JAVAStudyNote/1.Java%E6%A6%82%E8%BF%B0.md"]],
  ["v-6d91a85e","/docs/JAVAStudyNote/2.bianliangyuyunsuanfu.html",{"title":""},["/docs/JAVAStudyNote/2.bianliangyuyunsuanfu","/docs/JAVAStudyNote/2.变量与运算符.html","/docs/JAVAStudyNote/2.%E5%8F%98%E9%87%8F%E4%B8%8E%E8%BF%90%E7%AE%97%E7%AC%A6.html","/docs/JAVAStudyNote/2.变量与运算符.md","/docs/JAVAStudyNote/2.%E5%8F%98%E9%87%8F%E4%B8%8E%E8%BF%90%E7%AE%97%E7%AC%A6.md"]],
  ["v-9ae9b208","/docs/Python/1.bianliang_nazhihanshu.html",{"title":""},["/docs/Python/1.bianliang_nazhihanshu","/docs/Python/1.变量,内置函数.html","/docs/Python/1.%E5%8F%98%E9%87%8F,%E5%86%85%E7%BD%AE%E5%87%BD%E6%95%B0.html","/docs/Python/1.变量,内置函数.md","/docs/Python/1.%E5%8F%98%E9%87%8F,%E5%86%85%E7%BD%AE%E5%87%BD%E6%95%B0.md"]],
  ["v-acdd9360","/docs/theme-reco/api.html",{"title":"api"},["/docs/theme-reco/api","/docs/theme-reco/api.md"]],
  ["v-48c1226e","/docs/theme-reco/guide.html",{"title":"vuepress-theme-reco"},["/docs/theme-reco/guide","/docs/theme-reco/guide.md"]],
  ["v-5cd03a29","/docs/theme-reco/home.html",{"title":"theme-reco"},["/docs/theme-reco/home","/docs/theme-reco/home.md"]],
  ["v-456cc6d6","/docs/theme-reco/plugin.html",{"title":"plugin"},["/docs/theme-reco/plugin","/docs/theme-reco/plugin.md"]],
  ["v-65959fc1","/docs/theme-reco/theme.html",{"title":"theme"},["/docs/theme-reco/theme","/docs/theme-reco/theme.md"]],
  ["v-32598bfc","/blogs/category1/2018/121501.html",{"title":"first page in category1"},["/blogs/category1/2018/121501","/blogs/category1/2018/121501.md"]],
  ["v-2eb9b31a","/blogs/category1/2019/092101.html",{"title":"second page in category1"},["/blogs/category1/2019/092101","/blogs/category1/2019/092101.md"]],
  ["v-19e56119","/blogs/category2/2016/121501.html",{"title":"first page in category2"},["/blogs/category2/2016/121501","/blogs/category2/2016/121501.md"]],
  ["v-16458837","/blogs/category2/2017/092101.html",{"title":"second page in category2"},["/blogs/category2/2017/092101","/blogs/category2/2017/092101.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
]
