<template><div><div align="center">
  <h1> 30 天 Python：第 7 天 - 集合</h1>
  <a class="header-badge" target="_blank" href="https://www.linkedin.com/in/asabeneh/">
  <img src="https://img.shields.io/badge/style--5eba00.svg?label=LinkedIn&logo=linkedin&style=social">
  </a>
  <a class="header-badge" target="_blank" href="https://twitter.com/Asabeneh">
  <img alt="Twitter Follow" src="https://img.shields.io/twitter/follow/asabeneh?style=social">
  </a>
<p><sub>作者：
<a href="https://www.linkedin.com/in/asabeneh/" target="_blank">Asabeneh Yetayeh</a><br>
<small> 第二版：2021 年 7 月</small>
</sub></p>
</div>
<p><RouterLink to="/docs/Python/06_tuples.html">&lt;&lt; 第 6 天</RouterLink> | <RouterLink to="/docs/Python/08_dictionaries.html">第 8 天 &gt;&gt;</RouterLink></p>
<p><img src="@source/docs/images/30DaysOfPython_banner3@2x.png" alt="30DaysOfPython"></p>
<ul>
<li><a href="#-%E7%AC%AC-7-%E5%A4%A9">📘 第 7 天</a>
<ul>
<li><a href="#%E9%9B%86%E5%90%88">集合</a>
<ul>
<li><a href="#%E5%88%9B%E5%BB%BA%E9%9B%86%E5%90%88">创建集合</a></li>
<li><a href="#%E8%8E%B7%E5%8F%96%E9%9B%86%E5%90%88%E9%95%BF%E5%BA%A6">获取集合长度</a></li>
<li><a href="#%E8%AE%BF%E9%97%AE%E9%9B%86%E5%90%88%E4%B8%AD%E7%9A%84%E9%A1%B9%E7%9B%AE">访问集合中的项目</a></li>
<li><a href="#%E6%A3%80%E6%9F%A5%E9%A1%B9%E7%9B%AE">检查项目</a></li>
<li><a href="#%E5%90%91%E9%9B%86%E5%90%88%E4%B8%AD%E6%B7%BB%E5%8A%A0%E9%A1%B9%E7%9B%AE">向集合中添加项目</a></li>
<li><a href="#%E4%BB%8E%E9%9B%86%E5%90%88%E4%B8%AD%E7%A7%BB%E9%99%A4%E9%A1%B9%E7%9B%AE">从集合中移除项目</a></li>
<li><a href="#%E6%B8%85%E7%A9%BA%E9%9B%86%E5%90%88%E4%B8%AD%E7%9A%84%E9%A1%B9%E7%9B%AE">清空集合中的项目</a></li>
<li><a href="#%E5%88%A0%E9%99%A4%E9%9B%86%E5%90%88">删除集合</a></li>
<li><a href="#%E5%B0%86%E5%88%97%E8%A1%A8%E8%BD%AC%E6%8D%A2%E4%B8%BA%E9%9B%86%E5%90%88">将列表转换为集合</a></li>
<li><a href="#%E5%90%88%E5%B9%B6%E9%9B%86%E5%90%88">合并集合</a></li>
<li><a href="#%E6%9F%A5%E6%89%BE%E4%BA%A4%E9%9B%86%E9%A1%B9%E7%9B%AE">查找交集项目</a></li>
<li><a href="#%E6%A3%80%E6%9F%A5%E5%AD%90%E9%9B%86%E5%92%8C%E8%B6%85%E9%9B%86">检查子集和超集</a></li>
<li><a href="#%E6%A3%80%E6%9F%A5%E4%B8%A4%E4%B8%AA%E9%9B%86%E5%90%88%E4%B9%8B%E9%97%B4%E7%9A%84%E5%B7%AE%E5%BC%82">检查两个集合之间的差异</a></li>
<li><a href="#%E6%9F%A5%E6%89%BE%E4%B8%A4%E4%B8%AA%E9%9B%86%E5%90%88%E4%B9%8B%E9%97%B4%E7%9A%84%E5%AF%B9%E7%A7%B0%E5%B7%AE%E5%BC%82">查找两个集合之间的对称差异</a></li>
<li><a href="#%E5%90%88%E5%B9%B6%E9%9B%86%E5%90%88-1">合并集合</a></li>
</ul>
</li>
<li><a href="#-%E7%BB%83%E4%B9%A0-%E7%AC%AC-7-%E5%A4%A9">💻 练习：第 7 天</a>
<ul>
<li><a href="#%E7%BB%83%E4%B9%A0-%E7%AD%89%E7%BA%A7-1">练习：等级 1</a></li>
<li><a href="#%E7%BB%83%E4%B9%A0-%E7%AD%89%E7%BA%A7-2">练习：等级 2</a></li>
<li><a href="#%E7%BB%83%E4%B9%A0-%E7%AD%89%E7%BA%A7-3">练习：等级 3</a></li>
</ul>
</li>
</ul>
</li>
</ul>
<h1 id="📘-第-7-天" tabindex="-1"><a class="header-anchor" href="#📘-第-7-天" aria-hidden="true">#</a> 📘 第 7 天</h1>
<h2 id="集合" tabindex="-1"><a class="header-anchor" href="#集合" aria-hidden="true">#</a> 集合</h2>
<p>集合是项目的集合。让我带你回到小学或高中的数学课。集合的数学定义也适用于 Python。集合是无序且未索引的不同元素的集合。在 Python 中，集合用于存储唯一项目，可以在集合之间找到 <em>并集</em>、<em>交集</em>、<em>差集</em>、<em>对称差集</em>、<em>子集</em>、<em>超集</em> 和 <em>不相交集</em>。</p>
<h3 id="创建集合" tabindex="-1"><a class="header-anchor" href="#创建集合" aria-hidden="true">#</a> 创建集合</h3>
<p>我们使用 <em>set()</em> 内置函数。</p>
<ul>
<li>创建空集合</li>
</ul>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
st <span class="token operator">=</span> <span class="token builtin">set</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>创建一个包含初始项目的集合</li>
</ul>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
st <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item1'</span><span class="token punctuation">,</span> <span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">,</span> <span class="token string">'item4'</span><span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
fruits <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'banana'</span><span class="token punctuation">,</span> <span class="token string">'orange'</span><span class="token punctuation">,</span> <span class="token string">'mango'</span><span class="token punctuation">,</span> <span class="token string">'lemon'</span><span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="获取设置的长度" tabindex="-1"><a class="header-anchor" href="#获取设置的长度" aria-hidden="true">#</a> 获取设置的长度</h3>
<p>我们使用**len()**方法来查找集合的长度。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
st <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item1'</span><span class="token punctuation">,</span> <span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">,</span> <span class="token string">'item4'</span><span class="token punctuation">}</span>
<span class="token builtin">len</span><span class="token punctuation">(</span>st<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>fruits <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'banana'</span><span class="token punctuation">,</span> <span class="token string">'orange'</span><span class="token punctuation">,</span> <span class="token string">'mango'</span><span class="token punctuation">,</span> <span class="token string">'lemon'</span><span class="token punctuation">}</span>
<span class="token builtin">len</span><span class="token punctuation">(</span>fruits<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="访问集合中的项目" tabindex="-1"><a class="header-anchor" href="#访问集合中的项目" aria-hidden="true">#</a> 访问集合中的项目</h3>
<p>我们使用循环来访问项目。我们将在循环部分看到这一点。</p>
<h3 id="检查项目" tabindex="-1"><a class="header-anchor" href="#检查项目" aria-hidden="true">#</a> 检查项目</h3>
<p>要检查列表中是否存在某个项目，我们使用 <em>in</em> 成员运算符。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
st <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item1'</span><span class="token punctuation">,</span> <span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">,</span> <span class="token string">'item4'</span><span class="token punctuation">}</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"Does set st contain item3? "</span><span class="token punctuation">,</span> <span class="token string">'item3'</span> <span class="token keyword">in</span> st<span class="token punctuation">)</span> <span class="token comment"># Does set st contain item3? True</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>
fruits <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'香蕉'</span><span class="token punctuation">,</span> <span class="token string">'橙色'</span><span class="token punctuation">,</span> <span class="token string">'芒果'</span><span class="token punctuation">,</span> <span class="token string">'柠檬'</span><span class="token punctuation">}</span>

<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'芒果'</span> <span class="token keyword">in</span> fruits <span class="token punctuation">)</span> <span class="token comment"># True</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="向集合中添加元素" tabindex="-1"><a class="header-anchor" href="#向集合中添加元素" aria-hidden="true">#</a> 向集合中添加元素</h3>
<p>一旦集合创建后，我们不能改变其中的任何元素，但可以添加其他的元素。</p>
<ul>
<li>使用 <em>add()</em> 方法添加单个元素</li>
</ul>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
st <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item1'</span><span class="token punctuation">,</span> <span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">,</span> <span class="token string">'item4'</span><span class="token punctuation">}</span>
st<span class="token punctuation">.</span>add<span class="token punctuation">(</span><span class="token string">'item5'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例:</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>fruits <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'banana'</span><span class="token punctuation">,</span> <span class="token string">'orange'</span><span class="token punctuation">,</span> <span class="token string">'mango'</span><span class="token punctuation">,</span> <span class="token string">'lemon'</span><span class="token punctuation">}</span>
fruits<span class="token punctuation">.</span>add<span class="token punctuation">(</span><span class="token string">'lime'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>使用 <em>update()</em> 方法添加多个元素
<em>update()</em> 方法允许向集合中添加多个元素。<em>update()</em> 接收一个列表作为参数。</li>
</ul>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
st <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item1'</span><span class="token punctuation">,</span> <span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">,</span> <span class="token string">'item4'</span><span class="token punctuation">}</span>
st<span class="token punctuation">.</span>update<span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">'item5'</span><span class="token punctuation">,</span><span class="token string">'item6'</span><span class="token punctuation">,</span><span class="token string">'item7'</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例:</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>fruits <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'banana'</span><span class="token punctuation">,</span> <span class="token string">'orange'</span><span class="token punctuation">,</span> <span class="token string">'mango'</span><span class="token punctuation">,</span> <span class="token string">'lemon'</span><span class="token punctuation">}</span>
vegetables <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token string">'tomato'</span><span class="token punctuation">,</span> <span class="token string">'potato'</span><span class="token punctuation">,</span> <span class="token string">'cabbage'</span><span class="token punctuation">,</span><span class="token string">'onion'</span><span class="token punctuation">,</span> <span class="token string">'carrot'</span><span class="token punctuation">)</span>
fruits<span class="token punctuation">.</span>update<span class="token punctuation">(</span>vegetables<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="从集合中移除元素" tabindex="-1"><a class="header-anchor" href="#从集合中移除元素" aria-hidden="true">#</a> 从集合中移除元素</h3>
<p>我们可以使用 <em>remove()</em> 方法从集合中移除一个元素。如果找不到该元素，<em>remove()</em> 方法会抛出错误，因此最好先检查该元素是否存在于集合中。<em>discard()</em> 方法则不会抛出任何错误。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
st <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item1'</span><span class="token punctuation">,</span> <span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">,</span> <span class="token string">'item4'</span><span class="token punctuation">}</span>
st<span class="token punctuation">.</span>remove<span class="token punctuation">(</span><span class="token string">'item2'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><em>pop()</em> 方法从集合中移除一个随机元素并返回该被移除的元素。</p>
<p><strong>示例:</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>fruits <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'banana'</span><span class="token punctuation">,</span> <span class="token string">'orange'</span><span class="token punctuation">,</span> <span class="token string">'mango'</span><span class="token punctuation">,</span> <span class="token string">'lemon'</span><span class="token punctuation">}</span>
fruits<span class="token punctuation">.</span>pop<span class="token punctuation">(</span><span class="token punctuation">)</span>  <span class="token comment"># 从集合中移除一个随机元素</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>如果我们对被移除的元素感兴趣。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>fruits <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'banana'</span><span class="token punctuation">,</span> <span class="token string">'orange'</span><span class="token punctuation">,</span> <span class="token string">'mango'</span><span class="token punctuation">,</span> <span class="token string">'lemon'</span><span class="token punctuation">}</span>
removed_item <span class="token operator">=</span> fruits<span class="token punctuation">.</span>pop<span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="清空集合中的项目" tabindex="-1"><a class="header-anchor" href="#清空集合中的项目" aria-hidden="true">#</a> 清空集合中的项目</h3>
<p>如果我们想要清空或清除集合中的所有项目，可以使用 <em>clear</em> 方法。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
st <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item1'</span><span class="token punctuation">,</span> <span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">,</span> <span class="token string">'item4'</span><span class="token punctuation">}</span>
st<span class="token punctuation">.</span>clear<span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例:</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>fruits <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'banana'</span><span class="token punctuation">,</span> <span class="token string">'orange'</span><span class="token punctuation">,</span> <span class="token string">'mango'</span><span class="token punctuation">,</span> <span class="token string">'lemon'</span><span class="token punctuation">}</span>
fruits<span class="token punctuation">.</span>clear<span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>fruits<span class="token punctuation">)</span> <span class="token comment"># set()</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="删除一个集合" tabindex="-1"><a class="header-anchor" href="#删除一个集合" aria-hidden="true">#</a> 删除一个集合</h3>
<p>如果我们想要删除整个集合，可以使用 <em>del</em> 操作符。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
st <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item1'</span><span class="token punctuation">,</span> <span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">,</span> <span class="token string">'item4'</span><span class="token punctuation">}</span>
<span class="token keyword">del</span> st
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例:</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>fruits <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'banana'</span><span class="token punctuation">,</span> <span class="token string">'orange'</span><span class="token punctuation">,</span> <span class="token string">'mango'</span><span class="token punctuation">,</span> <span class="token string">'lemon'</span><span class="token punctuation">}</span>
<span class="token keyword">del</span> fruits
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="将列表转换为集合" tabindex="-1"><a class="header-anchor" href="#将列表转换为集合" aria-hidden="true">#</a> 将列表转换为集合</h3>
<p>我们可以将列表转换为集合，也可以将集合转换为列表。将列表转换为集合会去除重复项，只保留唯一项。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
lst <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'item1'</span><span class="token punctuation">,</span> <span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">,</span> <span class="token string">'item4'</span><span class="token punctuation">,</span> <span class="token string">'item1'</span><span class="token punctuation">]</span>
st <span class="token operator">=</span> <span class="token builtin">set</span><span class="token punctuation">(</span>lst<span class="token punctuation">)</span>  <span class="token comment"># {'item2', 'item4', 'item1', 'item3'} - 顺序是随机的，因为集合在一般情况下是无序的</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例:</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>fruits <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'banana'</span><span class="token punctuation">,</span> <span class="token string">'orange'</span><span class="token punctuation">,</span> <span class="token string">'mango'</span><span class="token punctuation">,</span> <span class="token string">'lemon'</span><span class="token punctuation">,</span><span class="token string">'orange'</span><span class="token punctuation">,</span> <span class="token string">'banana'</span><span class="token punctuation">]</span>
fruits <span class="token operator">=</span> <span class="token builtin">set</span><span class="token punctuation">(</span>fruits<span class="token punctuation">)</span> <span class="token comment"># {'mango', 'lemon', 'banana', 'orange'}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="合并集合" tabindex="-1"><a class="header-anchor" href="#合并集合" aria-hidden="true">#</a> 合并集合</h3>
<p>我们可以使用 <em>union()</em> 或 <em>update()</em> 方法来合并两个集合。</p>
<ul>
<li>Union
这个方法返回一个新集合</li>
</ul>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
st1 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item1'</span><span class="token punctuation">,</span> <span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">,</span> <span class="token string">'item4'</span><span class="token punctuation">}</span>
st2 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item5'</span><span class="token punctuation">,</span> <span class="token string">'item6'</span><span class="token punctuation">,</span> <span class="token string">'item7'</span><span class="token punctuation">,</span> <span class="token string">'item8'</span><span class="token punctuation">}</span>
st3 <span class="token operator">=</span> st1<span class="token punctuation">.</span>union<span class="token punctuation">(</span>st2<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例:</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>fruits <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'banana'</span><span class="token punctuation">,</span> <span class="token string">'orange'</span><span class="token punctuation">,</span> <span class="token string">'mango'</span><span class="token punctuation">,</span> <span class="token string">'lemon'</span><span class="token punctuation">}</span>
vegetables <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'tomato'</span><span class="token punctuation">,</span> <span class="token string">'potato'</span><span class="token punctuation">,</span> <span class="token string">'cabbage'</span><span class="token punctuation">,</span><span class="token string">'onion'</span><span class="token punctuation">,</span> <span class="token string">'carrot'</span><span class="token punctuation">}</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>fruits<span class="token punctuation">.</span>union<span class="token punctuation">(</span>vegetables<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># {'lemon', 'carrot', 'tomato', 'banana', 'mango', 'orange', 'cabbage', 'potato', 'onion'}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>Update
这个方法将一个集合插入到给定的集合中</li>
</ul>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
st1 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item1'</span><span class="token punctuation">,</span> <span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">,</span> <span class="token string">'item4'</span><span class="token punctuation">}</span>
st2 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item5'</span><span class="token punctuation">,</span> <span class="token string">'item6'</span><span class="token punctuation">,</span> <span class="token string">'item7'</span><span class="token punctuation">,</span> <span class="token string">'item8'</span><span class="token punctuation">}</span>
st1<span class="token punctuation">.</span>update<span class="token punctuation">(</span>st2<span class="token punctuation">)</span> <span class="token comment"># st2 的内容被添加到 st1 中</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例:</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>fruits <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'banana'</span><span class="token punctuation">,</span> <span class="token string">'orange'</span><span class="token punctuation">,</span> <span class="token string">'mango'</span><span class="token punctuation">,</span> <span class="token string">'lemon'</span><span class="token punctuation">}</span>
vegetables <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'tomato'</span><span class="token punctuation">,</span> <span class="token string">'potato'</span><span class="token punctuation">,</span> <span class="token string">'cabbage'</span><span class="token punctuation">,</span><span class="token string">'onion'</span><span class="token punctuation">,</span> <span class="token string">'carrot'</span><span class="token punctuation">}</span>
fruits<span class="token punctuation">.</span>update<span class="token punctuation">(</span>vegetables<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>fruits<span class="token punctuation">)</span> <span class="token comment"># {'lemon', 'carrot', 'tomato', 'banana', 'mango', 'orange', 'cabbage', 'potato', 'onion'}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="查找交集项" tabindex="-1"><a class="header-anchor" href="#查找交集项" aria-hidden="true">#</a> 查找交集项</h3>
<p>交集返回两个集合中都存在的项的集合。请参见示例</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
st1 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item1'</span><span class="token punctuation">,</span> <span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">,</span> <span class="token string">'item4'</span><span class="token punctuation">}</span>
st2 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item3'</span><span class="token punctuation">,</span> <span class="token string">'item2'</span><span class="token punctuation">}</span>
st1<span class="token punctuation">.</span>intersection<span class="token punctuation">(</span>st2<span class="token punctuation">)</span> <span class="token comment"># {'item3', 'item2'}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>whole_numbers <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">}</span>
even_numbers <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">}</span>
whole_numbers<span class="token punctuation">.</span>intersection<span class="token punctuation">(</span>even_numbers<span class="token punctuation">)</span> <span class="token comment"># {0, 2, 4, 6, 8, 10}</span>

python <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'p'</span><span class="token punctuation">,</span> <span class="token string">'y'</span><span class="token punctuation">,</span> <span class="token string">'t'</span><span class="token punctuation">,</span> <span class="token string">'h'</span><span class="token punctuation">,</span> <span class="token string">'o'</span><span class="token punctuation">,</span> <span class="token string">'n'</span><span class="token punctuation">}</span>
dragon <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'d'</span><span class="token punctuation">,</span> <span class="token string">'r'</span><span class="token punctuation">,</span> <span class="token string">'a'</span><span class="token punctuation">,</span> <span class="token string">'g'</span><span class="token punctuation">,</span> <span class="token string">'o'</span><span class="token punctuation">,</span> <span class="token string">'n'</span><span class="token punctuation">}</span>
python<span class="token punctuation">.</span>intersection<span class="token punctuation">(</span>dragon<span class="token punctuation">)</span>     <span class="token comment"># {'o', 'n'}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="检查子集和超集" tabindex="-1"><a class="header-anchor" href="#检查子集和超集" aria-hidden="true">#</a> 检查子集和超集</h3>
<p>一个集合可以是另一个集合的子集或超集：</p>
<ul>
<li>子集: <em>issubset()</em></li>
<li>超集: <em>issuperset</em></li>
</ul>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
st1 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item1'</span><span class="token punctuation">,</span> <span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">,</span> <span class="token string">'item4'</span><span class="token punctuation">}</span>
st2 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">}</span>
st2<span class="token punctuation">.</span>issubset<span class="token punctuation">(</span>st1<span class="token punctuation">)</span> <span class="token comment"># True</span>
st1<span class="token punctuation">.</span>issuperset<span class="token punctuation">(</span>st2<span class="token punctuation">)</span> <span class="token comment"># True</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>whole_numbers <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">}</span>
even_numbers <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">}</span>
whole_numbers<span class="token punctuation">.</span>issubset<span class="token punctuation">(</span>even_numbers<span class="token punctuation">)</span> <span class="token comment"># 错误，因为它是超集</span>
whole_numbers<span class="token punctuation">.</span>issuperset<span class="token punctuation">(</span>even_numbers<span class="token punctuation">)</span> <span class="token comment"># 正确</span>

python <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'p'</span><span class="token punctuation">,</span> <span class="token string">'y'</span><span class="token punctuation">,</span> <span class="token string">'t'</span><span class="token punctuation">,</span> <span class="token string">'h'</span><span class="token punctuation">,</span> <span class="token string">'o'</span><span class="token punctuation">,</span> <span class="token string">'n'</span><span class="token punctuation">}</span>
dragon <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'d'</span><span class="token punctuation">,</span> <span class="token string">'r'</span><span class="token punctuation">,</span> <span class="token string">'a'</span><span class="token punctuation">,</span> <span class="token string">'g'</span><span class="token punctuation">,</span> <span class="token string">'o'</span><span class="token punctuation">,</span> <span class="token string">'n'</span><span class="token punctuation">}</span>
python<span class="token punctuation">.</span>issubset<span class="token punctuation">(</span>dragon<span class="token punctuation">)</span>     <span class="token comment"># 错误</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="检查两个集合之间的差异" tabindex="-1"><a class="header-anchor" href="#检查两个集合之间的差异" aria-hidden="true">#</a> 检查两个集合之间的差异</h3>
<p>它返回两个集合之间的差异。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
st1 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item1'</span><span class="token punctuation">,</span> <span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">,</span> <span class="token string">'item4'</span><span class="token punctuation">}</span>
st2 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">}</span>
st2<span class="token punctuation">.</span>difference<span class="token punctuation">(</span>st1<span class="token punctuation">)</span> <span class="token comment"># set()</span>
st1<span class="token punctuation">.</span>difference<span class="token punctuation">(</span>st2<span class="token punctuation">)</span> <span class="token comment"># {'item1', 'item4'} => st1\st2</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>whole_numbers <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">}</span>
even_numbers <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">}</span>
whole_numbers<span class="token punctuation">.</span>difference<span class="token punctuation">(</span>even_numbers<span class="token punctuation">)</span> <span class="token comment"># {1, 3, 5, 7, 9}</span>

python <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'p'</span><span class="token punctuation">,</span> <span class="token string">'y'</span><span class="token punctuation">,</span> <span class="token string">'t'</span><span class="token punctuation">,</span> <span class="token string">'o'</span><span class="token punctuation">,</span> <span class="token string">'n'</span><span class="token punctuation">}</span>
dragon <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'d'</span><span class="token punctuation">,</span> <span class="token string">'r'</span><span class="token punctuation">,</span> <span class="token string">'a'</span><span class="token punctuation">,</span> <span class="token string">'g'</span><span class="token punctuation">,</span> <span class="token string">'o'</span><span class="token punctuation">,</span> <span class="token string">'n'</span><span class="token punctuation">}</span>
python<span class="token punctuation">.</span>difference<span class="token punctuation">(</span>dragon<span class="token punctuation">)</span>     <span class="token comment"># {'p', 'y', 't'}  - 结果是无序的（集合的特性）</span>
dragon<span class="token punctuation">.</span>difference<span class="token punctuation">(</span>python<span class="token punctuation">)</span>     <span class="token comment"># {'d', 'r', 'a', 'g'}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="查找两个集合之间的对称差异" tabindex="-1"><a class="header-anchor" href="#查找两个集合之间的对称差异" aria-hidden="true">#</a> 查找两个集合之间的对称差异</h3>
<p>它返回两个集合之间的对称差异。它意味着它返回一个包含两个集合中所有项的集合，除了同时出现在两个集合中的项，数学上：(A\B) ∪ (B\A)</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
st1 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item1'</span><span class="token punctuation">,</span> <span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">,</span> <span class="token string">'item4'</span><span class="token punctuation">}</span>
st2 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">}</span>
<span class="token comment"># 意思是 (A\B)∪(B\A)</span>
st2<span class="token punctuation">.</span>symmetric_difference<span class="token punctuation">(</span>st1<span class="token punctuation">)</span> <span class="token comment"># {'item1', 'item4'}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>whole_numbers <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">}</span>
some_numbers <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">}</span>
whole_numbers<span class="token punctuation">.</span>symmetric_difference<span class="token punctuation">(</span>some_numbers<span class="token punctuation">)</span> <span class="token comment"># {0, 6, 7, 8, 9, 10}</span>

python <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'p'</span><span class="token punctuation">,</span> <span class="token string">'y'</span><span class="token punctuation">,</span> <span class="token string">'t'</span><span class="token punctuation">,</span> <span class="token string">'h'</span><span class="token punctuation">,</span> <span class="token string">'o'</span><span class="token punctuation">,</span> <span class="token string">'n'</span><span class="token punctuation">}</span>
dragon <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'d'</span><span class="token punctuation">,</span> <span class="token string">'r'</span><span class="token punctuation">,</span> <span class="token string">'a'</span><span class="token punctuation">,</span> <span class="token string">'g'</span><span class="token punctuation">,</span> <span class="token string">'o'</span><span class="token punctuation">,</span> <span class="token string">'n'</span><span class="token punctuation">}</span>
python<span class="token punctuation">.</span>symmetric_difference<span class="token punctuation">(</span>dragon<span class="token punctuation">)</span>  <span class="token comment"># {'r', 't', 'p', 'y', 'g', 'a', 'd', 'h'}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="合并集合-1" tabindex="-1"><a class="header-anchor" href="#合并集合-1" aria-hidden="true">#</a> 合并集合</h3>
<p>如果两个集合没有共同的项或项，我们称它们为不相交集合。我们可以使用 <em>isdisjoint()</em> 方法来检查两个集合是否相交。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
st1 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item1'</span><span class="token punctuation">,</span> <span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">,</span> <span class="token string">'item4'</span><span class="token punctuation">}</span>
st2 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'item2'</span><span class="token punctuation">,</span> <span class="token string">'item3'</span><span class="token punctuation">}</span>
st2<span class="token punctuation">.</span>isdisjoint<span class="token punctuation">(</span>st1<span class="token punctuation">)</span> <span class="token comment"># 错误</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>even_numbers <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">}</span>
odd_numbers <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">}</span>
even_numbers<span class="token punctuation">.</span>isdisjoint<span class="token punctuation">(</span>odd_numbers<span class="token punctuation">)</span> <span class="token comment"># 正确，因为没有共同项</span>

python <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'p'</span><span class="token punctuation">,</span> <span class="token string">'y'</span><span class="token punctuation">,</span> <span class="token string">'t'</span><span class="token punctuation">,</span> <span class="token string">'h'</span><span class="token punctuation">,</span> <span class="token string">'o'</span><span class="token punctuation">,</span> <span class="token string">'n'</span><span class="token punctuation">}</span>
dragon <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'d'</span><span class="token punctuation">,</span> <span class="token string">'r'</span><span class="token punctuation">,</span> <span class="token string">'a'</span><span class="token punctuation">,</span> <span class="token string">'g'</span><span class="token punctuation">,</span> <span class="token string">'o'</span><span class="token punctuation">,</span> <span class="token string">'n'</span><span class="token punctuation">}</span>
python<span class="token punctuation">.</span>isdisjoint<span class="token punctuation">(</span>dragon<span class="token punctuation">)</span>  <span class="token comment"># 错误，有共同项 {'o', 'n'}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>🌕 你是一颗冉冉升起的明星。你刚刚完成了第 7 天的挑战，你在通往伟大的道路上前进了 7 步。现在为你的大脑和肌肉做一些练习。</p>
<h2 id="💻-练习-第-7-天" tabindex="-1"><a class="header-anchor" href="#💻-练习-第-7-天" aria-hidden="true">#</a> 💻 练习：第 7 天</h2>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 集合</span>
it_companies <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'Facebook'</span><span class="token punctuation">,</span> <span class="token string">'Google'</span><span class="token punctuation">,</span> <span class="token string">'Microsoft'</span><span class="token punctuation">,</span> <span class="token string">'Apple'</span><span class="token punctuation">,</span> <span class="token string">'IBM'</span><span class="token punctuation">,</span> <span class="token string">'Oracle'</span><span class="token punctuation">,</span> <span class="token string">'Amazon'</span><span class="token punctuation">}</span>
A <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token number">19</span><span class="token punctuation">,</span> <span class="token number">22</span><span class="token punctuation">,</span> <span class="token number">24</span><span class="token punctuation">,</span> <span class="token number">20</span><span class="token punctuation">,</span> <span class="token number">25</span><span class="token punctuation">,</span> <span class="token number">26</span><span class="token punctuation">}</span>
B <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token number">19</span><span class="token punctuation">,</span> <span class="token number">22</span><span class="token punctuation">,</span> <span class="token number">20</span><span class="token punctuation">,</span> <span class="token number">25</span><span class="token punctuation">,</span> <span class="token number">26</span><span class="token punctuation">,</span> <span class="token number">24</span><span class="token punctuation">,</span> <span class="token number">28</span><span class="token punctuation">,</span> <span class="token number">27</span><span class="token punctuation">}</span>
age <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">22</span><span class="token punctuation">,</span> <span class="token number">19</span><span class="token punctuation">,</span> <span class="token number">24</span><span class="token punctuation">,</span> <span class="token number">25</span><span class="token punctuation">,</span> <span class="token number">26</span><span class="token punctuation">,</span> <span class="token number">24</span><span class="token punctuation">,</span> <span class="token number">25</span><span class="token punctuation">,</span> <span class="token number">24</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="练习-第-1-级" tabindex="-1"><a class="header-anchor" href="#练习-第-1-级" aria-hidden="true">#</a> 练习：第 1 级</h3>
<ol>
<li>找到集合 it_companies 的长度</li>
<li>向 it_companies 添加'Twitter'</li>
<li>一次性向集合 it_companies 插入多个 IT 公司</li>
<li>从集合 it_companies 中移除一家公司</li>
<li>移除和丢弃之间有什么区别</li>
</ol>
<h3 id="练习-第-2-级" tabindex="-1"><a class="header-anchor" href="#练习-第-2-级" aria-hidden="true">#</a> 练习：第 2 级</h3>
<ol>
<li>合并 A 和 B</li>
<li>找到 A 和 B 的交集</li>
<li>A 是 B 的子集吗</li>
<li>A 和 B 是不相交集合吗</li>
<li>将 A 与 B 合并，反之亦然</li>
<li>A 和 B 之间的对称差异是什么</li>
<li>完全删除集合</li>
</ol>
<h3 id="练习-第-3-级" tabindex="-1"><a class="header-anchor" href="#练习-第-3-级" aria-hidden="true">#</a> 练习：第 3 级</h3>
<ol>
<li>将年龄转换为集合并比较列表和集合的长度，哪一个更大？</li>
<li>解释以下数据类型之间的区别：字符串、列表、元组和集合</li>
<li><em>我是一个老师，我喜欢激励和教导人们。</em> 这句句子中用了多少独特的单词？使用 split 方法和集合来获取独特的单词。</li>
</ol>
<p>🎉 恭喜！ 🎉</p>
<p><RouterLink to="/docs/Python/06_tuples.html">&lt;&lt; 第 6 天</RouterLink> | <RouterLink to="/docs/Python/08_dictionaries.html">第 8 天 &gt;&gt;</RouterLink></p>
</div></template>


