<template><div><div align="center">
  <h1>Python 30 天挑战：第 13 天 - 列表推导式</h1>
  <a class="header-badge" target="_blank" href="https://www.linkedin.com/in/asabeneh/">
  <img src="https://img.shields.io/badge/style--5eba00.svg?label=LinkedIn&logo=linkedin&style=social">
  </a>
  <a class="header-badge" target="_blank" href="https://twitter.com/Asabeneh">
  <img alt="Twitter Follow" src="https://img.shields.io/twitter/follow/asabeneh?style=social">
  </a>
<p><sub>作者:
<a href="https://www.linkedin.com/in/asabeneh/" target="_blank">Asabeneh Yetayeh</a><br>
<small>第二版: 2021 年 7 月</small>
</sub></p>
</div>
</div>
<p><RouterLink to="/docs/Python/12_modules.html">&lt;&lt; 第 12 天</RouterLink> | <RouterLink to="/docs/Python/14_higher_order_functions.html">第 14 天 &gt;&gt;</RouterLink></p>
<p><img src="@source/docs/images/30DaysOfPython_banner3@2x.png" alt="30DaysOfPython"></p>
<ul>
<li><a href="#%F0%9F%93%98-%E7%AC%AC-13-%E5%A4%A9">📘 第 13 天</a>
<ul>
<li><a href="#%E5%88%97%E8%A1%A8%E6%8E%A8%E5%AF%BC%E5%BC%8F">列表推导式</a></li>
<li><a href="#lambda%E5%87%BD%E6%95%B0">Lambda 函数</a>
<ul>
<li><a href="#%E5%88%9B%E5%BB%BA-lambda-%E5%87%BD%E6%95%B0">创建 Lambda 函数</a></li>
<li><a href="#lambda-%E5%87%BD%E6%95%B0%E5%9C%A8%E5%8F%A6%E4%B8%80%E4%B8%AA%E5%87%BD%E6%95%B0%E4%B8%AD">Lambda 函数在另一个函数中</a></li>
</ul>
</li>
<li><a href="#%F0%9F%92%BB-%E7%BB%83%E4%B9%A0%E7%AC%AC-13-%E5%A4%A9">💻 练习：第 13 天</a></li>
</ul>
</li>
</ul>
<h1 id="📘-第-13-天" tabindex="-1"><a class="header-anchor" href="#📘-第-13-天" aria-hidden="true">#</a> 📘 第 13 天</h1>
<h2 id="列表推导式" tabindex="-1"><a class="header-anchor" href="#列表推导式" aria-hidden="true">#</a> 列表推导式</h2>
<p>在 Python 中，列表推导式是一种从序列中创建列表的简洁方式。它是创建新列表的简短方法。列表推导式比使用 <em>for</em> 循环处理列表快得多。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
<span class="token punctuation">[</span>i <span class="token keyword">for</span> i <span class="token keyword">in</span> iterable <span class="token keyword">if</span> 表达式<span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>例子: 1</strong></p>
<p>例如，如果你想将字符串转换为字符列表。你可以使用几种方法。我们来看看其中的一些：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 一种方法</span>
language <span class="token operator">=</span> <span class="token string">'Python'</span>
lst <span class="token operator">=</span> <span class="token builtin">list</span><span class="token punctuation">(</span>language<span class="token punctuation">)</span>  <span class="token comment"># 将字符串转换为列表</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token builtin">type</span><span class="token punctuation">(</span>lst<span class="token punctuation">)</span><span class="token punctuation">)</span>      <span class="token comment"># list</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>lst<span class="token punctuation">)</span>            <span class="token comment"># ['P', 'y', 't', 'h', 'o', 'n']</span>

<span class="token comment"># 第二种方法: 列表推导式</span>
lst <span class="token operator">=</span> <span class="token punctuation">[</span>i <span class="token keyword">for</span> i <span class="token keyword">in</span> language<span class="token punctuation">]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token builtin">type</span><span class="token punctuation">(</span>lst<span class="token punctuation">)</span><span class="token punctuation">)</span>     <span class="token comment"># list</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>lst<span class="token punctuation">)</span>           <span class="token comment"># ['P', 'y', 't', 'h', 'o', 'n']</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>例子: 2</strong></p>
<p>例如，如果你想生成一个数字列表</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 生成数字</span>
numbers <span class="token operator">=</span> <span class="token punctuation">[</span>i <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">11</span><span class="token punctuation">)</span><span class="token punctuation">]</span>  <span class="token comment"># 生成从0到10的数字</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>numbers<span class="token punctuation">)</span>                    <span class="token comment"># [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]</span>

<span class="token comment"># 也可以在迭代过程中进行数学运算</span>
squares <span class="token operator">=</span> <span class="token punctuation">[</span>i <span class="token operator">*</span> i <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">11</span><span class="token punctuation">)</span><span class="token punctuation">]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>squares<span class="token punctuation">)</span>                    <span class="token comment"># [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]</span>

<span class="token comment"># 还可以生成元组列表</span>
numbers <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">(</span>i<span class="token punctuation">,</span> i <span class="token operator">*</span> i<span class="token punctuation">)</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">11</span><span class="token punctuation">)</span><span class="token punctuation">]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>numbers<span class="token punctuation">)</span>                    <span class="token comment"># [(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25)]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>例子: 3</strong></p>
<p>列表推导式可以与 if 表达式结合使用</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 生成偶数</span>
even_numbers <span class="token operator">=</span> <span class="token punctuation">[</span>i <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">21</span><span class="token punctuation">)</span> <span class="token keyword">if</span> i <span class="token operator">%</span> <span class="token number">2</span> <span class="token operator">==</span> <span class="token number">0</span><span class="token punctuation">]</span>  <span class="token comment"># 生成从0到21的偶数列表</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>even_numbers<span class="token punctuation">)</span>                    <span class="token comment"># [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]</span>

<span class="token comment"># 生成奇数</span>
odd_numbers <span class="token operator">=</span> <span class="token punctuation">[</span>i <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">21</span><span class="token punctuation">)</span> <span class="token keyword">if</span> i <span class="token operator">%</span> <span class="token number">2</span> <span class="token operator">!=</span> <span class="token number">0</span><span class="token punctuation">]</span>  <span class="token comment"># 生成从0到21的奇数列表</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>odd_numbers<span class="token punctuation">)</span>                      <span class="token comment"># [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]</span>

<span class="token comment"># 过滤数字：让我们从下面的列表中过滤出正偶数</span>
numbers <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token operator">-</span><span class="token number">8</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">7</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">3</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">]</span>
positive_even_numbers <span class="token operator">=</span> <span class="token punctuation">[</span>i <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">21</span><span class="token punctuation">)</span> <span class="token keyword">if</span> i <span class="token operator">%</span> <span class="token number">2</span> <span class="token operator">==</span> <span class="token number">0</span> <span class="token keyword">and</span> i <span class="token operator">></span> <span class="token number">0</span><span class="token punctuation">]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>positive_even_numbers<span class="token punctuation">)</span>           <span class="token comment"># [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]</span>

<span class="token comment"># 扁平化三维数组</span>
list_of_lists <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">7</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">]</span><span class="token punctuation">]</span>
flattened_list <span class="token operator">=</span> <span class="token punctuation">[</span>number <span class="token keyword">for</span> row <span class="token keyword">in</span> list_of_lists <span class="token keyword">for</span> number <span class="token keyword">in</span> row<span class="token punctuation">]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>flattened_list<span class="token punctuation">)</span>                  <span class="token comment"># [1, 2, 3, 4, 5, 6, 7, 8, 9]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="lambda-函数" tabindex="-1"><a class="header-anchor" href="#lambda-函数" aria-hidden="true">#</a> Lambda 函数</h2>
<p>Lambda 函数是没有名字的小匿名函数。它可以接受任意数量的参数，但只能有一个表达式。Lambda 函数类似于 JavaScript 中的匿名函数。当我们想在另一个函数中编写匿名函数时，需要它。</p>
<h3 id="创建-lambda-函数" tabindex="-1"><a class="header-anchor" href="#创建-lambda-函数" aria-hidden="true">#</a> 创建 Lambda 函数</h3>
<p>要创建一个 lambda 函数，我们使用 <em>lambda</em> 关键字，然后是一个或多个参数，再然后是一个表达式。请参阅下面的语法和示例。Lambda 函数不用 return，但它会隐式地返回表达式。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
x <span class="token operator">=</span> <span class="token keyword">lambda</span> param1<span class="token punctuation">,</span> param2<span class="token punctuation">,</span> param3<span class="token punctuation">:</span> param1 <span class="token operator">+</span> param2 <span class="token operator">+</span> param3
<span class="token keyword">print</span><span class="token punctuation">(</span>x<span class="token punctuation">(</span>arg1<span class="token punctuation">,</span> arg2<span class="token punctuation">,</span> arg3<span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例:</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 命名函数</span>
<span class="token keyword">def</span> <span class="token function">add_two_nums</span><span class="token punctuation">(</span>a<span class="token punctuation">,</span> b<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">return</span> a <span class="token operator">+</span> b

<span class="token keyword">print</span><span class="token punctuation">(</span>add_two_nums<span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">)</span><span class="token punctuation">)</span>  <span class="token comment"># 5</span>

<span class="token comment"># 让我们将上述函数更改为 lambda 函数</span>
add_two_nums <span class="token operator">=</span> <span class="token keyword">lambda</span> a<span class="token punctuation">,</span> b<span class="token punctuation">:</span> a <span class="token operator">+</span> b
<span class="token keyword">print</span><span class="token punctuation">(</span>add_two_nums<span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">)</span><span class="token punctuation">)</span>  <span class="token comment"># 5</span>

<span class="token comment"># 自调用 lambda 函数</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token keyword">lambda</span> a<span class="token punctuation">,</span> b<span class="token punctuation">:</span> a <span class="token operator">+</span> b<span class="token punctuation">)</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">)</span><span class="token punctuation">)</span>  <span class="token comment"># 5</span>

square <span class="token operator">=</span> <span class="token keyword">lambda</span> x<span class="token punctuation">:</span> x <span class="token operator">**</span> <span class="token number">2</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>square<span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">)</span><span class="token punctuation">)</span>    <span class="token comment"># 9</span>
cube <span class="token operator">=</span> <span class="token keyword">lambda</span> x<span class="token punctuation">:</span> x <span class="token operator">**</span> <span class="token number">3</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>cube<span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">)</span><span class="token punctuation">)</span>      <span class="token comment"># 27</span>

<span class="token comment"># 多个变量</span>
multiple_variable <span class="token operator">=</span> <span class="token keyword">lambda</span> a<span class="token punctuation">,</span> b<span class="token punctuation">,</span> c<span class="token punctuation">:</span> a <span class="token operator">**</span> <span class="token number">2</span> <span class="token operator">-</span> <span class="token number">3</span> <span class="token operator">*</span> b <span class="token operator">+</span> <span class="token number">4</span> <span class="token operator">*</span> c
<span class="token keyword">print</span><span class="token punctuation">(</span>multiple_variable<span class="token punctuation">(</span><span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">)</span><span class="token punctuation">)</span>  <span class="token comment"># 22</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="lambda-函数在另一个函数中" tabindex="-1"><a class="header-anchor" href="#lambda-函数在另一个函数中" aria-hidden="true">#</a> Lambda 函数在另一个函数中</h3>
<p>在另一个函数中使用 lambda 函数。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">def</span> <span class="token function">power</span><span class="token punctuation">(</span>x<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">return</span> <span class="token keyword">lambda</span> n<span class="token punctuation">:</span> x <span class="token operator">**</span> n

cube <span class="token operator">=</span> power<span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">)</span>   <span class="token comment"># 函数 power 现在需要两个单独的括号中的参数</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>cube<span class="token punctuation">)</span>          <span class="token comment"># 8</span>
two_power_of_five <span class="token operator">=</span> power<span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">(</span><span class="token number">5</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>two_power_of_five<span class="token punctuation">)</span>  <span class="token comment"># 32</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>🌕 继续保持良好的工作。保持动力，天空才是你的极限！你已经完成了第 13 天的挑战，你已经向伟大的目标迈出了 13 步。现在为你的大脑和肌肉来做一些练习。</p>
<h2 id="💻-练习-第-13-天" tabindex="-1"><a class="header-anchor" href="#💻-练习-第-13-天" aria-hidden="true">#</a> 💻 练习: 第 13 天</h2>
<ol>
<li>
<p>使用列表推导式过滤出列表中的负数和零：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>numbers <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token operator">-</span><span class="token number">4</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">3</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div></li>
<li>
<p>将以下列表中的列表展平为一维列表：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>list_of_lists <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">[</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token punctuation">[</span><span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">]</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token punctuation">[</span><span class="token number">7</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">]</span><span class="token punctuation">]</span><span class="token punctuation">]</span>

输出<span class="token punctuation">:</span>
<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>使用列表推导式创建以下元组列表：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token punctuation">[</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">,</span> <span class="token number">16</span><span class="token punctuation">,</span> <span class="token number">32</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">(</span><span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">,</span> <span class="token number">27</span><span class="token punctuation">,</span> <span class="token number">81</span><span class="token punctuation">,</span> <span class="token number">243</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">(</span><span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">16</span><span class="token punctuation">,</span> <span class="token number">64</span><span class="token punctuation">,</span> <span class="token number">256</span><span class="token punctuation">,</span> <span class="token number">1024</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">(</span><span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">25</span><span class="token punctuation">,</span> <span class="token number">125</span><span class="token punctuation">,</span> <span class="token number">625</span><span class="token punctuation">,</span> <span class="token number">3125</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">(</span><span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">36</span><span class="token punctuation">,</span> <span class="token number">216</span><span class="token punctuation">,</span> <span class="token number">1296</span><span class="token punctuation">,</span> <span class="token number">7776</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">(</span><span class="token number">7</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">,</span> <span class="token number">49</span><span class="token punctuation">,</span> <span class="token number">343</span><span class="token punctuation">,</span> <span class="token number">2401</span><span class="token punctuation">,</span> <span class="token number">16807</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">(</span><span class="token number">8</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">,</span> <span class="token number">64</span><span class="token punctuation">,</span> <span class="token number">512</span><span class="token punctuation">,</span> <span class="token number">4096</span><span class="token punctuation">,</span> <span class="token number">32768</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">(</span><span class="token number">9</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">9</span><span class="token punctuation">,</span> <span class="token number">81</span><span class="token punctuation">,</span> <span class="token number">729</span><span class="token punctuation">,</span> <span class="token number">6561</span><span class="token punctuation">,</span> <span class="token number">59049</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">,</span> <span class="token number">1000</span><span class="token punctuation">,</span> <span class="token number">10000</span><span class="token punctuation">,</span> <span class="token number">100000</span><span class="token punctuation">)</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>将以下列表展平成一个新列表：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>countries <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">[</span><span class="token punctuation">(</span><span class="token string">'芬兰'</span><span class="token punctuation">,</span> <span class="token string">'赫尔辛基'</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token punctuation">(</span><span class="token string">'瑞典'</span><span class="token punctuation">,</span> <span class="token string">'斯德哥尔摩'</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token punctuation">(</span><span class="token string">'挪威'</span><span class="token punctuation">,</span> <span class="token string">'奥斯陆'</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">]</span>
输出<span class="token punctuation">:</span>
<span class="token punctuation">[</span><span class="token punctuation">[</span><span class="token string">'芬兰'</span><span class="token punctuation">,</span> <span class="token string">'汇编'</span><span class="token punctuation">,</span> <span class="token string">'赫尔辛基'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string">'瑞典'</span><span class="token punctuation">,</span> <span class="token string">'SWE'</span><span class="token punctuation">,</span> <span class="token string">'斯德哥尔摩'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string">'挪威'</span><span class="token punctuation">,</span> <span class="token string">'NOR'</span><span class="token punctuation">,</span> <span class="token string">'奥斯陆'</span><span class="token punctuation">]</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>将以下列表转换为字典列表：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>countries <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">[</span><span class="token punctuation">(</span><span class="token string">'芬兰'</span><span class="token punctuation">,</span> <span class="token string">'赫尔辛基'</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token punctuation">(</span><span class="token string">'瑞典'</span><span class="token punctuation">,</span> <span class="token string">'斯德哥尔摩'</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token punctuation">(</span><span class="token string">'挪威'</span><span class="token punctuation">,</span> <span class="token string">'奥斯陆'</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">]</span>
输出<span class="token punctuation">:</span>
<span class="token punctuation">[</span><span class="token punctuation">{</span><span class="token string">'国家'</span><span class="token punctuation">:</span> <span class="token string">'芬兰'</span><span class="token punctuation">,</span> <span class="token string">'城市'</span><span class="token punctuation">:</span> <span class="token string">'赫尔辛基'</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">{</span><span class="token string">'国家'</span><span class="token punctuation">:</span> <span class="token string">'瑞典'</span><span class="token punctuation">,</span> <span class="token string">'城市'</span><span class="token punctuation">:</span> <span class="token string">'斯德哥尔摩'</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">{</span><span class="token string">'国家'</span><span class="token punctuation">:</span> <span class="token string">'挪威'</span><span class="token punctuation">,</span> <span class="token string">'城市'</span><span class="token punctuation">:</span> <span class="token string">'奥斯陆'</span><span class="token punctuation">}</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>将以下列表转换为连接字符串的列表：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>names <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">[</span><span class="token punctuation">(</span><span class="token string">'Asabeneh'</span><span class="token punctuation">,</span> <span class="token string">'Yetayeh'</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token punctuation">(</span><span class="token string">'David'</span><span class="token punctuation">,</span> <span class="token string">'Smith'</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token punctuation">(</span><span class="token string">'Donald'</span><span class="token punctuation">,</span> <span class="token string">'Trump'</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token punctuation">(</span><span class="token string">'Bill'</span><span class="token punctuation">,</span> <span class="token string">'Gates'</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">]</span>
输出<span class="token punctuation">:</span>
<span class="token punctuation">[</span><span class="token string">'Asabeneh Yetayeh'</span><span class="token punctuation">,</span> <span class="token string">'David Smith'</span><span class="token punctuation">,</span> <span class="token string">'Donald Trump'</span><span class="token punctuation">,</span> <span class="token string">'Bill Gates'</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>编写一个 lambda 函数，可以求解线性函数的斜率或 y 截距。</p>
</li>
</ol>
<p>🎉 祝贺你！🎉</p>
<p><RouterLink to="/docs/Python/12_modules.html">&lt;&lt; 第 12 天</RouterLink> | <RouterLink to="/docs/Python/14_higher_order_functions.html">第 14 天 &gt;&gt;</RouterLink></p>
</div></template>


