<template><div><div align="center">
  <h1> 30 Days Of Python: Day 15 - Python Type Errors </h1>
  <a class="header-badge" target="_blank" href="https://www.linkedin.com/in/asabeneh/">
  <img src="https://img.shields.io/badge/style--5eba00.svg?label=LinkedIn&logo=linkedin&style=social">
  </a>
  <a class="header-badge" target="_blank" href="https://twitter.com/Asabeneh">
  <img alt="Twitter Follow" src="https://img.shields.io/twitter/follow/asabeneh?style=social">
  </a>
<p><sub>Author:
<a href="https://www.linkedin.com/in/asabeneh/" target="_blank">Asabeneh Yetayeh</a><br>
<small> Second Edition: July, 2021</small>
</sub></p>
</div>
</div>
<p><RouterLink to="/docs/14_Day_Higher_order_functions/14_higher_order_functions.html">&lt;&lt; Day 14</RouterLink> | <RouterLink to="/docs/16_Day_Python_date_time/16_python_datetime.html">Day 16 &gt;&gt;</RouterLink></p>
<p><img src="@source/docs/images/30DaysOfPython_banner3@2x.png" alt="30DaysOfPython"></p>
<ul>
<li><a href="#-day-15">📘 Day 15</a>
<ul>
<li><a href="#python-error-types">Python Error Types</a>
<ul>
<li><a href="#syntaxerror">SyntaxError</a></li>
<li><a href="#nameerror">NameError</a></li>
<li><a href="#indexerror">IndexError</a></li>
<li><a href="#modulenotfounderror">ModuleNotFoundError</a></li>
<li><a href="#attributeerror">AttributeError</a></li>
<li><a href="#keyerror">KeyError</a></li>
<li><a href="#typeerror">TypeError</a></li>
<li><a href="#importerror">ImportError</a></li>
<li><a href="#valueerror">ValueError</a></li>
<li><a href="#zerodivisionerror">ZeroDivisionError</a></li>
</ul>
</li>
<li><a href="#-exercises-day-15">💻 Exercises: Day 15</a></li>
</ul>
</li>
</ul>
<h1 id="📘-day-15" tabindex="-1"><a class="header-anchor" href="#📘-day-15" aria-hidden="true">#</a> 📘 Day 15</h1>
<h2 id="python-error-types" tabindex="-1"><a class="header-anchor" href="#python-error-types" aria-hidden="true">#</a> Python Error Types</h2>
<p>When we write code it is common that we make a typo or some other common error. If our code fails to run, the Python interpreter will display a message, containing feedback with information on where the problem occurs and the type of an error. It will also sometimes gives us suggestions on a possible fix. Understanding different types of errors in programming languages will help us to debug our code quickly and also it makes us better at what we do.</p>
<p>Let us see the most common error types one by one. First let us open our Python interactive shell. Go to your you computer terminal and write 'python'. The python interactive shell will be opened.</p>
<h3 id="syntaxerror" tabindex="-1"><a class="header-anchor" href="#syntaxerror" aria-hidden="true">#</a> SyntaxError</h3>
<p><strong>Example 1: SyntaxError</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>asabeneh@Asabeneh<span class="token punctuation">:</span><span class="token operator">~</span>$ python
Python <span class="token number">3.9</span><span class="token number">.6</span> <span class="token punctuation">(</span>default<span class="token punctuation">,</span> Jun <span class="token number">28</span> <span class="token number">2021</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">:</span><span class="token number">26</span><span class="token punctuation">:</span><span class="token number">21</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span>Clang <span class="token number">11.0</span><span class="token number">.0</span> <span class="token punctuation">(</span>clang<span class="token operator">-</span><span class="token number">1100.0</span><span class="token number">.33</span><span class="token number">.8</span><span class="token punctuation">)</span><span class="token punctuation">]</span> on darwin
Type <span class="token string">"help"</span><span class="token punctuation">,</span> <span class="token string">"copyright"</span><span class="token punctuation">,</span> <span class="token string">"credits"</span> <span class="token keyword">or</span> <span class="token string">"license"</span> <span class="token keyword">for</span> more information<span class="token punctuation">.</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token keyword">print</span> <span class="token string">'hello world'</span>
  File <span class="token string">"&lt;stdin>"</span><span class="token punctuation">,</span> line <span class="token number">1</span>
    <span class="token keyword">print</span> <span class="token string">'hello world'</span>
                      <span class="token operator">^</span>
SyntaxError<span class="token punctuation">:</span> Missing parentheses <span class="token keyword">in</span> call to <span class="token string">'print'</span><span class="token punctuation">.</span> Did you mean <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'hello world'</span><span class="token punctuation">)</span>?
<span class="token operator">>></span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>As you can see we made a syntax error because we forgot to enclose the string with parenthesis and Python already suggests the solution. Let us fix it.</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>asabeneh@Asabeneh<span class="token punctuation">:</span><span class="token operator">~</span>$ python
Python <span class="token number">3.9</span><span class="token number">.6</span> <span class="token punctuation">(</span>default<span class="token punctuation">,</span> Jun <span class="token number">28</span> <span class="token number">2021</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">:</span><span class="token number">26</span><span class="token punctuation">:</span><span class="token number">21</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span>Clang <span class="token number">11.0</span><span class="token number">.0</span> <span class="token punctuation">(</span>clang<span class="token operator">-</span><span class="token number">1100.0</span><span class="token number">.33</span><span class="token number">.8</span><span class="token punctuation">)</span><span class="token punctuation">]</span> on darwin
Type <span class="token string">"help"</span><span class="token punctuation">,</span> <span class="token string">"copyright"</span><span class="token punctuation">,</span> <span class="token string">"credits"</span> <span class="token keyword">or</span> <span class="token string">"license"</span> <span class="token keyword">for</span> more information<span class="token punctuation">.</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token keyword">print</span> <span class="token string">'hello world'</span>
  File <span class="token string">"&lt;stdin>"</span><span class="token punctuation">,</span> line <span class="token number">1</span>
    <span class="token keyword">print</span> <span class="token string">'hello world'</span>
                      <span class="token operator">^</span>
SyntaxError<span class="token punctuation">:</span> Missing parentheses <span class="token keyword">in</span> call to <span class="token string">'print'</span><span class="token punctuation">.</span> Did you mean <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'hello world'</span><span class="token punctuation">)</span>?
<span class="token operator">>></span><span class="token operator">></span> <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'hello world'</span><span class="token punctuation">)</span>
hello world
<span class="token operator">>></span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>The error was a <em>SyntaxError</em>. After the fix our code was executed without a hitch. Let see more error types.</p>
<h3 id="nameerror" tabindex="-1"><a class="header-anchor" href="#nameerror" aria-hidden="true">#</a> NameError</h3>
<p><strong>Example 1: NameError</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>asabeneh@Asabeneh<span class="token punctuation">:</span><span class="token operator">~</span>$ python
Python <span class="token number">3.9</span><span class="token number">.6</span> <span class="token punctuation">(</span>default<span class="token punctuation">,</span> Jun <span class="token number">28</span> <span class="token number">2021</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">:</span><span class="token number">26</span><span class="token punctuation">:</span><span class="token number">21</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span>Clang <span class="token number">11.0</span><span class="token number">.0</span> <span class="token punctuation">(</span>clang<span class="token operator">-</span><span class="token number">1100.0</span><span class="token number">.33</span><span class="token number">.8</span><span class="token punctuation">)</span><span class="token punctuation">]</span> on darwin
Type <span class="token string">"help"</span><span class="token punctuation">,</span> <span class="token string">"copyright"</span><span class="token punctuation">,</span> <span class="token string">"credits"</span> <span class="token keyword">or</span> <span class="token string">"license"</span> <span class="token keyword">for</span> more information<span class="token punctuation">.</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token keyword">print</span><span class="token punctuation">(</span>age<span class="token punctuation">)</span>
Traceback <span class="token punctuation">(</span>most recent call last<span class="token punctuation">)</span><span class="token punctuation">:</span>
  File <span class="token string">"&lt;stdin>"</span><span class="token punctuation">,</span> line <span class="token number">1</span><span class="token punctuation">,</span> <span class="token keyword">in</span> <span class="token operator">&lt;</span>module<span class="token operator">></span>
NameError<span class="token punctuation">:</span> name <span class="token string">'age'</span> <span class="token keyword">is</span> <span class="token keyword">not</span> defined
<span class="token operator">>></span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>As you can see from the message above, name age is not defined. Yes, it is true that we did not define an age variable but we were trying to print it out as if we had had declared it. Now, lets fix this by declaring it and assigning with a value.</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>asabeneh@Asabeneh<span class="token punctuation">:</span><span class="token operator">~</span>$ python
Python <span class="token number">3.9</span><span class="token number">.6</span> <span class="token punctuation">(</span>default<span class="token punctuation">,</span> Jun <span class="token number">28</span> <span class="token number">2021</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">:</span><span class="token number">26</span><span class="token punctuation">:</span><span class="token number">21</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span>Clang <span class="token number">11.0</span><span class="token number">.0</span> <span class="token punctuation">(</span>clang<span class="token operator">-</span><span class="token number">1100.0</span><span class="token number">.33</span><span class="token number">.8</span><span class="token punctuation">)</span><span class="token punctuation">]</span> on darwin
Type <span class="token string">"help"</span><span class="token punctuation">,</span> <span class="token string">"copyright"</span><span class="token punctuation">,</span> <span class="token string">"credits"</span> <span class="token keyword">or</span> <span class="token string">"license"</span> <span class="token keyword">for</span> more information<span class="token punctuation">.</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token keyword">print</span><span class="token punctuation">(</span>age<span class="token punctuation">)</span>
Traceback <span class="token punctuation">(</span>most recent call last<span class="token punctuation">)</span><span class="token punctuation">:</span>
  File <span class="token string">"&lt;stdin>"</span><span class="token punctuation">,</span> line <span class="token number">1</span><span class="token punctuation">,</span> <span class="token keyword">in</span> <span class="token operator">&lt;</span>module<span class="token operator">></span>
NameError<span class="token punctuation">:</span> name <span class="token string">'age'</span> <span class="token keyword">is</span> <span class="token keyword">not</span> defined
<span class="token operator">>></span><span class="token operator">></span> age <span class="token operator">=</span> <span class="token number">25</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token keyword">print</span><span class="token punctuation">(</span>age<span class="token punctuation">)</span>
<span class="token number">25</span>
<span class="token operator">>></span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>The type of error was a <em>NameError</em>. We debugged the error by defining the variable name.</p>
<h3 id="indexerror" tabindex="-1"><a class="header-anchor" href="#indexerror" aria-hidden="true">#</a> IndexError</h3>
<p><strong>Example 1: IndexError</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>asabeneh@Asabeneh<span class="token punctuation">:</span><span class="token operator">~</span>$ python
Python <span class="token number">3.9</span><span class="token number">.6</span> <span class="token punctuation">(</span>default<span class="token punctuation">,</span> Jun <span class="token number">28</span> <span class="token number">2021</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">:</span><span class="token number">26</span><span class="token punctuation">:</span><span class="token number">21</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span>Clang <span class="token number">11.0</span><span class="token number">.0</span> <span class="token punctuation">(</span>clang<span class="token operator">-</span><span class="token number">1100.0</span><span class="token number">.33</span><span class="token number">.8</span><span class="token punctuation">)</span><span class="token punctuation">]</span> on darwin
Type <span class="token string">"help"</span><span class="token punctuation">,</span> <span class="token string">"copyright"</span><span class="token punctuation">,</span> <span class="token string">"credits"</span> <span class="token keyword">or</span> <span class="token string">"license"</span> <span class="token keyword">for</span> more information<span class="token punctuation">.</span>
<span class="token operator">>></span><span class="token operator">></span> numbers <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">]</span>
<span class="token operator">>></span><span class="token operator">></span> numbers<span class="token punctuation">[</span><span class="token number">5</span><span class="token punctuation">]</span>
Traceback <span class="token punctuation">(</span>most recent call last<span class="token punctuation">)</span><span class="token punctuation">:</span>
  File <span class="token string">"&lt;stdin>"</span><span class="token punctuation">,</span> line <span class="token number">1</span><span class="token punctuation">,</span> <span class="token keyword">in</span> <span class="token operator">&lt;</span>module<span class="token operator">></span>
IndexError<span class="token punctuation">:</span> <span class="token builtin">list</span> index out of <span class="token builtin">range</span>
<span class="token operator">>></span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>In the example above, Python raised an <em>IndexError</em>, because the list has only indexes from 0 to 4 , so it was out of range.</p>
<h3 id="modulenotfounderror" tabindex="-1"><a class="header-anchor" href="#modulenotfounderror" aria-hidden="true">#</a> ModuleNotFoundError</h3>
<p><strong>Example 1: ModuleNotFoundError</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>asabeneh@Asabeneh<span class="token punctuation">:</span><span class="token operator">~</span>$ python
Python <span class="token number">3.9</span><span class="token number">.6</span> <span class="token punctuation">(</span>default<span class="token punctuation">,</span> Jun <span class="token number">28</span> <span class="token number">2021</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">:</span><span class="token number">26</span><span class="token punctuation">:</span><span class="token number">21</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span>Clang <span class="token number">11.0</span><span class="token number">.0</span> <span class="token punctuation">(</span>clang<span class="token operator">-</span><span class="token number">1100.0</span><span class="token number">.33</span><span class="token number">.8</span><span class="token punctuation">)</span><span class="token punctuation">]</span> on darwin
Type <span class="token string">"help"</span><span class="token punctuation">,</span> <span class="token string">"copyright"</span><span class="token punctuation">,</span> <span class="token string">"credits"</span> <span class="token keyword">or</span> <span class="token string">"license"</span> <span class="token keyword">for</span> more information<span class="token punctuation">.</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token keyword">import</span> maths
Traceback <span class="token punctuation">(</span>most recent call last<span class="token punctuation">)</span><span class="token punctuation">:</span>
  File <span class="token string">"&lt;stdin>"</span><span class="token punctuation">,</span> line <span class="token number">1</span><span class="token punctuation">,</span> <span class="token keyword">in</span> <span class="token operator">&lt;</span>module<span class="token operator">></span>
ModuleNotFoundError<span class="token punctuation">:</span> No module named <span class="token string">'maths'</span>
<span class="token operator">>></span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>In the example above, I added an extra s to math deliberately and <em>ModuleNotFoundError</em> was raised. Lets fix it by removing the extra s from math.</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>asabeneh@Asabeneh<span class="token punctuation">:</span><span class="token operator">~</span>$ python
Python <span class="token number">3.9</span><span class="token number">.6</span> <span class="token punctuation">(</span>default<span class="token punctuation">,</span> Jun <span class="token number">28</span> <span class="token number">2021</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">:</span><span class="token number">26</span><span class="token punctuation">:</span><span class="token number">21</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span>Clang <span class="token number">11.0</span><span class="token number">.0</span> <span class="token punctuation">(</span>clang<span class="token operator">-</span><span class="token number">1100.0</span><span class="token number">.33</span><span class="token number">.8</span><span class="token punctuation">)</span><span class="token punctuation">]</span> on darwin
Type <span class="token string">"help"</span><span class="token punctuation">,</span> <span class="token string">"copyright"</span><span class="token punctuation">,</span> <span class="token string">"credits"</span> <span class="token keyword">or</span> <span class="token string">"license"</span> <span class="token keyword">for</span> more information<span class="token punctuation">.</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token keyword">import</span> maths
Traceback <span class="token punctuation">(</span>most recent call last<span class="token punctuation">)</span><span class="token punctuation">:</span>
  File <span class="token string">"&lt;stdin>"</span><span class="token punctuation">,</span> line <span class="token number">1</span><span class="token punctuation">,</span> <span class="token keyword">in</span> <span class="token operator">&lt;</span>module<span class="token operator">></span>
ModuleNotFoundError<span class="token punctuation">:</span> No module named <span class="token string">'maths'</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token keyword">import</span> math
<span class="token operator">>></span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>We fixed it, so let's use some of the functions from the math module.</p>
<h3 id="attributeerror" tabindex="-1"><a class="header-anchor" href="#attributeerror" aria-hidden="true">#</a> AttributeError</h3>
<p><strong>Example 1: AttributeError</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>asabeneh@Asabeneh<span class="token punctuation">:</span><span class="token operator">~</span>$ python
Python <span class="token number">3.9</span><span class="token number">.6</span> <span class="token punctuation">(</span>default<span class="token punctuation">,</span> Jun <span class="token number">28</span> <span class="token number">2021</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">:</span><span class="token number">26</span><span class="token punctuation">:</span><span class="token number">21</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span>Clang <span class="token number">11.0</span><span class="token number">.0</span> <span class="token punctuation">(</span>clang<span class="token operator">-</span><span class="token number">1100.0</span><span class="token number">.33</span><span class="token number">.8</span><span class="token punctuation">)</span><span class="token punctuation">]</span> on darwin
Type <span class="token string">"help"</span><span class="token punctuation">,</span> <span class="token string">"copyright"</span><span class="token punctuation">,</span> <span class="token string">"credits"</span> <span class="token keyword">or</span> <span class="token string">"license"</span> <span class="token keyword">for</span> more information<span class="token punctuation">.</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token keyword">import</span> maths
Traceback <span class="token punctuation">(</span>most recent call last<span class="token punctuation">)</span><span class="token punctuation">:</span>
  File <span class="token string">"&lt;stdin>"</span><span class="token punctuation">,</span> line <span class="token number">1</span><span class="token punctuation">,</span> <span class="token keyword">in</span> <span class="token operator">&lt;</span>module<span class="token operator">></span>
ModuleNotFoundError<span class="token punctuation">:</span> No module named <span class="token string">'maths'</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token keyword">import</span> math
<span class="token operator">>></span><span class="token operator">></span> math<span class="token punctuation">.</span>PI
Traceback <span class="token punctuation">(</span>most recent call last<span class="token punctuation">)</span><span class="token punctuation">:</span>
  File <span class="token string">"&lt;stdin>"</span><span class="token punctuation">,</span> line <span class="token number">1</span><span class="token punctuation">,</span> <span class="token keyword">in</span> <span class="token operator">&lt;</span>module<span class="token operator">></span>
AttributeError<span class="token punctuation">:</span> module <span class="token string">'math'</span> has no attribute <span class="token string">'PI'</span>
<span class="token operator">>></span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>As you can see, I made a mistake again! Instead of pi, I tried to call a PI function from maths module. It raised an attribute error, it means, that the function does not exist in the module. Lets fix it by changing from PI to pi.</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>asabeneh@Asabeneh<span class="token punctuation">:</span><span class="token operator">~</span>$ python
Python <span class="token number">3.9</span><span class="token number">.6</span> <span class="token punctuation">(</span>default<span class="token punctuation">,</span> Jun <span class="token number">28</span> <span class="token number">2021</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">:</span><span class="token number">26</span><span class="token punctuation">:</span><span class="token number">21</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span>Clang <span class="token number">11.0</span><span class="token number">.0</span> <span class="token punctuation">(</span>clang<span class="token operator">-</span><span class="token number">1100.0</span><span class="token number">.33</span><span class="token number">.8</span><span class="token punctuation">)</span><span class="token punctuation">]</span> on darwin
Type <span class="token string">"help"</span><span class="token punctuation">,</span> <span class="token string">"copyright"</span><span class="token punctuation">,</span> <span class="token string">"credits"</span> <span class="token keyword">or</span> <span class="token string">"license"</span> <span class="token keyword">for</span> more information<span class="token punctuation">.</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token keyword">import</span> maths
Traceback <span class="token punctuation">(</span>most recent call last<span class="token punctuation">)</span><span class="token punctuation">:</span>
  File <span class="token string">"&lt;stdin>"</span><span class="token punctuation">,</span> line <span class="token number">1</span><span class="token punctuation">,</span> <span class="token keyword">in</span> <span class="token operator">&lt;</span>module<span class="token operator">></span>
ModuleNotFoundError<span class="token punctuation">:</span> No module named <span class="token string">'maths'</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token keyword">import</span> math
<span class="token operator">>></span><span class="token operator">></span> math<span class="token punctuation">.</span>PI
Traceback <span class="token punctuation">(</span>most recent call last<span class="token punctuation">)</span><span class="token punctuation">:</span>
  File <span class="token string">"&lt;stdin>"</span><span class="token punctuation">,</span> line <span class="token number">1</span><span class="token punctuation">,</span> <span class="token keyword">in</span> <span class="token operator">&lt;</span>module<span class="token operator">></span>
AttributeError<span class="token punctuation">:</span> module <span class="token string">'math'</span> has no attribute <span class="token string">'PI'</span>
<span class="token operator">>></span><span class="token operator">></span> math<span class="token punctuation">.</span>pi
<span class="token number">3.141592653589793</span>
<span class="token operator">>></span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Now, when we call pi from the math module we got the result.</p>
<h3 id="keyerror" tabindex="-1"><a class="header-anchor" href="#keyerror" aria-hidden="true">#</a> KeyError</h3>
<p><strong>Example 1: KeyError</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>asabeneh@Asabeneh<span class="token punctuation">:</span><span class="token operator">~</span>$ python
Python <span class="token number">3.9</span><span class="token number">.6</span> <span class="token punctuation">(</span>default<span class="token punctuation">,</span> Jun <span class="token number">28</span> <span class="token number">2021</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">:</span><span class="token number">26</span><span class="token punctuation">:</span><span class="token number">21</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span>Clang <span class="token number">11.0</span><span class="token number">.0</span> <span class="token punctuation">(</span>clang<span class="token operator">-</span><span class="token number">1100.0</span><span class="token number">.33</span><span class="token number">.8</span><span class="token punctuation">)</span><span class="token punctuation">]</span> on darwin
Type <span class="token string">"help"</span><span class="token punctuation">,</span> <span class="token string">"copyright"</span><span class="token punctuation">,</span> <span class="token string">"credits"</span> <span class="token keyword">or</span> <span class="token string">"license"</span> <span class="token keyword">for</span> more information<span class="token punctuation">.</span>
<span class="token operator">>></span><span class="token operator">></span> users <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'name'</span><span class="token punctuation">:</span><span class="token string">'Asab'</span><span class="token punctuation">,</span> <span class="token string">'age'</span><span class="token punctuation">:</span><span class="token number">250</span><span class="token punctuation">,</span> <span class="token string">'country'</span><span class="token punctuation">:</span><span class="token string">'Finland'</span><span class="token punctuation">}</span>
<span class="token operator">>></span><span class="token operator">></span> users<span class="token punctuation">[</span><span class="token string">'name'</span><span class="token punctuation">]</span>
<span class="token string">'Asab'</span>
<span class="token operator">>></span><span class="token operator">></span> users<span class="token punctuation">[</span><span class="token string">'county'</span><span class="token punctuation">]</span>
Traceback <span class="token punctuation">(</span>most recent call last<span class="token punctuation">)</span><span class="token punctuation">:</span>
  File <span class="token string">"&lt;stdin>"</span><span class="token punctuation">,</span> line <span class="token number">1</span><span class="token punctuation">,</span> <span class="token keyword">in</span> <span class="token operator">&lt;</span>module<span class="token operator">></span>
KeyError<span class="token punctuation">:</span> <span class="token string">'county'</span>
<span class="token operator">>></span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>As you can see, there was a typo in the key used to get the dictionary value. so, this is a key error and the fix is quite straight forward. Let's do this!</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>asabeneh@Asabeneh<span class="token punctuation">:</span><span class="token operator">~</span>$ python
Python <span class="token number">3.9</span><span class="token number">.6</span> <span class="token punctuation">(</span>default<span class="token punctuation">,</span> Jun <span class="token number">28</span> <span class="token number">2021</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">:</span><span class="token number">26</span><span class="token punctuation">:</span><span class="token number">21</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span>Clang <span class="token number">11.0</span><span class="token number">.0</span> <span class="token punctuation">(</span>clang<span class="token operator">-</span><span class="token number">1100.0</span><span class="token number">.33</span><span class="token number">.8</span><span class="token punctuation">)</span><span class="token punctuation">]</span> on darwin
Type <span class="token string">"help"</span><span class="token punctuation">,</span> <span class="token string">"copyright"</span><span class="token punctuation">,</span> <span class="token string">"credits"</span> <span class="token keyword">or</span> <span class="token string">"license"</span> <span class="token keyword">for</span> more information<span class="token punctuation">.</span>
<span class="token operator">>></span><span class="token operator">></span> user <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'name'</span><span class="token punctuation">:</span><span class="token string">'Asab'</span><span class="token punctuation">,</span> <span class="token string">'age'</span><span class="token punctuation">:</span><span class="token number">250</span><span class="token punctuation">,</span> <span class="token string">'country'</span><span class="token punctuation">:</span><span class="token string">'Finland'</span><span class="token punctuation">}</span>
<span class="token operator">>></span><span class="token operator">></span> user<span class="token punctuation">[</span><span class="token string">'name'</span><span class="token punctuation">]</span>
<span class="token string">'Asab'</span>
<span class="token operator">>></span><span class="token operator">></span> user<span class="token punctuation">[</span><span class="token string">'county'</span><span class="token punctuation">]</span>
Traceback <span class="token punctuation">(</span>most recent call last<span class="token punctuation">)</span><span class="token punctuation">:</span>
  File <span class="token string">"&lt;stdin>"</span><span class="token punctuation">,</span> line <span class="token number">1</span><span class="token punctuation">,</span> <span class="token keyword">in</span> <span class="token operator">&lt;</span>module<span class="token operator">></span>
KeyError<span class="token punctuation">:</span> <span class="token string">'county'</span>
<span class="token operator">>></span><span class="token operator">></span> user<span class="token punctuation">[</span><span class="token string">'country'</span><span class="token punctuation">]</span>
<span class="token string">'Finland'</span>
<span class="token operator">>></span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>We debugged the error, our code ran and we got the value.</p>
<h3 id="typeerror" tabindex="-1"><a class="header-anchor" href="#typeerror" aria-hidden="true">#</a> TypeError</h3>
<p><strong>Example 1: TypeError</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>asabeneh@Asabeneh<span class="token punctuation">:</span><span class="token operator">~</span>$ python
Python <span class="token number">3.9</span><span class="token number">.6</span> <span class="token punctuation">(</span>default<span class="token punctuation">,</span> Jun <span class="token number">28</span> <span class="token number">2021</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">:</span><span class="token number">26</span><span class="token punctuation">:</span><span class="token number">21</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span>Clang <span class="token number">11.0</span><span class="token number">.0</span> <span class="token punctuation">(</span>clang<span class="token operator">-</span><span class="token number">1100.0</span><span class="token number">.33</span><span class="token number">.8</span><span class="token punctuation">)</span><span class="token punctuation">]</span> on darwin
Type <span class="token string">"help"</span><span class="token punctuation">,</span> <span class="token string">"copyright"</span><span class="token punctuation">,</span> <span class="token string">"credits"</span> <span class="token keyword">or</span> <span class="token string">"license"</span> <span class="token keyword">for</span> more information<span class="token punctuation">.</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token number">4</span> <span class="token operator">+</span> <span class="token string">'3'</span>
Traceback <span class="token punctuation">(</span>most recent call last<span class="token punctuation">)</span><span class="token punctuation">:</span>
  File <span class="token string">"&lt;stdin>"</span><span class="token punctuation">,</span> line <span class="token number">1</span><span class="token punctuation">,</span> <span class="token keyword">in</span> <span class="token operator">&lt;</span>module<span class="token operator">></span>
TypeError<span class="token punctuation">:</span> unsupported operand <span class="token builtin">type</span><span class="token punctuation">(</span>s<span class="token punctuation">)</span> <span class="token keyword">for</span> <span class="token operator">+</span><span class="token punctuation">:</span> <span class="token string">'int'</span> <span class="token keyword">and</span> <span class="token string">'str'</span>
<span class="token operator">>></span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>In the example above, a TypeError is raised because we cannot add a number to a string. First solution would be to convert the string to int or float. Another solution would be converting the number to a string (the result then would be '43'). Let us follow the first fix.</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>asabeneh@Asabeneh<span class="token punctuation">:</span><span class="token operator">~</span>$ python
Python <span class="token number">3.9</span><span class="token number">.6</span> <span class="token punctuation">(</span>default<span class="token punctuation">,</span> Jun <span class="token number">28</span> <span class="token number">2021</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">:</span><span class="token number">26</span><span class="token punctuation">:</span><span class="token number">21</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span>Clang <span class="token number">11.0</span><span class="token number">.0</span> <span class="token punctuation">(</span>clang<span class="token operator">-</span><span class="token number">1100.0</span><span class="token number">.33</span><span class="token number">.8</span><span class="token punctuation">)</span><span class="token punctuation">]</span> on darwin
Type <span class="token string">"help"</span><span class="token punctuation">,</span> <span class="token string">"copyright"</span><span class="token punctuation">,</span> <span class="token string">"credits"</span> <span class="token keyword">or</span> <span class="token string">"license"</span> <span class="token keyword">for</span> more information<span class="token punctuation">.</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token number">4</span> <span class="token operator">+</span> <span class="token string">'3'</span>
Traceback <span class="token punctuation">(</span>most recent call last<span class="token punctuation">)</span><span class="token punctuation">:</span>
  File <span class="token string">"&lt;stdin>"</span><span class="token punctuation">,</span> line <span class="token number">1</span><span class="token punctuation">,</span> <span class="token keyword">in</span> <span class="token operator">&lt;</span>module<span class="token operator">></span>
TypeError<span class="token punctuation">:</span> unsupported operand <span class="token builtin">type</span><span class="token punctuation">(</span>s<span class="token punctuation">)</span> <span class="token keyword">for</span> <span class="token operator">+</span><span class="token punctuation">:</span> <span class="token string">'int'</span> <span class="token keyword">and</span> <span class="token string">'str'</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token number">4</span> <span class="token operator">+</span> <span class="token builtin">int</span><span class="token punctuation">(</span><span class="token string">'3'</span><span class="token punctuation">)</span>
<span class="token number">7</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token number">4</span> <span class="token operator">+</span> <span class="token builtin">float</span><span class="token punctuation">(</span><span class="token string">'3'</span><span class="token punctuation">)</span>
<span class="token number">7.0</span>
<span class="token operator">>></span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Error removed and we got the result we expected.</p>
<h3 id="importerror" tabindex="-1"><a class="header-anchor" href="#importerror" aria-hidden="true">#</a> ImportError</h3>
<p><strong>Example 1: TypeError</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>asabeneh@Asabeneh<span class="token punctuation">:</span><span class="token operator">~</span>$ python
Python <span class="token number">3.9</span><span class="token number">.6</span> <span class="token punctuation">(</span>default<span class="token punctuation">,</span> Jun <span class="token number">28</span> <span class="token number">2021</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">:</span><span class="token number">26</span><span class="token punctuation">:</span><span class="token number">21</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span>Clang <span class="token number">11.0</span><span class="token number">.0</span> <span class="token punctuation">(</span>clang<span class="token operator">-</span><span class="token number">1100.0</span><span class="token number">.33</span><span class="token number">.8</span><span class="token punctuation">)</span><span class="token punctuation">]</span> on darwin
Type <span class="token string">"help"</span><span class="token punctuation">,</span> <span class="token string">"copyright"</span><span class="token punctuation">,</span> <span class="token string">"credits"</span> <span class="token keyword">or</span> <span class="token string">"license"</span> <span class="token keyword">for</span> more information<span class="token punctuation">.</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token keyword">from</span> math <span class="token keyword">import</span> power
Traceback <span class="token punctuation">(</span>most recent call last<span class="token punctuation">)</span><span class="token punctuation">:</span>
  File <span class="token string">"&lt;stdin>"</span><span class="token punctuation">,</span> line <span class="token number">1</span><span class="token punctuation">,</span> <span class="token keyword">in</span> <span class="token operator">&lt;</span>module<span class="token operator">></span>
ImportError<span class="token punctuation">:</span> cannot <span class="token keyword">import</span> name <span class="token string">'power'</span> <span class="token keyword">from</span> <span class="token string">'math'</span>
<span class="token operator">>></span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>There is no function called power in the math module, it goes with a different name: <em>pow</em>. Let's correct it:</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>asabeneh@Asabeneh<span class="token punctuation">:</span><span class="token operator">~</span>$ python
Python <span class="token number">3.9</span><span class="token number">.6</span> <span class="token punctuation">(</span>default<span class="token punctuation">,</span> Jun <span class="token number">28</span> <span class="token number">2021</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">:</span><span class="token number">26</span><span class="token punctuation">:</span><span class="token number">21</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span>Clang <span class="token number">11.0</span><span class="token number">.0</span> <span class="token punctuation">(</span>clang<span class="token operator">-</span><span class="token number">1100.0</span><span class="token number">.33</span><span class="token number">.8</span><span class="token punctuation">)</span><span class="token punctuation">]</span> on darwin
Type <span class="token string">"help"</span><span class="token punctuation">,</span> <span class="token string">"copyright"</span><span class="token punctuation">,</span> <span class="token string">"credits"</span> <span class="token keyword">or</span> <span class="token string">"license"</span> <span class="token keyword">for</span> more information<span class="token punctuation">.</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token keyword">from</span> math <span class="token keyword">import</span> power
Traceback <span class="token punctuation">(</span>most recent call last<span class="token punctuation">)</span><span class="token punctuation">:</span>
  File <span class="token string">"&lt;stdin>"</span><span class="token punctuation">,</span> line <span class="token number">1</span><span class="token punctuation">,</span> <span class="token keyword">in</span> <span class="token operator">&lt;</span>module<span class="token operator">></span>
ImportError<span class="token punctuation">:</span> cannot <span class="token keyword">import</span> name <span class="token string">'power'</span> <span class="token keyword">from</span> <span class="token string">'math'</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token keyword">from</span> math <span class="token keyword">import</span> <span class="token builtin">pow</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token builtin">pow</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">,</span><span class="token number">3</span><span class="token punctuation">)</span>
<span class="token number">8.0</span>
<span class="token operator">>></span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="valueerror" tabindex="-1"><a class="header-anchor" href="#valueerror" aria-hidden="true">#</a> ValueError</h3>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>asabeneh@Asabeneh<span class="token punctuation">:</span><span class="token operator">~</span>$ python
Python <span class="token number">3.9</span><span class="token number">.6</span> <span class="token punctuation">(</span>default<span class="token punctuation">,</span> Jun <span class="token number">28</span> <span class="token number">2021</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">:</span><span class="token number">26</span><span class="token punctuation">:</span><span class="token number">21</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span>Clang <span class="token number">11.0</span><span class="token number">.0</span> <span class="token punctuation">(</span>clang<span class="token operator">-</span><span class="token number">1100.0</span><span class="token number">.33</span><span class="token number">.8</span><span class="token punctuation">)</span><span class="token punctuation">]</span> on darwin
Type <span class="token string">"help"</span><span class="token punctuation">,</span> <span class="token string">"copyright"</span><span class="token punctuation">,</span> <span class="token string">"credits"</span> <span class="token keyword">or</span> <span class="token string">"license"</span> <span class="token keyword">for</span> more information<span class="token punctuation">.</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token builtin">int</span><span class="token punctuation">(</span><span class="token string">'12a'</span><span class="token punctuation">)</span>
Traceback <span class="token punctuation">(</span>most recent call last<span class="token punctuation">)</span><span class="token punctuation">:</span>
  File <span class="token string">"&lt;stdin>"</span><span class="token punctuation">,</span> line <span class="token number">1</span><span class="token punctuation">,</span> <span class="token keyword">in</span> <span class="token operator">&lt;</span>module<span class="token operator">></span>
ValueError<span class="token punctuation">:</span> invalid literal <span class="token keyword">for</span> <span class="token builtin">int</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token keyword">with</span> base <span class="token number">10</span><span class="token punctuation">:</span> <span class="token string">'12a'</span>
<span class="token operator">>></span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>In this case we cannot change the given string to a number, because of the 'a' letter in it.</p>
<h3 id="zerodivisionerror" tabindex="-1"><a class="header-anchor" href="#zerodivisionerror" aria-hidden="true">#</a> ZeroDivisionError</h3>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>asabeneh@Asabeneh<span class="token punctuation">:</span><span class="token operator">~</span>$ python
Python <span class="token number">3.9</span><span class="token number">.6</span> <span class="token punctuation">(</span>default<span class="token punctuation">,</span> Jun <span class="token number">28</span> <span class="token number">2021</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">:</span><span class="token number">26</span><span class="token punctuation">:</span><span class="token number">21</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span>Clang <span class="token number">11.0</span><span class="token number">.0</span> <span class="token punctuation">(</span>clang<span class="token operator">-</span><span class="token number">1100.0</span><span class="token number">.33</span><span class="token number">.8</span><span class="token punctuation">)</span><span class="token punctuation">]</span> on darwin
Type <span class="token string">"help"</span><span class="token punctuation">,</span> <span class="token string">"copyright"</span><span class="token punctuation">,</span> <span class="token string">"credits"</span> <span class="token keyword">or</span> <span class="token string">"license"</span> <span class="token keyword">for</span> more information<span class="token punctuation">.</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token number">1</span><span class="token operator">/</span><span class="token number">0</span>
Traceback <span class="token punctuation">(</span>most recent call last<span class="token punctuation">)</span><span class="token punctuation">:</span>
  File <span class="token string">"&lt;stdin>"</span><span class="token punctuation">,</span> line <span class="token number">1</span><span class="token punctuation">,</span> <span class="token keyword">in</span> <span class="token operator">&lt;</span>module<span class="token operator">></span>
ZeroDivisionError<span class="token punctuation">:</span> division by zero
<span class="token operator">>></span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>We cannot divide a number by zero.</p>
<p>We have covered some of the python error types, if you want to check more about it check the python documentation about python error types.
If you are good at reading the error types then you will be able to fix your bugs fast and you will also become a better programmer.</p>
<p>🌕 You are excelling. You made it to half way to your way to greatness. Now do some exercises for your brain and for your muscle.</p>
<h2 id="💻-exercises-day-15" tabindex="-1"><a class="header-anchor" href="#💻-exercises-day-15" aria-hidden="true">#</a> 💻 Exercises: Day 15</h2>
<ol>
<li>Open you python interactive shell and try all the examples covered in this section.</li>
</ol>
<p>🎉 CONGRATULATIONS ! 🎉</p>
<p><RouterLink to="/docs/14_Day_Higher_order_functions/14_higher_order_functions.html">&lt;&lt; Day 14</RouterLink> | <RouterLink to="/docs/16_Day_Python_date_time/16_python_datetime.html">Day 16 &gt;&gt;</RouterLink></p>
</div></template>


