<template><div><h1 id="_30天python编程挑战-第16天-python日期时间" tabindex="-1"><a class="header-anchor" href="#_30天python编程挑战-第16天-python日期时间" aria-hidden="true">#</a> 30天Python编程挑战：第16天 - Python日期时间</h1>
<ul>
<li><a href="#-%E7%AC%AC16%E5%A4%A9">第16天</a>
<ul>
<li><a href="#python-datetime">Python <em>datetime</em></a>
<ul>
<li><a href="#%E8%8E%B7%E5%8F%96-datetime-%E4%BF%A1%E6%81%AF">获取 <em>datetime</em> 信息</a></li>
<li><a href="#%E4%BD%BF%E7%94%A8-strftime-%E6%A0%BC%E5%BC%8F%E5%8C%96%E6%97%A5%E6%9C%9F%E8%BE%93%E5%87%BA">使用 <em>strftime</em> 格式化日期输出</a></li>
<li><a href="#%E4%BD%BF%E7%94%A8-strptime-%E5%B0%86%E5%AD%97%E7%AC%A6%E4%B8%B2%E8%BD%AC%E6%8D%A2%E4%B8%BA%E6%97%B6%E9%97%B4">使用 <em>strptime</em> 将字符串转换为时间</a></li>
<li><a href="#%E4%BB%8E-datetime-%E4%BD%BF%E7%94%A8-date">从 <em>datetime</em> 使用 <em>date</em></a></li>
<li><a href="#%E4%BD%BF%E7%94%A8time%E5%AF%B9%E8%B1%A1%E8%A1%A8%E7%A4%BA%E6%97%B6%E9%97%B4">使用Time对象表示时间</a></li>
<li><a href="#%E8%AE%A1%E7%AE%97%E4%B8%A4%E4%B8%AA%E6%97%B6%E9%97%B4%E7%82%B9%E4%B9%8B%E9%97%B4%E7%9A%84%E5%B7%AE%E5%BC%82">计算两个时间点之间的差异</a></li>
<li><a href="#%E4%BD%BF%E7%94%A8-timedelta-%E8%AE%A1%E7%AE%97%E4%B8%A4%E4%B8%AA%E6%97%B6%E9%97%B4%E7%82%B9%E4%B9%8B%E9%97%B4%E7%9A%84%E5%B7%AE%E5%BC%82">使用 <em>timedelta</em> 计算两个时间点之间的差异</a></li>
</ul>
</li>
<li><a href="#-%E7%BB%83%E4%B9%A0---%E7%AC%AC16%E5%A4%A9">💻 练习 - 第16天</a></li>
</ul>
</li>
</ul>
<h1 id="📘-第16天" tabindex="-1"><a class="header-anchor" href="#📘-第16天" aria-hidden="true">#</a> 📘 第16天</h1>
<h2 id="python-datetime" tabindex="-1"><a class="header-anchor" href="#python-datetime" aria-hidden="true">#</a> Python <em>datetime</em></h2>
<p>Python有一个 <em>datetime</em> 模块用于处理日期和时间。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">import</span> datetime
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token builtin">dir</span><span class="token punctuation">(</span>datetime<span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span><span class="token string">'MAXYEAR'</span><span class="token punctuation">,</span> <span class="token string">'MINYEAR'</span><span class="token punctuation">,</span> <span class="token string">'__builtins__'</span><span class="token punctuation">,</span> <span class="token string">'__cached__'</span><span class="token punctuation">,</span> <span class="token string">'__doc__'</span><span class="token punctuation">,</span> <span class="token string">'__file__'</span><span class="token punctuation">,</span> <span class="token string">'__loader__'</span><span class="token punctuation">,</span> <span class="token string">'__name__'</span><span class="token punctuation">,</span> <span class="token string">'__package__'</span><span class="token punctuation">,</span> <span class="token string">'__spec__'</span><span class="token punctuation">,</span> <span class="token string">'date'</span><span class="token punctuation">,</span> <span class="token string">'datetime'</span><span class="token punctuation">,</span> <span class="token string">'datetime_CAPI'</span><span class="token punctuation">,</span> <span class="token string">'sys'</span><span class="token punctuation">,</span> <span class="token string">'time'</span><span class="token punctuation">,</span> <span class="token string">'timedelta'</span><span class="token punctuation">,</span> <span class="token string">'timezone'</span><span class="token punctuation">,</span> <span class="token string">'tzinfo'</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>通过dir或help内置命令，可以了解特定模块中可用的函数。如你所见，datetime模块中有许多函数，但我们将重点关注 <em>date</em>、<em>datetime</em>、<em>time</em> 和 <em>timedelta</em>。让我们一个一个地看。</p>
<h3 id="获取-datetime-信息" tabindex="-1"><a class="header-anchor" href="#获取-datetime-信息" aria-hidden="true">#</a> 获取 <em>datetime</em> 信息</h3>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">from</span> datetime <span class="token keyword">import</span> datetime
now <span class="token operator">=</span> datetime<span class="token punctuation">.</span>now<span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>now<span class="token punctuation">)</span>                      <span class="token comment"># 2021-07-08 07:34:46.549883</span>
day <span class="token operator">=</span> now<span class="token punctuation">.</span>day                   <span class="token comment"># 8</span>
month <span class="token operator">=</span> now<span class="token punctuation">.</span>month               <span class="token comment"># 7</span>
year <span class="token operator">=</span> now<span class="token punctuation">.</span>year                 <span class="token comment"># 2021</span>
hour <span class="token operator">=</span> now<span class="token punctuation">.</span>hour                 <span class="token comment"># 7</span>
minute <span class="token operator">=</span> now<span class="token punctuation">.</span>minute             <span class="token comment"># 38</span>
second <span class="token operator">=</span> now<span class="token punctuation">.</span>second
timestamp <span class="token operator">=</span> now<span class="token punctuation">.</span>timestamp<span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>day<span class="token punctuation">,</span> month<span class="token punctuation">,</span> year<span class="token punctuation">,</span> hour<span class="token punctuation">,</span> minute<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'timestamp'</span><span class="token punctuation">,</span> timestamp<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string-interpolation"><span class="token string">f'</span><span class="token interpolation"><span class="token punctuation">{</span>day<span class="token punctuation">}</span></span><span class="token string">/</span><span class="token interpolation"><span class="token punctuation">{</span>month<span class="token punctuation">}</span></span><span class="token string">/</span><span class="token interpolation"><span class="token punctuation">{</span>year<span class="token punctuation">}</span></span><span class="token string">, </span><span class="token interpolation"><span class="token punctuation">{</span>hour<span class="token punctuation">}</span></span><span class="token string">:</span><span class="token interpolation"><span class="token punctuation">{</span>minute<span class="token punctuation">}</span></span><span class="token string">'</span></span><span class="token punctuation">)</span>  <span class="token comment"># 8/7/2021, 7:38</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>时间戳或Unix时间戳是从1970年1月1日UTC开始经过的秒数。</p>
<h3 id="使用-strftime-格式化日期输出" tabindex="-1"><a class="header-anchor" href="#使用-strftime-格式化日期输出" aria-hidden="true">#</a> 使用 <em>strftime</em> 格式化日期输出</h3>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">from</span> datetime <span class="token keyword">import</span> datetime
new_year <span class="token operator">=</span> datetime<span class="token punctuation">(</span><span class="token number">2020</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>new_year<span class="token punctuation">)</span>      <span class="token comment"># 2020-01-01 00:00:00</span>
day <span class="token operator">=</span> new_year<span class="token punctuation">.</span>day
month <span class="token operator">=</span> new_year<span class="token punctuation">.</span>month
year <span class="token operator">=</span> new_year<span class="token punctuation">.</span>year
hour <span class="token operator">=</span> new_year<span class="token punctuation">.</span>hour
minute <span class="token operator">=</span> new_year<span class="token punctuation">.</span>minute
second <span class="token operator">=</span> new_year<span class="token punctuation">.</span>second
<span class="token keyword">print</span><span class="token punctuation">(</span>day<span class="token punctuation">,</span> month<span class="token punctuation">,</span> year<span class="token punctuation">,</span> hour<span class="token punctuation">,</span> minute<span class="token punctuation">)</span> <span class="token comment">#1 1 2020 0 0</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string-interpolation"><span class="token string">f'</span><span class="token interpolation"><span class="token punctuation">{</span>day<span class="token punctuation">}</span></span><span class="token string">/</span><span class="token interpolation"><span class="token punctuation">{</span>month<span class="token punctuation">}</span></span><span class="token string">/</span><span class="token interpolation"><span class="token punctuation">{</span>year<span class="token punctuation">}</span></span><span class="token string">, </span><span class="token interpolation"><span class="token punctuation">{</span>hour<span class="token punctuation">}</span></span><span class="token string">:</span><span class="token interpolation"><span class="token punctuation">{</span>minute<span class="token punctuation">}</span></span><span class="token string">'</span></span><span class="token punctuation">)</span>  <span class="token comment"># 1/1/2020, 0:0</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>使用 <em>strftime</em> 方法格式化日期时间，相关文档可以在<a href="https://strftime.org/" target="_blank" rel="noopener noreferrer">这里<ExternalLinkIcon/></a>找到。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">from</span> datetime <span class="token keyword">import</span> datetime
<span class="token comment"># 当前日期和时间</span>
now <span class="token operator">=</span> datetime<span class="token punctuation">.</span>now<span class="token punctuation">(</span><span class="token punctuation">)</span>
t <span class="token operator">=</span> now<span class="token punctuation">.</span>strftime<span class="token punctuation">(</span><span class="token string">"%H:%M:%S"</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"时间:"</span><span class="token punctuation">,</span> t<span class="token punctuation">)</span>
time_one <span class="token operator">=</span> now<span class="token punctuation">.</span>strftime<span class="token punctuation">(</span><span class="token string">"%m/%d/%Y, %H:%M:%S"</span><span class="token punctuation">)</span>
<span class="token comment"># mm/dd/YY H:M:S 格式</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"时间一:"</span><span class="token punctuation">,</span> time_one<span class="token punctuation">)</span>
time_two <span class="token operator">=</span> now<span class="token punctuation">.</span>strftime<span class="token punctuation">(</span><span class="token string">"%d/%m/%Y, %H:%M:%S"</span><span class="token punctuation">)</span>
<span class="token comment"># dd/mm/YY H:M:S 格式</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"时间二:"</span><span class="token punctuation">,</span> time_two<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>时间: 01:05:01
时间一: <span class="token number">12</span>/05/2019, 01:05:01
时间二: 05/12/2019, 01:05:01
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>以下是我们用来格式化时间的所有 <em>strftime</em> 符号。这个模块的所有格式示例。</p>
<p><img src="@source/docs/images/strftime.png" alt="strftime"></p>
<h3 id="使用-strptime-将字符串转换为时间" tabindex="-1"><a class="header-anchor" href="#使用-strptime-将字符串转换为时间" aria-hidden="true">#</a> 使用 <em>strptime</em> 将字符串转换为时间</h3>
<p>这里有一个<a href="https://www.programiz.com/python-programming/datetime/strptimet" target="_blank" rel="noopener noreferrer">文档<ExternalLinkIcon/></a>，有助于理解格式。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">from</span> datetime <span class="token keyword">import</span> datetime
date_string <span class="token operator">=</span> <span class="token string">"5 December, 2019"</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"date_string ="</span><span class="token punctuation">,</span> date_string<span class="token punctuation">)</span>
date_object <span class="token operator">=</span> datetime<span class="token punctuation">.</span>strptime<span class="token punctuation">(</span>date_string<span class="token punctuation">,</span> <span class="token string">"%d %B, %Y"</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"date_object ="</span><span class="token punctuation">,</span> date_object<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>date_string <span class="token operator">=</span> <span class="token number">5</span> December, <span class="token number">2019</span>
date_object <span class="token operator">=</span> <span class="token number">2019</span>-12-05 00:00:00
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="从-datetime-使用-date" tabindex="-1"><a class="header-anchor" href="#从-datetime-使用-date" aria-hidden="true">#</a> 从 <em>datetime</em> 使用 <em>date</em></h3>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">from</span> datetime <span class="token keyword">import</span> date
d <span class="token operator">=</span> date<span class="token punctuation">(</span><span class="token number">2020</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>d<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'当前日期:'</span><span class="token punctuation">,</span> d<span class="token punctuation">.</span>today<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>    <span class="token comment"># 2019-12-05</span>
<span class="token comment"># 今天的日期对象</span>
today <span class="token operator">=</span> date<span class="token punctuation">.</span>today<span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"当前年份:"</span><span class="token punctuation">,</span> today<span class="token punctuation">.</span>year<span class="token punctuation">)</span>   <span class="token comment"># 2019</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"当前月份:"</span><span class="token punctuation">,</span> today<span class="token punctuation">.</span>month<span class="token punctuation">)</span> <span class="token comment"># 12</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"当前日:"</span><span class="token punctuation">,</span> today<span class="token punctuation">.</span>day<span class="token punctuation">)</span>     <span class="token comment"># 5</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="使用time对象表示时间" tabindex="-1"><a class="header-anchor" href="#使用time对象表示时间" aria-hidden="true">#</a> 使用Time对象表示时间</h3>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">from</span> datetime <span class="token keyword">import</span> time
<span class="token comment"># time(hour = 0, minute = 0, second = 0)</span>
a <span class="token operator">=</span> time<span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"a ="</span><span class="token punctuation">,</span> a<span class="token punctuation">)</span>
<span class="token comment"># time(hour, minute 和 second)</span>
b <span class="token operator">=</span> time<span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token number">50</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"b ="</span><span class="token punctuation">,</span> b<span class="token punctuation">)</span>
<span class="token comment"># time(hour, minute 和 second)</span>
c <span class="token operator">=</span> time<span class="token punctuation">(</span>hour<span class="token operator">=</span><span class="token number">10</span><span class="token punctuation">,</span> minute<span class="token operator">=</span><span class="token number">30</span><span class="token punctuation">,</span> second<span class="token operator">=</span><span class="token number">50</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"c ="</span><span class="token punctuation">,</span> c<span class="token punctuation">)</span>
<span class="token comment"># time(hour, minute, second, microsecond)</span>
d <span class="token operator">=</span> time<span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token number">50</span><span class="token punctuation">,</span> <span class="token number">200555</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"d ="</span><span class="token punctuation">,</span> d<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输出：<br>
a = 00:00:00<br>
b = 10:30:50<br>
c = 10:30:50<br>
d = 10:30:50.200555</p>
<h3 id="计算两个时间点之间的差异" tabindex="-1"><a class="header-anchor" href="#计算两个时间点之间的差异" aria-hidden="true">#</a> 计算两个时间点之间的差异</h3>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>today <span class="token operator">=</span> date<span class="token punctuation">(</span>year<span class="token operator">=</span><span class="token number">2019</span><span class="token punctuation">,</span> month<span class="token operator">=</span><span class="token number">12</span><span class="token punctuation">,</span> day<span class="token operator">=</span><span class="token number">5</span><span class="token punctuation">)</span>
new_year <span class="token operator">=</span> date<span class="token punctuation">(</span>year<span class="token operator">=</span><span class="token number">2020</span><span class="token punctuation">,</span> month<span class="token operator">=</span><span class="token number">1</span><span class="token punctuation">,</span> day<span class="token operator">=</span><span class="token number">1</span><span class="token punctuation">)</span>
time_left_for_newyear <span class="token operator">=</span> new_year <span class="token operator">-</span> today
<span class="token comment"># 距离新年的时间：  27 days, 0:00:00</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'距离新年的时间: '</span><span class="token punctuation">,</span> time_left_for_newyear<span class="token punctuation">)</span>

t1 <span class="token operator">=</span> datetime<span class="token punctuation">(</span>year <span class="token operator">=</span> <span class="token number">2019</span><span class="token punctuation">,</span> month <span class="token operator">=</span> <span class="token number">12</span><span class="token punctuation">,</span> day <span class="token operator">=</span> <span class="token number">5</span><span class="token punctuation">,</span> hour <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">,</span> minute <span class="token operator">=</span> <span class="token number">59</span><span class="token punctuation">,</span> second <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">)</span>
t2 <span class="token operator">=</span> datetime<span class="token punctuation">(</span>year <span class="token operator">=</span> <span class="token number">2020</span><span class="token punctuation">,</span> month <span class="token operator">=</span> <span class="token number">1</span><span class="token punctuation">,</span> day <span class="token operator">=</span> <span class="token number">1</span><span class="token punctuation">,</span> hour <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">,</span> minute <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">,</span> second <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">)</span>
diff <span class="token operator">=</span> t2 <span class="token operator">-</span> t1
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'距离新年的时间:'</span><span class="token punctuation">,</span> diff<span class="token punctuation">)</span> <span class="token comment"># 距离新年的时间: 26 days, 23: 01: 00</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="使用-timedelta-计算两个时间点之间的差异" tabindex="-1"><a class="header-anchor" href="#使用-timedelta-计算两个时间点之间的差异" aria-hidden="true">#</a> 使用 <em>timedelta</em> 计算两个时间点之间的差异</h3>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">from</span> datetime <span class="token keyword">import</span> timedelta
t1 <span class="token operator">=</span> timedelta<span class="token punctuation">(</span>weeks<span class="token operator">=</span><span class="token number">12</span><span class="token punctuation">,</span> days<span class="token operator">=</span><span class="token number">10</span><span class="token punctuation">,</span> hours<span class="token operator">=</span><span class="token number">4</span><span class="token punctuation">,</span> seconds<span class="token operator">=</span><span class="token number">20</span><span class="token punctuation">)</span>
t2 <span class="token operator">=</span> timedelta<span class="token punctuation">(</span>days<span class="token operator">=</span><span class="token number">7</span><span class="token punctuation">,</span> hours<span class="token operator">=</span><span class="token number">5</span><span class="token punctuation">,</span> minutes<span class="token operator">=</span><span class="token number">3</span><span class="token punctuation">,</span> seconds<span class="token operator">=</span><span class="token number">30</span><span class="token punctuation">)</span>
t3 <span class="token operator">=</span> t1 <span class="token operator">-</span> t2
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"t3 ="</span><span class="token punctuation">,</span> t3<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>date_string <span class="token operator">=</span> <span class="token number">5</span> December, <span class="token number">2019</span>
date_object <span class="token operator">=</span> <span class="token number">2019</span>-12-05 00:00:00
t3 <span class="token operator">=</span> <span class="token number">86</span> days, <span class="token number">22</span>:56:50
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>🌕 你太了不起了。你在通往卓越的道路上已经前进了16步。现在做一些练习锻炼你的大脑和肌肉。</p>
<h2 id="💻-练习-第16天" tabindex="-1"><a class="header-anchor" href="#💻-练习-第16天" aria-hidden="true">#</a> 💻 练习 - 第16天</h2>
<ol>
<li>从datetime模块获取当前的日、月、年、小时、分钟和时间戳</li>
<li>使用此格式格式化当前日期：&quot;%m/%d/%Y, %H:%M:%S&quot;</li>
<li>今天是2019年12月5日。将此时间字符串转换为时间。</li>
<li>计算现在和新年之间的时间差。</li>
<li>计算1970年1月1日和现在之间的时间差。</li>
<li>思考，你可以将datetime模块用于什么？例如：
<ul>
<li>时间序列分析</li>
<li>获取应用程序中任何活动的时间戳</li>
<li>在博客上添加帖子</li>
</ul>
</li>
</ol>
<p>🎉 恭喜！🎉</p>
<p><RouterLink to="/docs/Python/15_python_type_errors_cn.html">&lt;&lt; 第 15 天</RouterLink> | <RouterLink to="/docs/Python/17_exception_handling_cn.html">第 17 天 &gt;&gt;</RouterLink></p>
</div></template>


