<template><div><h1 id="_16-异常处理" tabindex="-1"><a class="header-anchor" href="#_16-异常处理" aria-hidden="true">#</a> 16 异常处理</h1>
<p>Python使用 <em>try</em> 和 <em>except</em> 优雅地处理错误。优雅的退出（或优雅的错误处理）是一种简单的编程习惯 - 程序检测到严重的错误条件并&quot;优雅地退出&quot;，即以受控的方式处理结果。通常，程序会在优雅退出时向终端或日志打印描述性错误消息，这使我们的应用程序更加健壮。异常的原因通常是程序本身之外的因素，例如错误的输入、错误的文件名、找不到文件、IO设备故障等。优雅的错误处理可以防止我们的应用程序崩溃。</p>
<p>我们在前一部分已经介绍了不同类型的Python <em>错误</em>。如果我们在程序中使用 <em>try</em> 和 <em>except</em>，那么这些块中就不会引发错误。</p>
<p><img src="@source/docs/pythonImages/try_except.png" alt="Try and Except"></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">try</span><span class="token punctuation">:</span>
    <span class="token comment"># 如果一切正常，执行这个块中的代码</span>
<span class="token keyword">except</span><span class="token punctuation">:</span>
    <span class="token comment"># 如果出错，执行这个块中的代码</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">try</span><span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token number">10</span> <span class="token operator">+</span> <span class="token string">'5'</span><span class="token punctuation">)</span>
<span class="token keyword">except</span><span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'出现了一些错误'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在上面的例子中，第二个操作数是一个字符串。我们可以将其更改为float或int，使其能够与数字相加。但如果不做任何更改，第二个块 <em>except</em> 将被执行。</p>
<p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">try</span><span class="token punctuation">:</span>
    name <span class="token operator">=</span> <span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">'输入你的名字:'</span><span class="token punctuation">)</span>
    year_born <span class="token operator">=</span> <span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">'你出生的年份:'</span><span class="token punctuation">)</span>
    age <span class="token operator">=</span> <span class="token number">2019</span> <span class="token operator">-</span> year_born
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string-interpolation"><span class="token string">f'你是</span><span class="token interpolation"><span class="token punctuation">{</span>name<span class="token punctuation">}</span></span><span class="token string">. 你的年龄是</span><span class="token interpolation"><span class="token punctuation">{</span>age<span class="token punctuation">}</span></span><span class="token string">.'</span></span><span class="token punctuation">)</span>
<span class="token keyword">except</span><span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'出现了一些错误'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>出现了一些错误
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>在上面的例子中，异常块将运行，但我们不知道具体的问题是什么。为了分析问题，我们可以使用不同的错误类型配合except。
在下面的例子中，它将处理错误，并且告诉我们引发了什么类型的错误。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">try</span><span class="token punctuation">:</span>
    name <span class="token operator">=</span> <span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">'输入你的名字:'</span><span class="token punctuation">)</span>
    year_born <span class="token operator">=</span> <span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">'你出生的年份:'</span><span class="token punctuation">)</span>
    age <span class="token operator">=</span> <span class="token number">2019</span> <span class="token operator">-</span> year_born
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string-interpolation"><span class="token string">f'你是</span><span class="token interpolation"><span class="token punctuation">{</span>name<span class="token punctuation">}</span></span><span class="token string">. 你的年龄是</span><span class="token interpolation"><span class="token punctuation">{</span>age<span class="token punctuation">}</span></span><span class="token string">.'</span></span><span class="token punctuation">)</span>
<span class="token keyword">except</span> TypeError<span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'发生了类型错误'</span><span class="token punctuation">)</span>
<span class="token keyword">except</span> ValueError<span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'发生了值错误'</span><span class="token punctuation">)</span>
<span class="token keyword">except</span> ZeroDivisionError<span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'发生了除零错误'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>输入你的名字:hua
你出生的年份:1999
发生了类型错误
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在上述代码中，输出将是 <em>TypeError</em>。
现在，让我们添加一个额外的块：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">try</span><span class="token punctuation">:</span>
    name <span class="token operator">=</span> <span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">'输入你的名字:'</span><span class="token punctuation">)</span>
    year_born <span class="token operator">=</span> <span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">'你出生的年份:'</span><span class="token punctuation">)</span>
    age <span class="token operator">=</span> <span class="token number">2019</span> <span class="token operator">-</span> <span class="token builtin">int</span><span class="token punctuation">(</span>year_born<span class="token punctuation">)</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string-interpolation"><span class="token string">f'你是</span><span class="token interpolation"><span class="token punctuation">{</span>name<span class="token punctuation">}</span></span><span class="token string">. 你的年龄是</span><span class="token interpolation"><span class="token punctuation">{</span>age<span class="token punctuation">}</span></span><span class="token string">.'</span></span><span class="token punctuation">)</span>
<span class="token keyword">except</span> TypeError<span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'发生了类型错误'</span><span class="token punctuation">)</span>
<span class="token keyword">except</span> ValueError<span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'发生了值错误'</span><span class="token punctuation">)</span>
<span class="token keyword">except</span> ZeroDivisionError<span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'发生了除零错误'</span><span class="token punctuation">)</span>
<span class="token keyword">else</span><span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'我通常与try块一起运行'</span><span class="token punctuation">)</span>
<span class="token keyword">finally</span><span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'我总是运行。'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>输入你的名字:hua
你出生的年份:1999
你是Asabeneh. 你的年龄是20.
我通常与try块一起运行
我总是运行。
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>也可以将上述代码简化如下：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">try</span><span class="token punctuation">:</span>
    name <span class="token operator">=</span> <span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">'输入你的名字:'</span><span class="token punctuation">)</span>
    year_born <span class="token operator">=</span> <span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">'你出生的年份:'</span><span class="token punctuation">)</span>
    age <span class="token operator">=</span> <span class="token number">2019</span> <span class="token operator">-</span> <span class="token builtin">int</span><span class="token punctuation">(</span>year_born<span class="token punctuation">)</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string-interpolation"><span class="token string">f'你是</span><span class="token interpolation"><span class="token punctuation">{</span>name<span class="token punctuation">}</span></span><span class="token string">. 你的年龄是</span><span class="token interpolation"><span class="token punctuation">{</span>age<span class="token punctuation">}</span></span><span class="token string">.'</span></span><span class="token punctuation">)</span>
<span class="token keyword">except</span> Exception <span class="token keyword">as</span> e<span class="token punctuation">:</span> <span class="token comment"># 变量 e 存储了具体的报错信息</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span>e<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="python中的打包和解包参数" tabindex="-1"><a class="header-anchor" href="#python中的打包和解包参数" aria-hidden="true">#</a> Python中的打包和解包参数</h2>
<p>我们使用两个操作符：</p>
<ul>
<li>* 用于元组</li>
<li>** 用于字典</li>
</ul>
<p>让我们看一个例子。假设函数只接受参数，但我们有一个列表。我们可以解包列表并将其转换为参数。</p>
<h3 id="解包" tabindex="-1"><a class="header-anchor" href="#解包" aria-hidden="true">#</a> 解包</h3>
<h4 id="解包列表" tabindex="-1"><a class="header-anchor" href="#解包列表" aria-hidden="true">#</a> 解包列表</h4>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">def</span> <span class="token function">sum_of_five_nums</span><span class="token punctuation">(</span>a<span class="token punctuation">,</span> b<span class="token punctuation">,</span> c<span class="token punctuation">,</span> d<span class="token punctuation">,</span> e<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">return</span> a <span class="token operator">+</span> b <span class="token operator">+</span> c <span class="token operator">+</span> d <span class="token operator">+</span> e

lst <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>sum_of_five_nums<span class="token punctuation">(</span>lst<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># TypeError: sum_of_five_nums() missing 4 required positional arguments: 'b', 'c', 'd', and 'e'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>当我们运行这段代码时，会引发错误，因为这个函数接受数字（而不是列表）作为参数。让我们解包/解构这个列表。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">def</span> <span class="token function">sum_of_five_nums</span><span class="token punctuation">(</span>a<span class="token punctuation">,</span> b<span class="token punctuation">,</span> c<span class="token punctuation">,</span> d<span class="token punctuation">,</span> e<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">return</span> a <span class="token operator">+</span> b <span class="token operator">+</span> c <span class="token operator">+</span> d <span class="token operator">+</span> e

lst <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>sum_of_five_nums<span class="token punctuation">(</span><span class="token operator">*</span>lst<span class="token punctuation">)</span><span class="token punctuation">)</span>  <span class="token comment"># 15</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们也可以在内置的range函数中使用解包，该函数需要一个起始和结束参数。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>numbers <span class="token operator">=</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">)</span>  <span class="token comment"># 正常调用，使用单独的参数</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token builtin">list</span><span class="token punctuation">(</span>numbers<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># [2, 3, 4, 5, 6]</span>
args <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">]</span>
numbers <span class="token operator">=</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token operator">*</span>args<span class="token punctuation">)</span>  <span class="token comment"># 使用从列表解包的参数调用</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>numbers<span class="token punctuation">)</span>      <span class="token comment"># [2, 3, 4, 5,6]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>列表或元组也可以这样解包：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>countries <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'China'</span><span class="token punctuation">,</span> <span class="token string">'Sweden'</span><span class="token punctuation">,</span> <span class="token string">'Norway'</span><span class="token punctuation">,</span> <span class="token string">'Denmark'</span><span class="token punctuation">,</span> <span class="token string">'Iceland'</span><span class="token punctuation">]</span>
fin<span class="token punctuation">,</span> sw<span class="token punctuation">,</span> nor<span class="token punctuation">,</span> <span class="token operator">*</span>rest <span class="token operator">=</span> countries
<span class="token keyword">print</span><span class="token punctuation">(</span>fin<span class="token punctuation">,</span> sw<span class="token punctuation">,</span> nor<span class="token punctuation">,</span> rest<span class="token punctuation">)</span>
numbers <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">]</span>
one<span class="token punctuation">,</span> <span class="token operator">*</span>middle<span class="token punctuation">,</span> last <span class="token operator">=</span> numbers
<span class="token keyword">print</span><span class="token punctuation">(</span>one<span class="token punctuation">,</span> middle<span class="token punctuation">,</span> last<span class="token punctuation">)</span>      <span class="token comment">#  1 [2, 3, 4, 5, 6] 7</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="解包字典" tabindex="-1"><a class="header-anchor" href="#解包字典" aria-hidden="true">#</a> 解包字典</h4>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">def</span> <span class="token function">unpacking_person_info</span><span class="token punctuation">(</span>name<span class="token punctuation">,</span> country<span class="token punctuation">,</span> city<span class="token punctuation">,</span> age<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">return</span> <span class="token string-interpolation"><span class="token string">f'</span><span class="token interpolation"><span class="token punctuation">{</span>name<span class="token punctuation">}</span></span><span class="token string">住在</span><span class="token interpolation"><span class="token punctuation">{</span>country<span class="token punctuation">}</span></span><span class="token string">的</span><span class="token interpolation"><span class="token punctuation">{</span>city<span class="token punctuation">}</span></span><span class="token string">。他</span><span class="token interpolation"><span class="token punctuation">{</span>age<span class="token punctuation">}</span></span><span class="token string">岁。'</span></span>
dct <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'name'</span><span class="token punctuation">:</span><span class="token string">'hua'</span><span class="token punctuation">,</span> <span class="token string">'country'</span><span class="token punctuation">:</span><span class="token string">'China'</span><span class="token punctuation">,</span> <span class="token string">'city'</span><span class="token punctuation">:</span><span class="token string">'Suzhou'</span><span class="token punctuation">,</span> <span class="token string">'age'</span><span class="token punctuation">:</span><span class="token number">13</span><span class="token operator">&lt;&lt;</span><span class="token number">1</span><span class="token punctuation">}</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>unpacking_person_info<span class="token punctuation">(</span><span class="token operator">**</span>dct<span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="打包" tabindex="-1"><a class="header-anchor" href="#打包" aria-hidden="true">#</a> 打包</h3>
<p>有时候我们不知道需要向Python函数传递多少个参数。我们可以使用打包方法让我们的函数接受无限数量或任意数量的参数。</p>
<h3 id="打包列表" tabindex="-1"><a class="header-anchor" href="#打包列表" aria-hidden="true">#</a> 打包列表</h3>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">def</span> <span class="token function">sum_all</span><span class="token punctuation">(</span><span class="token operator">*</span>args<span class="token punctuation">)</span><span class="token punctuation">:</span>
    s <span class="token operator">=</span> <span class="token number">0</span>
    <span class="token keyword">for</span> i <span class="token keyword">in</span> args<span class="token punctuation">:</span>
        s <span class="token operator">+=</span> i
    <span class="token keyword">return</span> s
<span class="token keyword">print</span><span class="token punctuation">(</span>sum_all<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">)</span><span class="token punctuation">)</span>             <span class="token comment"># 6</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>sum_all<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># 28</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="打包字典" tabindex="-1"><a class="header-anchor" href="#打包字典" aria-hidden="true">#</a> 打包字典</h4>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">def</span> <span class="token function">packing_person_info</span><span class="token punctuation">(</span><span class="token operator">**</span>kwargs<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token comment"># 检查kwargs的类型，它是一个字典类型</span>
    <span class="token comment"># print(type(kwargs))</span>
    <span class="token comment"># 打印字典项</span>
    <span class="token keyword">for</span> key <span class="token keyword">in</span> kwargs<span class="token punctuation">:</span>
        <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string-interpolation"><span class="token string">f"</span><span class="token interpolation"><span class="token punctuation">{</span>key<span class="token punctuation">}</span></span><span class="token string"> = </span><span class="token interpolation"><span class="token punctuation">{</span>kwargs<span class="token punctuation">[</span>key<span class="token punctuation">]</span><span class="token punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">)</span>
    <span class="token keyword">return</span> kwargs

<span class="token keyword">print</span><span class="token punctuation">(</span>packing_person_info<span class="token punctuation">(</span>name<span class="token operator">=</span><span class="token string">"hua"</span><span class="token punctuation">,</span>
      country<span class="token operator">=</span><span class="token string">"Chia"</span><span class="token punctuation">,</span> city<span class="token operator">=</span><span class="token string">"Suzhou"</span><span class="token punctuation">,</span> age<span class="token operator">=</span><span class="token number">13</span><span class="token operator">&lt;&lt;</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="python中的展开" tabindex="-1"><a class="header-anchor" href="#python中的展开" aria-hidden="true">#</a> Python中的展开</h2>
<p>与JavaScript类似，Python中也可以进行展开操作。让我们通过下面的例子来看看：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>lst_one <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">]</span>
lst_two <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">]</span>
lst <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token operator">*</span>lst_one<span class="token punctuation">,</span> <span class="token operator">*</span>lst_two<span class="token punctuation">]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>lst<span class="token punctuation">)</span>          <span class="token comment"># [0, 1, 2, 3, 4, 5, 6, 7]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="枚举" tabindex="-1"><a class="header-anchor" href="#枚举" aria-hidden="true">#</a> 枚举</h2>
<p>如果我们对列表的索引感兴趣，我们使用enumerate内置函数。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">for</span> index<span class="token punctuation">,</span> item <span class="token keyword">in</span> <span class="token builtin">enumerate</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">20</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token number">40</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span>index<span class="token punctuation">,</span> item<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>countries <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'China'</span><span class="token punctuation">,</span> <span class="token string">'Sweden'</span><span class="token punctuation">,</span> <span class="token string">'Norway'</span><span class="token punctuation">,</span> <span class="token string">'Denmark'</span><span class="token punctuation">,</span> <span class="token string">'Iceland'</span><span class="token punctuation">]</span>
<span class="token keyword">for</span> index<span class="token punctuation">,</span> i <span class="token keyword">in</span> <span class="token builtin">enumerate</span><span class="token punctuation">(</span>countries<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'hi'</span><span class="token punctuation">)</span>
    <span class="token keyword">if</span> i <span class="token operator">==</span> <span class="token string">'China'</span><span class="token punctuation">:</span>
        <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string-interpolation"><span class="token string">f'国家 </span><span class="token interpolation"><span class="token punctuation">{</span>i<span class="token punctuation">}</span></span><span class="token string"> 位于索引 </span><span class="token interpolation"><span class="token punctuation">{</span>index<span class="token punctuation">}</span></span><span class="token string">'</span></span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="zip" tabindex="-1"><a class="header-anchor" href="#zip" aria-hidden="true">#</a> Zip</h2>
<p>有时，我们可能需要将列表组合起来。
zip() 函数的作用就像拉链一样，把两个列表对应位置的元素一对一地捆绑在一起,看看以下示例：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>fruits <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'banana'</span><span class="token punctuation">,</span> <span class="token string">'orange'</span><span class="token punctuation">,</span> <span class="token string">'mango'</span><span class="token punctuation">,</span> <span class="token string">'lemon'</span><span class="token punctuation">,</span> <span class="token string">'lime'</span><span class="token punctuation">,</span><span class="token string">'cherry'</span><span class="token punctuation">]</span>                    
vegetables <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'Tomato'</span><span class="token punctuation">,</span> <span class="token string">'Potato'</span><span class="token punctuation">,</span> <span class="token string">'Cabbage'</span><span class="token punctuation">,</span><span class="token string">'Onion'</span><span class="token punctuation">,</span> <span class="token string">'Carrot'</span><span class="token punctuation">]</span>
fruits_and_veges <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>
<span class="token keyword">for</span> f<span class="token punctuation">,</span> v <span class="token keyword">in</span> <span class="token builtin">zip</span><span class="token punctuation">(</span>fruits<span class="token punctuation">,</span> vegetables<span class="token punctuation">)</span><span class="token punctuation">:</span>
    fruits_and_veges<span class="token punctuation">.</span>append<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">'fruit'</span><span class="token punctuation">:</span>f<span class="token punctuation">,</span> <span class="token string">'veg'</span><span class="token punctuation">:</span>v<span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>fruits_and_veges<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="custom-container tip"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"></circle><path d="M12 8h.01"></path><path d="M11 12h1v4h1"></path></g></svg><p class="custom-container-title">注意“木桶效应：</p><p>zip() 会以较短的那个列表为准。因此，'cherry' 会被自动忽略，不会出现在最终结果中。</p>
</div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token punctuation">[</span><span class="token punctuation">{</span><span class="token string">'fruit'</span><span class="token builtin class-name">:</span> <span class="token string">'banana'</span>, <span class="token string">'veg'</span><span class="token builtin class-name">:</span> <span class="token string">'Tomato'</span><span class="token punctuation">}</span>, <span class="token punctuation">{</span><span class="token string">'fruit'</span><span class="token builtin class-name">:</span> <span class="token string">'orange'</span>, <span class="token string">'veg'</span><span class="token builtin class-name">:</span> <span class="token string">'Potato'</span><span class="token punctuation">}</span>, <span class="token punctuation">{</span><span class="token string">'fruit'</span><span class="token builtin class-name">:</span> <span class="token string">'mango'</span>, <span class="token string">'veg'</span><span class="token builtin class-name">:</span> <span class="token string">'Cabbage'</span><span class="token punctuation">}</span>, <span class="token punctuation">{</span><span class="token string">'fruit'</span><span class="token builtin class-name">:</span> <span class="token string">'lemon'</span>, <span class="token string">'veg'</span><span class="token builtin class-name">:</span> <span class="token string">'Onion'</span><span class="token punctuation">}</span>, <span class="token punctuation">{</span><span class="token string">'fruit'</span><span class="token builtin class-name">:</span> <span class="token string">'lime'</span>, <span class="token string">'veg'</span><span class="token builtin class-name">:</span> <span class="token string">'Carrot'</span><span class="token punctuation">}</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="总结" tabindex="-1"><a class="header-anchor" href="#总结" aria-hidden="true">#</a> 总结</h2>
<h3 id="_1-异常处理-try-except" tabindex="-1"><a class="header-anchor" href="#_1-异常处理-try-except" aria-hidden="true">#</a> 1. 异常处理 (<code v-pre>try...except</code>)</h3>
<p>为了防止程序因为错误的输入（如字符串转数字失败）而直接崩溃，Python 提供了异常处理机制：</p>
<ul>
<li><strong><code v-pre>try</code></strong>: 放置可能出错的代码。</li>
<li><strong><code v-pre>except</code></strong>: 当错误发生时，执行这里的挽救措施。可以指定具体的错误类型（如 <code v-pre>TypeError</code>, <code v-pre>ValueError</code>）。</li>
<li><strong><code v-pre>else</code></strong>: 如果 <code v-pre>try</code> 块没有发生错误，则运行。</li>
<li><strong><code v-pre>finally</code></strong>: 无论是否出错，<strong>始终</strong>会运行的代码（常用于清理工作）。</li>
</ul>
<h3 id="_2-参数的打包与解包-与" tabindex="-1"><a class="header-anchor" href="#_2-参数的打包与解包-与" aria-hidden="true">#</a> 2. 参数的打包与解包 (<code v-pre>*</code> 与 <code v-pre>**</code>)</h3>
<p>这组操作符让函数处理数据变得极其灵活：</p>
<ul>
<li><strong>解包 (Unpacking)</strong>：
<ul>
<li><code v-pre>*list/tuple</code>：把列表/元组拆开，作为多个独立的参数传递给函数。</li>
<li><code v-pre>**dict</code>：把字典拆开，以“键=值”的形式传递给函数。</li>
</ul>
</li>
<li><strong>打包 (Packing)</strong>：
<ul>
<li><code v-pre>*args</code>：在函数定义时使用，用于接收任意数量的位置参数，存为元组。</li>
<li><code v-pre>**kwargs</code>：用于接收任意数量的关键字参数，存为字典。</li>
</ul>
</li>
<li><strong>展开 (Spreading)</strong>：可以在一个新列表中通过 <code v-pre>[*list1, *list2]</code> 的方式快速合并多个列表。</li>
</ul>
<h3 id="_3-高效迭代工具" tabindex="-1"><a class="header-anchor" href="#_3-高效迭代工具" aria-hidden="true">#</a> 3. 高效迭代工具</h3>
<p>文档介绍了两个提升循环效率的内置函数：</p>
<ul>
<li><strong><code v-pre>enumerate()</code> (枚举)</strong>：
<ul>
<li><strong>作用</strong>：在遍历列表时，同时获得元素的<strong>索引</strong>（index）和<strong>数值</strong>（item）。</li>
<li><strong>场景</strong>：当你需要知道当前处理到第几个元素时非常有用。</li>
</ul>
</li>
<li><strong><code v-pre>zip()</code> (压缩/拉链)</strong>：
<ul>
<li><strong>作用</strong>：将多个列表对应位置的元素配对，打包成一个个元组。</li>
<li><strong>注意</strong>：遵循**“木桶效应”**，结果的长度取决于最短的那个列表，多出的元素会被舍弃。</li>
</ul>
</li>
</ul>
</div></template>


