<template><div><h1 id="_30天python编程挑战-第17天-异常处理" tabindex="-1"><a class="header-anchor" href="#_30天python编程挑战-第17天-异常处理" aria-hidden="true">#</a> 30天Python编程挑战：第17天 - 异常处理</h1>
<ul>
<li><a href="#-%E7%AC%AC17%E5%A4%A9">第17天</a>
<ul>
<li><a href="#%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86">异常处理</a></li>
<li><a href="#python%E4%B8%AD%E7%9A%84%E6%89%93%E5%8C%85%E5%92%8C%E8%A7%A3%E5%8C%85%E5%8F%82%E6%95%B0">Python中的打包和解包参数</a>
<ul>
<li><a href="#%E8%A7%A3%E5%8C%85">解包</a>
<ul>
<li><a href="#%E8%A7%A3%E5%8C%85%E5%88%97%E8%A1%A8">解包列表</a></li>
<li><a href="#%E8%A7%A3%E5%8C%85%E5%AD%97%E5%85%B8">解包字典</a></li>
</ul>
</li>
<li><a href="#%E6%89%93%E5%8C%85">打包</a></li>
<li><a href="#%E6%89%93%E5%8C%85%E5%88%97%E8%A1%A8">打包列表</a>
<ul>
<li><a href="#%E6%89%93%E5%8C%85%E5%AD%97%E5%85%B8">打包字典</a></li>
</ul>
</li>
</ul>
</li>
<li><a href="#python%E4%B8%AD%E7%9A%84%E5%B1%95%E5%BC%80">Python中的展开</a></li>
<li><a href="#%E6%9E%9A%E4%B8%BE">枚举</a></li>
<li><a href="#zip">Zip</a></li>
<li><a href="#%E7%BB%83%E4%B9%A0%E7%AC%AC17%E5%A4%A9">练习：第17天</a></li>
</ul>
</li>
</ul>
<h1 id="📘-第17天" tabindex="-1"><a class="header-anchor" href="#📘-第17天" aria-hidden="true">#</a> 📘 第17天</h1>
<h2 id="异常处理" tabindex="-1"><a class="header-anchor" href="#异常处理" aria-hidden="true">#</a> 异常处理</h2>
<p>Python使用 <em>try</em> 和 <em>except</em> 优雅地处理错误。优雅的退出（或优雅的错误处理）是一种简单的编程习惯 - 程序检测到严重的错误条件并&quot;优雅地退出&quot;，即以受控的方式处理结果。通常，程序会在优雅退出时向终端或日志打印描述性错误消息，这使我们的应用程序更加健壮。异常的原因通常是程序本身之外的因素，例如错误的输入、错误的文件名、找不到文件、IO设备故障等。优雅的错误处理可以防止我们的应用程序崩溃。</p>
<p>我们在前一部分已经介绍了不同类型的Python <em>错误</em>。如果我们在程序中使用 <em>try</em> 和 <em>except</em>，那么这些块中就不会引发错误。</p>
<p><img src="@source/docs/images/try_except.png" alt="Try and Except"></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">try</span><span class="token punctuation">:</span>
    <span class="token comment"># 如果一切正常，执行这个块中的代码</span>
<span class="token keyword">except</span><span class="token punctuation">:</span>
    <span class="token comment"># 如果出错，执行这个块中的代码</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">try</span><span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token number">10</span> <span class="token operator">+</span> <span class="token string">'5'</span><span class="token punctuation">)</span>
<span class="token keyword">except</span><span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'出现了一些错误'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在上面的例子中，第二个操作数是一个字符串。我们可以将其更改为float或int，使其能够与数字相加。但如果不做任何更改，第二个块 <em>except</em> 将被执行。</p>
<p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">try</span><span class="token punctuation">:</span>
    name <span class="token operator">=</span> <span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">'输入你的名字:'</span><span class="token punctuation">)</span>
    year_born <span class="token operator">=</span> <span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">'你出生的年份:'</span><span class="token punctuation">)</span>
    age <span class="token operator">=</span> <span class="token number">2019</span> <span class="token operator">-</span> year_born
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string-interpolation"><span class="token string">f'你是</span><span class="token interpolation"><span class="token punctuation">{</span>name<span class="token punctuation">}</span></span><span class="token string">. 你的年龄是</span><span class="token interpolation"><span class="token punctuation">{</span>age<span class="token punctuation">}</span></span><span class="token string">.'</span></span><span class="token punctuation">)</span>
<span class="token keyword">except</span><span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'出现了一些错误'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>出现了一些错误
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>在上面的例子中，异常块将运行，但我们不知道具体的问题是什么。为了分析问题，我们可以使用不同的错误类型配合except。</p>
<p>在下面的例子中，它将处理错误，并且告诉我们引发了什么类型的错误。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">try</span><span class="token punctuation">:</span>
    name <span class="token operator">=</span> <span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">'输入你的名字:'</span><span class="token punctuation">)</span>
    year_born <span class="token operator">=</span> <span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">'你出生的年份:'</span><span class="token punctuation">)</span>
    age <span class="token operator">=</span> <span class="token number">2019</span> <span class="token operator">-</span> year_born
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string-interpolation"><span class="token string">f'你是</span><span class="token interpolation"><span class="token punctuation">{</span>name<span class="token punctuation">}</span></span><span class="token string">. 你的年龄是</span><span class="token interpolation"><span class="token punctuation">{</span>age<span class="token punctuation">}</span></span><span class="token string">.'</span></span><span class="token punctuation">)</span>
<span class="token keyword">except</span> TypeError<span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'发生了类型错误'</span><span class="token punctuation">)</span>
<span class="token keyword">except</span> ValueError<span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'发生了值错误'</span><span class="token punctuation">)</span>
<span class="token keyword">except</span> ZeroDivisionError<span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'发生了除零错误'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>输入你的名字:Asabeneh
你出生的年份:1920
发生了类型错误
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在上述代码中，输出将是 <em>TypeError</em>。
现在，让我们添加一个额外的块：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">try</span><span class="token punctuation">:</span>
    name <span class="token operator">=</span> <span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">'输入你的名字:'</span><span class="token punctuation">)</span>
    year_born <span class="token operator">=</span> <span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">'你出生的年份:'</span><span class="token punctuation">)</span>
    age <span class="token operator">=</span> <span class="token number">2019</span> <span class="token operator">-</span> <span class="token builtin">int</span><span class="token punctuation">(</span>year_born<span class="token punctuation">)</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string-interpolation"><span class="token string">f'你是</span><span class="token interpolation"><span class="token punctuation">{</span>name<span class="token punctuation">}</span></span><span class="token string">. 你的年龄是</span><span class="token interpolation"><span class="token punctuation">{</span>age<span class="token punctuation">}</span></span><span class="token string">.'</span></span><span class="token punctuation">)</span>
<span class="token keyword">except</span> TypeError<span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'发生了类型错误'</span><span class="token punctuation">)</span>
<span class="token keyword">except</span> ValueError<span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'发生了值错误'</span><span class="token punctuation">)</span>
<span class="token keyword">except</span> ZeroDivisionError<span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'发生了除零错误'</span><span class="token punctuation">)</span>
<span class="token keyword">else</span><span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'我通常与try块一起运行'</span><span class="token punctuation">)</span>
<span class="token keyword">finally</span><span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'我总是运行。'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>输入你的名字:Asabeneh
你出生的年份:1920
你是Asabeneh. 你的年龄是99.
我通常与try块一起运行
我总是运行。
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>也可以将上述代码简化如下：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">try</span><span class="token punctuation">:</span>
    name <span class="token operator">=</span> <span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">'输入你的名字:'</span><span class="token punctuation">)</span>
    year_born <span class="token operator">=</span> <span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">'你出生的年份:'</span><span class="token punctuation">)</span>
    age <span class="token operator">=</span> <span class="token number">2019</span> <span class="token operator">-</span> <span class="token builtin">int</span><span class="token punctuation">(</span>year_born<span class="token punctuation">)</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string-interpolation"><span class="token string">f'你是</span><span class="token interpolation"><span class="token punctuation">{</span>name<span class="token punctuation">}</span></span><span class="token string">. 你的年龄是</span><span class="token interpolation"><span class="token punctuation">{</span>age<span class="token punctuation">}</span></span><span class="token string">.'</span></span><span class="token punctuation">)</span>
<span class="token keyword">except</span> Exception <span class="token keyword">as</span> e<span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span>e<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="python中的打包和解包参数" tabindex="-1"><a class="header-anchor" href="#python中的打包和解包参数" aria-hidden="true">#</a> Python中的打包和解包参数</h2>
<p>我们使用两个操作符：</p>
<ul>
<li>* 用于元组</li>
<li>** 用于字典</li>
</ul>
<p>让我们看一个例子。假设函数只接受参数，但我们有一个列表。我们可以解包列表并将其转换为参数。</p>
<h3 id="解包" tabindex="-1"><a class="header-anchor" href="#解包" aria-hidden="true">#</a> 解包</h3>
<h4 id="解包列表" tabindex="-1"><a class="header-anchor" href="#解包列表" aria-hidden="true">#</a> 解包列表</h4>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">def</span> <span class="token function">sum_of_five_nums</span><span class="token punctuation">(</span>a<span class="token punctuation">,</span> b<span class="token punctuation">,</span> c<span class="token punctuation">,</span> d<span class="token punctuation">,</span> e<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">return</span> a <span class="token operator">+</span> b <span class="token operator">+</span> c <span class="token operator">+</span> d <span class="token operator">+</span> e

lst <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>sum_of_five_nums<span class="token punctuation">(</span>lst<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># TypeError: sum_of_five_nums() missing 4 required positional arguments: 'b', 'c', 'd', and 'e'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>当我们运行这段代码时，会引发错误，因为这个函数接受数字（而不是列表）作为参数。让我们解包/解构这个列表。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">def</span> <span class="token function">sum_of_five_nums</span><span class="token punctuation">(</span>a<span class="token punctuation">,</span> b<span class="token punctuation">,</span> c<span class="token punctuation">,</span> d<span class="token punctuation">,</span> e<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">return</span> a <span class="token operator">+</span> b <span class="token operator">+</span> c <span class="token operator">+</span> d <span class="token operator">+</span> e

lst <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>sum_of_five_nums<span class="token punctuation">(</span><span class="token operator">*</span>lst<span class="token punctuation">)</span><span class="token punctuation">)</span>  <span class="token comment"># 15</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们也可以在内置的range函数中使用解包，该函数需要一个起始和结束参数。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>numbers <span class="token operator">=</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">)</span>  <span class="token comment"># 正常调用，使用单独的参数</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token builtin">list</span><span class="token punctuation">(</span>numbers<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># [2, 3, 4, 5, 6]</span>
args <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">]</span>
numbers <span class="token operator">=</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token operator">*</span>args<span class="token punctuation">)</span>  <span class="token comment"># 使用从列表解包的参数调用</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>numbers<span class="token punctuation">)</span>      <span class="token comment"># [2, 3, 4, 5,6]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>列表或元组也可以这样解包：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>countries <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'Finland'</span><span class="token punctuation">,</span> <span class="token string">'Sweden'</span><span class="token punctuation">,</span> <span class="token string">'Norway'</span><span class="token punctuation">,</span> <span class="token string">'Denmark'</span><span class="token punctuation">,</span> <span class="token string">'Iceland'</span><span class="token punctuation">]</span>
fin<span class="token punctuation">,</span> sw<span class="token punctuation">,</span> nor<span class="token punctuation">,</span> <span class="token operator">*</span>rest <span class="token operator">=</span> countries
<span class="token keyword">print</span><span class="token punctuation">(</span>fin<span class="token punctuation">,</span> sw<span class="token punctuation">,</span> nor<span class="token punctuation">,</span> rest<span class="token punctuation">)</span>   <span class="token comment"># Finland Sweden Norway ['Denmark', 'Iceland']</span>
numbers <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">]</span>
one<span class="token punctuation">,</span> <span class="token operator">*</span>middle<span class="token punctuation">,</span> last <span class="token operator">=</span> numbers
<span class="token keyword">print</span><span class="token punctuation">(</span>one<span class="token punctuation">,</span> middle<span class="token punctuation">,</span> last<span class="token punctuation">)</span>      <span class="token comment">#  1 [2, 3, 4, 5, 6] 7</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="解包字典" tabindex="-1"><a class="header-anchor" href="#解包字典" aria-hidden="true">#</a> 解包字典</h4>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">def</span> <span class="token function">unpacking_person_info</span><span class="token punctuation">(</span>name<span class="token punctuation">,</span> country<span class="token punctuation">,</span> city<span class="token punctuation">,</span> age<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">return</span> <span class="token string-interpolation"><span class="token string">f'</span><span class="token interpolation"><span class="token punctuation">{</span>name<span class="token punctuation">}</span></span><span class="token string">住在</span><span class="token interpolation"><span class="token punctuation">{</span>country<span class="token punctuation">}</span></span><span class="token string">的</span><span class="token interpolation"><span class="token punctuation">{</span>city<span class="token punctuation">}</span></span><span class="token string">。他</span><span class="token interpolation"><span class="token punctuation">{</span>age<span class="token punctuation">}</span></span><span class="token string">岁。'</span></span>
dct <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'name'</span><span class="token punctuation">:</span><span class="token string">'Asabeneh'</span><span class="token punctuation">,</span> <span class="token string">'country'</span><span class="token punctuation">:</span><span class="token string">'Finland'</span><span class="token punctuation">,</span> <span class="token string">'city'</span><span class="token punctuation">:</span><span class="token string">'Helsinki'</span><span class="token punctuation">,</span> <span class="token string">'age'</span><span class="token punctuation">:</span><span class="token number">250</span><span class="token punctuation">}</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>unpacking_person_info<span class="token punctuation">(</span><span class="token operator">**</span>dct<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># Asabeneh住在Finland的Helsinki。他250岁。</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="打包" tabindex="-1"><a class="header-anchor" href="#打包" aria-hidden="true">#</a> 打包</h3>
<p>有时候我们不知道需要向Python函数传递多少个参数。我们可以使用打包方法让我们的函数接受无限数量或任意数量的参数。</p>
<h3 id="打包列表" tabindex="-1"><a class="header-anchor" href="#打包列表" aria-hidden="true">#</a> 打包列表</h3>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">def</span> <span class="token function">sum_all</span><span class="token punctuation">(</span><span class="token operator">*</span>args<span class="token punctuation">)</span><span class="token punctuation">:</span>
    s <span class="token operator">=</span> <span class="token number">0</span>
    <span class="token keyword">for</span> i <span class="token keyword">in</span> args<span class="token punctuation">:</span>
        s <span class="token operator">+=</span> i
    <span class="token keyword">return</span> s
<span class="token keyword">print</span><span class="token punctuation">(</span>sum_all<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">)</span><span class="token punctuation">)</span>             <span class="token comment"># 6</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>sum_all<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># 28</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="打包字典" tabindex="-1"><a class="header-anchor" href="#打包字典" aria-hidden="true">#</a> 打包字典</h4>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">def</span> <span class="token function">packing_person_info</span><span class="token punctuation">(</span><span class="token operator">**</span>kwargs<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token comment"># 检查kwargs的类型，它是一个字典类型</span>
    <span class="token comment"># print(type(kwargs))</span>
    <span class="token comment"># 打印字典项</span>
    <span class="token keyword">for</span> key <span class="token keyword">in</span> kwargs<span class="token punctuation">:</span>
        <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string-interpolation"><span class="token string">f"</span><span class="token interpolation"><span class="token punctuation">{</span>key<span class="token punctuation">}</span></span><span class="token string"> = </span><span class="token interpolation"><span class="token punctuation">{</span>kwargs<span class="token punctuation">[</span>key<span class="token punctuation">]</span><span class="token punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">)</span>
    <span class="token keyword">return</span> kwargs

<span class="token keyword">print</span><span class="token punctuation">(</span>packing_person_info<span class="token punctuation">(</span>name<span class="token operator">=</span><span class="token string">"Asabeneh"</span><span class="token punctuation">,</span>
      country<span class="token operator">=</span><span class="token string">"Finland"</span><span class="token punctuation">,</span> city<span class="token operator">=</span><span class="token string">"Helsinki"</span><span class="token punctuation">,</span> age<span class="token operator">=</span><span class="token number">250</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>name <span class="token operator">=</span> Asabeneh
country <span class="token operator">=</span> Finland
city <span class="token operator">=</span> Helsinki
age <span class="token operator">=</span> <span class="token number">250</span>
<span class="token punctuation">{</span><span class="token string">'name'</span><span class="token builtin class-name">:</span> <span class="token string">'Asabeneh'</span>, <span class="token string">'country'</span><span class="token builtin class-name">:</span> <span class="token string">'Finland'</span>, <span class="token string">'city'</span><span class="token builtin class-name">:</span> <span class="token string">'Helsinki'</span>, <span class="token string">'age'</span><span class="token builtin class-name">:</span> <span class="token number">250</span><span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="python中的展开" tabindex="-1"><a class="header-anchor" href="#python中的展开" aria-hidden="true">#</a> Python中的展开</h2>
<p>与JavaScript类似，Python中也可以进行展开操作。让我们通过下面的例子来看看：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>lst_one <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">]</span>
lst_two <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">4</span><span class="token punctuation">,</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token number">6</span><span class="token punctuation">,</span> <span class="token number">7</span><span class="token punctuation">]</span>
lst <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token operator">*</span>lst_one<span class="token punctuation">,</span> <span class="token operator">*</span>lst_two<span class="token punctuation">]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>lst<span class="token punctuation">)</span>          <span class="token comment"># [0, 1, 2, 3, 4, 5, 6, 7]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="枚举" tabindex="-1"><a class="header-anchor" href="#枚举" aria-hidden="true">#</a> 枚举</h2>
<p>如果我们对列表的索引感兴趣，我们使用enumerate内置函数。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">for</span> index<span class="token punctuation">,</span> item <span class="token keyword">in</span> <span class="token builtin">enumerate</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">20</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token number">40</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span>index<span class="token punctuation">,</span> item<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">for</span> index<span class="token punctuation">,</span> i <span class="token keyword">in</span> <span class="token builtin">enumerate</span><span class="token punctuation">(</span>countries<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'hi'</span><span class="token punctuation">)</span>
    <span class="token keyword">if</span> i <span class="token operator">==</span> <span class="token string">'Finland'</span><span class="token punctuation">:</span>
        <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'国家 {i} 位于索引 {index}'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token number">0</span> <span class="token number">20</span>
<span class="token number">1</span> <span class="token number">30</span>
<span class="token number">2</span> <span class="token number">40</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="zip" tabindex="-1"><a class="header-anchor" href="#zip" aria-hidden="true">#</a> Zip</h2>
<p>有时，我们可能需要将列表组合起来。看看以下示例：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>fruits <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'banana'</span><span class="token punctuation">,</span> <span class="token string">'orange'</span><span class="token punctuation">,</span> <span class="token string">'mango'</span><span class="token punctuation">,</span> <span class="token string">'lemon'</span><span class="token punctuation">,</span> <span class="token string">'lime'</span><span class="token punctuation">]</span>                    
vegetables <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'Tomato'</span><span class="token punctuation">,</span> <span class="token string">'Potato'</span><span class="token punctuation">,</span> <span class="token string">'Cabbage'</span><span class="token punctuation">,</span><span class="token string">'Onion'</span><span class="token punctuation">,</span> <span class="token string">'Carrot'</span><span class="token punctuation">]</span>
fruits_and_veges <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>
<span class="token keyword">for</span> f<span class="token punctuation">,</span> v <span class="token keyword">in</span> <span class="token builtin">zip</span><span class="token punctuation">(</span>fruits<span class="token punctuation">,</span> vegetables<span class="token punctuation">)</span><span class="token punctuation">:</span>
    fruits_and_veges<span class="token punctuation">.</span>append<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">'fruit'</span><span class="token punctuation">:</span>f<span class="token punctuation">,</span> <span class="token string">'veg'</span><span class="token punctuation">:</span>v<span class="token punctuation">}</span><span class="token punctuation">)</span>

<span class="token keyword">print</span><span class="token punctuation">(</span>fruits_and_veges<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token punctuation">[</span><span class="token punctuation">{</span><span class="token string">'fruit'</span><span class="token builtin class-name">:</span> <span class="token string">'banana'</span>, <span class="token string">'veg'</span><span class="token builtin class-name">:</span> <span class="token string">'Tomato'</span><span class="token punctuation">}</span>, <span class="token punctuation">{</span><span class="token string">'fruit'</span><span class="token builtin class-name">:</span> <span class="token string">'orange'</span>, <span class="token string">'veg'</span><span class="token builtin class-name">:</span> <span class="token string">'Potato'</span><span class="token punctuation">}</span>, <span class="token punctuation">{</span><span class="token string">'fruit'</span><span class="token builtin class-name">:</span> <span class="token string">'mango'</span>, <span class="token string">'veg'</span><span class="token builtin class-name">:</span> <span class="token string">'Cabbage'</span><span class="token punctuation">}</span>, <span class="token punctuation">{</span><span class="token string">'fruit'</span><span class="token builtin class-name">:</span> <span class="token string">'lemon'</span>, <span class="token string">'veg'</span><span class="token builtin class-name">:</span> <span class="token string">'Onion'</span><span class="token punctuation">}</span>, <span class="token punctuation">{</span><span class="token string">'fruit'</span><span class="token builtin class-name">:</span> <span class="token string">'lime'</span>, <span class="token string">'veg'</span><span class="token builtin class-name">:</span> <span class="token string">'Carrot'</span><span class="token punctuation">}</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="练习-第17天" tabindex="-1"><a class="header-anchor" href="#练习-第17天" aria-hidden="true">#</a> 练习：第17天</h2>
<ol>
<li>为名为 <em>countries_data.py</em> 的文件中的数据创建一个名为 <em>countries.py</em> 的函数。
<ul>
<li>创建一个函数，找出十大使用的语言</li>
<li>创建一个函数，找出十大人口最多的国家</li>
</ul>
</li>
</ol>
<p>🎉 恭喜！🎉</p>
<p><RouterLink to="/docs/Python/16_python_datetime_cn.html">&lt;&lt; 第 16 天</RouterLink> | <RouterLink to="/docs/Python/18_regular_expressions_cn.html">第 18 天 &gt;&gt;</RouterLink></p>
</div></template>


