<template><div><h1 id="_20-类和对象" tabindex="-1"><a class="header-anchor" href="#_20-类和对象" aria-hidden="true">#</a> 20 类和对象</h1>
<p>Python是一种面向对象的编程语言。在Python中，一切都是对象，都有其属性和方法。在程序中使用的数字、字符串、列表、字典、元组、集合等都是相应内置类的对象。我们创建类来创建对象。类就像一个对象构造器，或者说是创建对象的&quot;蓝图&quot;。我们实例化一个类来创建一个对象。类定义了对象的属性和行为，而对象则代表了类。
让我们检查一下Python中的一切是否都是类：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>asabeneh@Asabeneh<span class="token punctuation">:</span><span class="token operator">~</span>$ python
Python <span class="token number">3.9</span><span class="token number">.6</span> <span class="token punctuation">(</span>default<span class="token punctuation">,</span> Jun <span class="token number">28</span> <span class="token number">2021</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">:</span><span class="token number">26</span><span class="token punctuation">:</span><span class="token number">21</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span>Clang <span class="token number">11.0</span><span class="token number">.0</span> <span class="token punctuation">(</span>clang<span class="token operator">-</span><span class="token number">1100.0</span><span class="token number">.33</span><span class="token number">.8</span><span class="token punctuation">)</span><span class="token punctuation">]</span> on darwin
Type <span class="token string">"help"</span><span class="token punctuation">,</span> <span class="token string">"copyright"</span><span class="token punctuation">,</span> <span class="token string">"credits"</span> <span class="token keyword">or</span> <span class="token string">"license"</span> <span class="token keyword">for</span> more information<span class="token punctuation">.</span>
<span class="token operator">>></span><span class="token operator">></span> num <span class="token operator">=</span> <span class="token number">10</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token builtin">type</span><span class="token punctuation">(</span>num<span class="token punctuation">)</span>
<span class="token operator">&lt;</span><span class="token keyword">class</span> <span class="token string">'int'</span><span class="token operator">></span>
<span class="token operator">>></span><span class="token operator">></span> string <span class="token operator">=</span> <span class="token string">'string'</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token builtin">type</span><span class="token punctuation">(</span>string<span class="token punctuation">)</span>
<span class="token operator">&lt;</span><span class="token keyword">class</span> <span class="token string">'str'</span><span class="token operator">></span>
<span class="token operator">>></span><span class="token operator">></span> boolean <span class="token operator">=</span> <span class="token boolean">True</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token builtin">type</span><span class="token punctuation">(</span>boolean<span class="token punctuation">)</span>
<span class="token operator">&lt;</span><span class="token keyword">class</span> <span class="token string">'bool'</span><span class="token operator">></span>
<span class="token operator">>></span><span class="token operator">></span> lst <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token builtin">type</span><span class="token punctuation">(</span>lst<span class="token punctuation">)</span>
<span class="token operator">&lt;</span><span class="token keyword">class</span> <span class="token string">'list'</span><span class="token operator">></span>
<span class="token operator">>></span><span class="token operator">></span> tpl <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token builtin">type</span><span class="token punctuation">(</span>tpl<span class="token punctuation">)</span>
<span class="token operator">&lt;</span><span class="token keyword">class</span> <span class="token string">'tuple'</span><span class="token operator">></span>
<span class="token operator">>></span><span class="token operator">></span> set1 <span class="token operator">=</span> <span class="token builtin">set</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token builtin">type</span><span class="token punctuation">(</span>set1<span class="token punctuation">)</span>
<span class="token operator">&lt;</span><span class="token keyword">class</span> <span class="token string">'set'</span><span class="token operator">></span>
<span class="token operator">>></span><span class="token operator">></span> dct <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token builtin">type</span><span class="token punctuation">(</span>dct<span class="token punctuation">)</span>
<span class="token operator">&lt;</span><span class="token keyword">class</span> <span class="token string">'dict'</span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="创建类" tabindex="-1"><a class="header-anchor" href="#创建类" aria-hidden="true">#</a> 创建类</h3>
<p>要创建一个类，我们需要关键字<strong>class</strong>，后跟类名和冒号。类名应该使用<strong>驼峰命名法（CamelCase）</strong>。</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token comment"># 语法</span>
class 类名:
  代码放在这里
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">class</span> <span class="token class-name">Person</span><span class="token punctuation">:</span>
  <span class="token keyword">pass</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>Person<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token operator">&lt;</span>__main__.Person object at 0x10804e51<span class="token operator"><span class="token file-descriptor important">0</span>></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="创建对象" tabindex="-1"><a class="header-anchor" href="#创建对象" aria-hidden="true">#</a> 创建对象</h3>
<p>我们可以通过调用类来创建对象。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>p <span class="token operator">=</span> Person<span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="类构造函数" tabindex="-1"><a class="header-anchor" href="#类构造函数" aria-hidden="true">#</a> 类构造函数</h3>
<p>在上面的例子中，我们已经从Person类创建了一个对象。然而，没有构造函数的类在实际应用中并不真正有用。让我们使用构造函数使我们的类更有用。与Java或JavaScript中的构造函数一样，Python也有一个内置的**<strong>init</strong><strong>()构造函数。</strong><strong>init</strong>**构造函数有一个self参数，它是当前类实例的引用。
<strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">class</span> <span class="token class-name">Person</span><span class="token punctuation">:</span>
      <span class="token keyword">def</span> <span class="token function">__init__</span> <span class="token punctuation">(</span>self<span class="token punctuation">,</span> name<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token comment"># self允许将参数附加到类</span>
          self<span class="token punctuation">.</span>name <span class="token operator">=</span> name

p <span class="token operator">=</span> Person<span class="token punctuation">(</span><span class="token string">'hua'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p<span class="token punctuation">.</span>name<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token comment"># 输出</span>
hua
<span class="token operator">&lt;</span>__main__.Person object at 0x2abf46907e8<span class="token operator"><span class="token file-descriptor important">0</span>></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>让我们向构造函数添加更多参数。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">class</span> <span class="token class-name">Person</span><span class="token punctuation">:</span>
    <span class="token keyword">def</span> <span class="token function">__init__</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span> firstname<span class="token punctuation">,</span> lastname<span class="token punctuation">,</span> age<span class="token punctuation">,</span> country<span class="token punctuation">,</span> city<span class="token punctuation">)</span><span class="token punctuation">:</span>
        self<span class="token punctuation">.</span>firstname <span class="token operator">=</span> firstname
        self<span class="token punctuation">.</span>lastname <span class="token operator">=</span> lastname
        self<span class="token punctuation">.</span>age <span class="token operator">=</span> age
        self<span class="token punctuation">.</span>country <span class="token operator">=</span> country
        self<span class="token punctuation">.</span>city <span class="token operator">=</span> city
p <span class="token operator">=</span> Person<span class="token punctuation">(</span><span class="token string">'hua'</span><span class="token punctuation">,</span> <span class="token string">'joffery'</span><span class="token punctuation">,</span> <span class="token number">13</span><span class="token operator">&lt;&lt;</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token string">'China'</span><span class="token punctuation">,</span> <span class="token string">'Suzhou'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p<span class="token punctuation">.</span>firstname<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p<span class="token punctuation">.</span>lastname<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p<span class="token punctuation">.</span>age<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p<span class="token punctuation">.</span>country<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p<span class="token punctuation">.</span>city<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token comment"># 输出</span>
hua
joffery
<span class="token number">26</span>
China
Suzhou
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="对象方法" tabindex="-1"><a class="header-anchor" href="#对象方法" aria-hidden="true">#</a> 对象方法</h3>
<p>对象可以有方法。方法是属于对象的函数。
<strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">class</span> <span class="token class-name">Person</span><span class="token punctuation">:</span>
      <span class="token keyword">def</span> <span class="token function">__init__</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span> firstname<span class="token punctuation">,</span> lastname<span class="token punctuation">,</span> age<span class="token punctuation">,</span> country<span class="token punctuation">,</span> city<span class="token punctuation">)</span><span class="token punctuation">:</span>
          self<span class="token punctuation">.</span>firstname <span class="token operator">=</span> firstname
          self<span class="token punctuation">.</span>lastname <span class="token operator">=</span> lastname
          self<span class="token punctuation">.</span>age <span class="token operator">=</span> age
          self<span class="token punctuation">.</span>country <span class="token operator">=</span> country
          self<span class="token punctuation">.</span>city <span class="token operator">=</span> city
      <span class="token keyword">def</span> <span class="token function">person_info</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token keyword">return</span> <span class="token string-interpolation"><span class="token string">f'</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>firstname<span class="token punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>lastname<span class="token punctuation">}</span></span><span class="token string">今年</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>age<span class="token punctuation">}</span></span><span class="token string">岁。他住在</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>country<span class="token punctuation">}</span></span><span class="token string">的</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>city<span class="token punctuation">}</span></span><span class="token string">。'</span></span>

p <span class="token operator">=</span> Person<span class="token punctuation">(</span><span class="token string">'hua'</span><span class="token punctuation">,</span> <span class="token string">'joffery'</span><span class="token punctuation">,</span> <span class="token number">13</span><span class="token operator">&lt;&lt;</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token string">'China'</span><span class="token punctuation">,</span> <span class="token string">'Suzhou'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p<span class="token punctuation">.</span>person_info<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token comment"># 输出</span>
hua joffery今年26岁。他住在China的Suzhou。
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="对象默认方法" tabindex="-1"><a class="header-anchor" href="#对象默认方法" aria-hidden="true">#</a> 对象默认方法</h3>
<p>有时，你可能希望为对象方法提供默认值。如果我们为构造函数中的参数提供默认值，可以避免在不带参数调用或实例化类时出现错误。让我们看看这是什么样子：
<strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">class</span> <span class="token class-name">Person</span><span class="token punctuation">:</span>
      <span class="token keyword">def</span> <span class="token function">__init__</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span> firstname<span class="token operator">=</span><span class="token string">'hua'</span><span class="token punctuation">,</span> lastname<span class="token operator">=</span><span class="token string">'joffery'</span><span class="token punctuation">,</span> age<span class="token operator">=</span><span class="token number">13</span><span class="token operator">&lt;&lt;</span><span class="token number">1</span><span class="token punctuation">,</span> country<span class="token operator">=</span><span class="token string">'China'</span><span class="token punctuation">,</span> city<span class="token operator">=</span><span class="token string">'Suzhou'</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
          self<span class="token punctuation">.</span>firstname <span class="token operator">=</span> firstname
          self<span class="token punctuation">.</span>lastname <span class="token operator">=</span> lastname
          self<span class="token punctuation">.</span>age <span class="token operator">=</span> age
          self<span class="token punctuation">.</span>country <span class="token operator">=</span> country
          self<span class="token punctuation">.</span>city <span class="token operator">=</span> city

      <span class="token keyword">def</span> <span class="token function">person_info</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token keyword">return</span> <span class="token string-interpolation"><span class="token string">f'</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>firstname<span class="token punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>lastname<span class="token punctuation">}</span></span><span class="token string">今年</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>age<span class="token punctuation">}</span></span><span class="token string">岁。他住在</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>country<span class="token punctuation">}</span></span><span class="token string">的</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>city<span class="token punctuation">}</span></span><span class="token string">。'</span></span>

p1 <span class="token operator">=</span> Person<span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p1<span class="token punctuation">.</span>person_info<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
p2 <span class="token operator">=</span> Person<span class="token punctuation">(</span><span class="token string">'wang'</span><span class="token punctuation">,</span> <span class="token string">'five'</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token string">'China'</span><span class="token punctuation">,</span> <span class="token string">'Shanghai'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p2<span class="token punctuation">.</span>person_info<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token comment"># 输出</span>
hua joffery今年26岁。他住在China的Suzhou。
wang five今年30岁。他住在China的Shanghai。
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="修改类默认值的方法" tabindex="-1"><a class="header-anchor" href="#修改类默认值的方法" aria-hidden="true">#</a> 修改类默认值的方法</h3>
<p>在下面的例子中，person类的所有构造函数参数都有默认值。此外，我们还有一个skills参数，可以通过方法访问。让我们创建一个add_skill方法，向skills列表添加技能。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">class</span> <span class="token class-name">Person</span><span class="token punctuation">:</span>
      <span class="token keyword">def</span> <span class="token function">__init__</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span> firstname<span class="token operator">=</span><span class="token string">'hua'</span><span class="token punctuation">,</span> lastname<span class="token operator">=</span><span class="token string">'joffery'</span><span class="token punctuation">,</span> age<span class="token operator">=</span><span class="token number">13</span><span class="token operator">&lt;&lt;</span><span class="token number">1</span><span class="token punctuation">,</span> country<span class="token operator">=</span><span class="token string">'China'</span><span class="token punctuation">,</span> city<span class="token operator">=</span><span class="token string">'Suzhhou'</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
          self<span class="token punctuation">.</span>firstname <span class="token operator">=</span> firstname
          self<span class="token punctuation">.</span>lastname <span class="token operator">=</span> lastname
          self<span class="token punctuation">.</span>age <span class="token operator">=</span> age
          self<span class="token punctuation">.</span>country <span class="token operator">=</span> country
          self<span class="token punctuation">.</span>city <span class="token operator">=</span> city
          self<span class="token punctuation">.</span>skills <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>

      <span class="token keyword">def</span> <span class="token function">person_info</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token keyword">return</span> <span class="token string-interpolation"><span class="token string">f'</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>firstname<span class="token punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>lastname<span class="token punctuation">}</span></span><span class="token string">今年</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>age<span class="token punctuation">}</span></span><span class="token string">岁。他住在</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>country<span class="token punctuation">}</span></span><span class="token string">的</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>city<span class="token punctuation">}</span></span><span class="token string">。'</span></span>
      <span class="token keyword">def</span> <span class="token function">add_skill</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span> skill<span class="token punctuation">)</span><span class="token punctuation">:</span>
          self<span class="token punctuation">.</span>skills<span class="token punctuation">.</span>append<span class="token punctuation">(</span>skill<span class="token punctuation">)</span>

p1 <span class="token operator">=</span> Person<span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p1<span class="token punctuation">.</span>person_info<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
p1<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'HTML'</span><span class="token punctuation">)</span>
p1<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'CSS'</span><span class="token punctuation">)</span>
p1<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'JavaScript'</span><span class="token punctuation">)</span>
p2 <span class="token operator">=</span> Person<span class="token punctuation">(</span><span class="token string">'wang'</span><span class="token punctuation">,</span> <span class="token string">'five'</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token string">'China'</span><span class="token punctuation">,</span> <span class="token string">'Shanghai'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p2<span class="token punctuation">.</span>person_info<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p1<span class="token punctuation">.</span>skills<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p2<span class="token punctuation">.</span>skills<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token comment"># 输出</span>
hua joffery今年26岁。他住在China的Suzhhou。
wang five今年30岁。他住在China的Shanghai。
<span class="token punctuation">[</span><span class="token string">'HTML'</span>, <span class="token string">'CSS'</span>, <span class="token string">'JavaScript'</span><span class="token punctuation">]</span>
<span class="token punctuation">[</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="继承" tabindex="-1"><a class="header-anchor" href="#继承" aria-hidden="true">#</a> 继承</h3>
<p>继承允许我们定义一个继承父类所有功能的类。它使代码可重用。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
<span class="token keyword">class</span> 子类名<span class="token punctuation">(</span>父类名<span class="token punctuation">)</span><span class="token punctuation">:</span>
    代码放在这里
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>让我们通过实际例子来看看继承的含义：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">class</span> <span class="token class-name">Student</span><span class="token punctuation">(</span>Person<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">pass</span>


s1 <span class="token operator">=</span> Student<span class="token punctuation">(</span><span class="token string">'zhang'</span><span class="token punctuation">,</span> <span class="token string">'three'</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token string">'China'</span><span class="token punctuation">,</span> <span class="token string">'Beijing'</span><span class="token punctuation">)</span>
s2 <span class="token operator">=</span> Student<span class="token punctuation">(</span><span class="token string">'li'</span><span class="token punctuation">,</span> <span class="token string">'four'</span><span class="token punctuation">,</span> <span class="token number">28</span><span class="token punctuation">,</span> <span class="token string">'China'</span><span class="token punctuation">,</span> <span class="token string">'Shenzheng'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>s1<span class="token punctuation">.</span>person_info<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
s1<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'JavaScript'</span><span class="token punctuation">)</span>
s1<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'React'</span><span class="token punctuation">)</span>
s1<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'Python'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>s1<span class="token punctuation">.</span>skills<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>s2<span class="token punctuation">.</span>person_info<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
s2<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'Organizing'</span><span class="token punctuation">)</span>
s2<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'Marketing'</span><span class="token punctuation">)</span>
s2<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'Digital Marketing'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>s2<span class="token punctuation">.</span>skills<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token comment"># 输出</span>
zhang three今年30岁。他住在China的Beijing。
<span class="token punctuation">[</span><span class="token string">'JavaScript'</span>, <span class="token string">'React'</span>, <span class="token string">'Python'</span><span class="token punctuation">]</span>
li four今年28岁。他住在China的Shenzheng。
<span class="token punctuation">[</span><span class="token string">'Organizing'</span>, <span class="token string">'Marketing'</span>, <span class="token string">'Digital Marketing'</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们没有在Student类中调用任何方法，但我们能够访问来自Parent类的所有方法。Student类继承了Person类的__init__构造函数和person_info方法。如果我们想要向子类添加一个特定于子类的新方法，我们必须编写子类并在子类中创建新的方法。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">class</span> <span class="token class-name">Student</span><span class="token punctuation">(</span>Person<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">def</span> <span class="token function">__init__</span> <span class="token punctuation">(</span>self<span class="token punctuation">,</span> firstname<span class="token operator">=</span><span class="token string">'hua'</span><span class="token punctuation">,</span> lastname<span class="token operator">=</span><span class="token string">'joffery'</span><span class="token punctuation">,</span>age<span class="token operator">=</span><span class="token number">13</span><span class="token operator">&lt;&lt;</span><span class="token number">1</span><span class="token punctuation">,</span> country<span class="token operator">=</span><span class="token string">'China'</span><span class="token punctuation">,</span> city<span class="token operator">=</span><span class="token string">'Suzhou'</span><span class="token punctuation">,</span> gender<span class="token operator">=</span><span class="token string">'male'</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
        self<span class="token punctuation">.</span>gender <span class="token operator">=</span> gender
        <span class="token builtin">super</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>__init__<span class="token punctuation">(</span>firstname<span class="token punctuation">,</span> lastname<span class="token punctuation">,</span>age<span class="token punctuation">,</span> country<span class="token punctuation">,</span> city<span class="token punctuation">)</span>
    <span class="token keyword">def</span> <span class="token function">person_info</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        gender <span class="token operator">=</span> <span class="token string">'他'</span> <span class="token keyword">if</span> self<span class="token punctuation">.</span>gender <span class="token operator">==</span><span class="token string">'male'</span> <span class="token keyword">else</span> <span class="token string">'她'</span>
        <span class="token keyword">return</span> <span class="token string-interpolation"><span class="token string">f'</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>firstname<span class="token punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>lastname<span class="token punctuation">}</span></span><span class="token string">今年</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>age<span class="token punctuation">}</span></span><span class="token string">岁。</span><span class="token interpolation"><span class="token punctuation">{</span>gender<span class="token punctuation">}</span></span><span class="token string">住在</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>country<span class="token punctuation">}</span></span><span class="token string">的</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>city<span class="token punctuation">}</span></span><span class="token string">。'</span></span>

s1 <span class="token operator">=</span> Student<span class="token punctuation">(</span><span class="token string">'zhang'</span><span class="token punctuation">,</span> <span class="token string">'three'</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token string">'China'</span><span class="token punctuation">,</span> <span class="token string">'Beijing'</span><span class="token punctuation">,</span><span class="token string">'male'</span><span class="token punctuation">)</span>
s2 <span class="token operator">=</span> Student<span class="token punctuation">(</span><span class="token string">'li'</span><span class="token punctuation">,</span> <span class="token string">'four'</span><span class="token punctuation">,</span> <span class="token number">28</span><span class="token punctuation">,</span> <span class="token string">'China'</span><span class="token punctuation">,</span> <span class="token string">'Shenzheng'</span><span class="token punctuation">,</span><span class="token string">'female'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>s1<span class="token punctuation">.</span>person_info<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
s1<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'JavaScript'</span><span class="token punctuation">)</span>
s1<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'React'</span><span class="token punctuation">)</span>
s1<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'Python'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>s1<span class="token punctuation">.</span>skills<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>s2<span class="token punctuation">.</span>person_info<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
s2<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'Organizing'</span><span class="token punctuation">)</span>
s2<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'Marketing'</span><span class="token punctuation">)</span>
s2<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'Digital Marketing'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>s2<span class="token punctuation">.</span>skills<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token comment"># 输出</span>
zhang three今年30岁。他住在China的Beijing。
<span class="token punctuation">[</span><span class="token string">'JavaScript'</span>, <span class="token string">'React'</span>, <span class="token string">'Python'</span><span class="token punctuation">]</span>
li four今年28岁。她住在China的Shenzheng。
<span class="token punctuation">[</span><span class="token string">'Organizing'</span>, <span class="token string">'Marketing'</span>, <span class="token string">'Digital Marketing'</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们可以使用super()函数或父类名Person来自动继承父类的方法和属性。在上面的例子中，我们覆盖了父类方法。子类的person_info方法有不同的实现，即使方法名称与父类相同。</p>
<h3 id="覆盖父类方法" tabindex="-1"><a class="header-anchor" href="#覆盖父类方法" aria-hidden="true">#</a> 覆盖父类方法</h3>
<p>如上所示，我们可以通过创建与父类方法名称相同的子类方法来覆盖父类方法。</p>
</div></template>


