<template><div><h1 id="_30天python编程挑战-第21天-类和对象" tabindex="-1"><a class="header-anchor" href="#_30天python编程挑战-第21天-类和对象" aria-hidden="true">#</a> 30天Python编程挑战：第21天 - 类和对象</h1>
<ul>
<li><a href="#-%E7%AC%AC21%E5%A4%A9">第21天</a>
<ul>
<li><a href="#%E7%B1%BB%E5%92%8C%E5%AF%B9%E8%B1%A1">类和对象</a>
<ul>
<li><a href="#%E5%88%9B%E5%BB%BA%E7%B1%BB">创建类</a></li>
<li><a href="#%E5%88%9B%E5%BB%BA%E5%AF%B9%E8%B1%A1">创建对象</a></li>
<li><a href="#%E7%B1%BB%E6%9E%84%E9%80%A0%E5%87%BD%E6%95%B0">类构造函数</a></li>
<li><a href="#%E5%AF%B9%E8%B1%A1%E6%96%B9%E6%B3%95">对象方法</a></li>
<li><a href="#%E5%AF%B9%E8%B1%A1%E9%BB%98%E8%AE%A4%E6%96%B9%E6%B3%95">对象默认方法</a></li>
<li><a href="#%E4%BF%AE%E6%94%B9%E7%B1%BB%E9%BB%98%E8%AE%A4%E5%80%BC%E7%9A%84%E6%96%B9%E6%B3%95">修改类默认值的方法</a></li>
<li><a href="#%E7%BB%A7%E6%89%BF">继承</a></li>
<li><a href="#%E8%A6%86%E7%9B%96%E7%88%B6%E7%B1%BB%E6%96%B9%E6%B3%95">覆盖父类方法</a></li>
</ul>
</li>
<li><a href="#-%E7%BB%83%E4%B9%A0%E7%AC%AC21%E5%A4%A9">💻 练习：第21天</a>
<ul>
<li><a href="#%E7%BB%83%E4%B9%A0%E7%BA%A7%E5%88%AB1">练习：级别1</a></li>
<li><a href="#%E7%BB%83%E4%B9%A0%E7%BA%A7%E5%88%AB2">练习：级别2</a></li>
<li><a href="#%E7%BB%83%E4%B9%A0%E7%BA%A7%E5%88%AB3">练习：级别3</a></li>
</ul>
</li>
</ul>
</li>
</ul>
<h1 id="📘-第21天" tabindex="-1"><a class="header-anchor" href="#📘-第21天" aria-hidden="true">#</a> 📘 第21天</h1>
<h2 id="类和对象" tabindex="-1"><a class="header-anchor" href="#类和对象" aria-hidden="true">#</a> 类和对象</h2>
<p>Python是一种面向对象的编程语言。在Python中，一切都是对象，都有其属性和方法。在程序中使用的数字、字符串、列表、字典、元组、集合等都是相应内置类的对象。我们创建类来创建对象。类就像一个对象构造器，或者说是创建对象的&quot;蓝图&quot;。我们实例化一个类来创建一个对象。类定义了对象的属性和行为，而对象则代表了类。</p>
<p>从这个挑战的开始，我们就一直在不知不觉地使用类和对象。Python程序中的每个元素都是某个类的对象。
让我们检查一下Python中的一切是否都是类：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>asabeneh@Asabeneh<span class="token punctuation">:</span><span class="token operator">~</span>$ python
Python <span class="token number">3.9</span><span class="token number">.6</span> <span class="token punctuation">(</span>default<span class="token punctuation">,</span> Jun <span class="token number">28</span> <span class="token number">2021</span><span class="token punctuation">,</span> <span class="token number">15</span><span class="token punctuation">:</span><span class="token number">26</span><span class="token punctuation">:</span><span class="token number">21</span><span class="token punctuation">)</span>
<span class="token punctuation">[</span>Clang <span class="token number">11.0</span><span class="token number">.0</span> <span class="token punctuation">(</span>clang<span class="token operator">-</span><span class="token number">1100.0</span><span class="token number">.33</span><span class="token number">.8</span><span class="token punctuation">)</span><span class="token punctuation">]</span> on darwin
Type <span class="token string">"help"</span><span class="token punctuation">,</span> <span class="token string">"copyright"</span><span class="token punctuation">,</span> <span class="token string">"credits"</span> <span class="token keyword">or</span> <span class="token string">"license"</span> <span class="token keyword">for</span> more information<span class="token punctuation">.</span>
<span class="token operator">>></span><span class="token operator">></span> num <span class="token operator">=</span> <span class="token number">10</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token builtin">type</span><span class="token punctuation">(</span>num<span class="token punctuation">)</span>
<span class="token operator">&lt;</span><span class="token keyword">class</span> <span class="token string">'int'</span><span class="token operator">></span>
<span class="token operator">>></span><span class="token operator">></span> string <span class="token operator">=</span> <span class="token string">'string'</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token builtin">type</span><span class="token punctuation">(</span>string<span class="token punctuation">)</span>
<span class="token operator">&lt;</span><span class="token keyword">class</span> <span class="token string">'str'</span><span class="token operator">></span>
<span class="token operator">>></span><span class="token operator">></span> boolean <span class="token operator">=</span> <span class="token boolean">True</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token builtin">type</span><span class="token punctuation">(</span>boolean<span class="token punctuation">)</span>
<span class="token operator">&lt;</span><span class="token keyword">class</span> <span class="token string">'bool'</span><span class="token operator">></span>
<span class="token operator">>></span><span class="token operator">></span> lst <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token builtin">type</span><span class="token punctuation">(</span>lst<span class="token punctuation">)</span>
<span class="token operator">&lt;</span><span class="token keyword">class</span> <span class="token string">'list'</span><span class="token operator">></span>
<span class="token operator">>></span><span class="token operator">></span> tpl <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token builtin">type</span><span class="token punctuation">(</span>tpl<span class="token punctuation">)</span>
<span class="token operator">&lt;</span><span class="token keyword">class</span> <span class="token string">'tuple'</span><span class="token operator">></span>
<span class="token operator">>></span><span class="token operator">></span> set1 <span class="token operator">=</span> <span class="token builtin">set</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token builtin">type</span><span class="token punctuation">(</span>set1<span class="token punctuation">)</span>
<span class="token operator">&lt;</span><span class="token keyword">class</span> <span class="token string">'set'</span><span class="token operator">></span>
<span class="token operator">>></span><span class="token operator">></span> dct <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token builtin">type</span><span class="token punctuation">(</span>dct<span class="token punctuation">)</span>
<span class="token operator">&lt;</span><span class="token keyword">class</span> <span class="token string">'dict'</span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="创建类" tabindex="-1"><a class="header-anchor" href="#创建类" aria-hidden="true">#</a> 创建类</h3>
<p>要创建一个类，我们需要关键字<strong>class</strong>，后跟类名和冒号。类名应该使用<strong>驼峰命名法（CamelCase）</strong>。</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token comment"># 语法</span>
class 类名:
  代码放在这里
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">class</span> <span class="token class-name">Person</span><span class="token punctuation">:</span>
  <span class="token keyword">pass</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>Person<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token operator">&lt;</span>__main__.Person object at 0x10804e51<span class="token operator"><span class="token file-descriptor important">0</span>></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="创建对象" tabindex="-1"><a class="header-anchor" href="#创建对象" aria-hidden="true">#</a> 创建对象</h3>
<p>我们可以通过调用类来创建对象。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>p <span class="token operator">=</span> Person<span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="类构造函数" tabindex="-1"><a class="header-anchor" href="#类构造函数" aria-hidden="true">#</a> 类构造函数</h3>
<p>在上面的例子中，我们已经从Person类创建了一个对象。然而，没有构造函数的类在实际应用中并不真正有用。让我们使用构造函数使我们的类更有用。与Java或JavaScript中的构造函数一样，Python也有一个内置的**<strong>init</strong><strong>()构造函数。</strong><strong>init</strong>**构造函数有一个self参数，它是当前类实例的引用。
<strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">class</span> <span class="token class-name">Person</span><span class="token punctuation">:</span>
      <span class="token keyword">def</span> <span class="token function">__init__</span> <span class="token punctuation">(</span>self<span class="token punctuation">,</span> name<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token comment"># self允许将参数附加到类</span>
          self<span class="token punctuation">.</span>name <span class="token operator">=</span> name

p <span class="token operator">=</span> Person<span class="token punctuation">(</span><span class="token string">'Asabeneh'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p<span class="token punctuation">.</span>name<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token comment"># 输出</span>
Asabeneh
<span class="token operator">&lt;</span>__main__.Person object at 0x2abf46907e8<span class="token operator"><span class="token file-descriptor important">0</span>></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>让我们向构造函数添加更多参数。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">class</span> <span class="token class-name">Person</span><span class="token punctuation">:</span>
      <span class="token keyword">def</span> <span class="token function">__init__</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span> firstname<span class="token punctuation">,</span> lastname<span class="token punctuation">,</span> age<span class="token punctuation">,</span> country<span class="token punctuation">,</span> city<span class="token punctuation">)</span><span class="token punctuation">:</span>
          self<span class="token punctuation">.</span>firstname <span class="token operator">=</span> firstname
          self<span class="token punctuation">.</span>lastname <span class="token operator">=</span> lastname
          self<span class="token punctuation">.</span>age <span class="token operator">=</span> age
          self<span class="token punctuation">.</span>country <span class="token operator">=</span> country
          self<span class="token punctuation">.</span>city <span class="token operator">=</span> city


p <span class="token operator">=</span> Person<span class="token punctuation">(</span><span class="token string">'Asabeneh'</span><span class="token punctuation">,</span> <span class="token string">'Yetayeh'</span><span class="token punctuation">,</span> <span class="token number">250</span><span class="token punctuation">,</span> <span class="token string">'Finland'</span><span class="token punctuation">,</span> <span class="token string">'Helsinki'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p<span class="token punctuation">.</span>firstname<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p<span class="token punctuation">.</span>lastname<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p<span class="token punctuation">.</span>age<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p<span class="token punctuation">.</span>country<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p<span class="token punctuation">.</span>city<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token comment"># 输出</span>
Asabeneh
Yetayeh
<span class="token number">250</span>
Finland
Helsinki
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="对象方法" tabindex="-1"><a class="header-anchor" href="#对象方法" aria-hidden="true">#</a> 对象方法</h3>
<p>对象可以有方法。方法是属于对象的函数。</p>
<p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">class</span> <span class="token class-name">Person</span><span class="token punctuation">:</span>
      <span class="token keyword">def</span> <span class="token function">__init__</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span> firstname<span class="token punctuation">,</span> lastname<span class="token punctuation">,</span> age<span class="token punctuation">,</span> country<span class="token punctuation">,</span> city<span class="token punctuation">)</span><span class="token punctuation">:</span>
          self<span class="token punctuation">.</span>firstname <span class="token operator">=</span> firstname
          self<span class="token punctuation">.</span>lastname <span class="token operator">=</span> lastname
          self<span class="token punctuation">.</span>age <span class="token operator">=</span> age
          self<span class="token punctuation">.</span>country <span class="token operator">=</span> country
          self<span class="token punctuation">.</span>city <span class="token operator">=</span> city
      <span class="token keyword">def</span> <span class="token function">person_info</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token keyword">return</span> <span class="token string-interpolation"><span class="token string">f'</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>firstname<span class="token punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>lastname<span class="token punctuation">}</span></span><span class="token string">今年</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>age<span class="token punctuation">}</span></span><span class="token string">岁。他住在</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>country<span class="token punctuation">}</span></span><span class="token string">的</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>city<span class="token punctuation">}</span></span><span class="token string">。'</span></span>

p <span class="token operator">=</span> Person<span class="token punctuation">(</span><span class="token string">'Asabeneh'</span><span class="token punctuation">,</span> <span class="token string">'Yetayeh'</span><span class="token punctuation">,</span> <span class="token number">250</span><span class="token punctuation">,</span> <span class="token string">'Finland'</span><span class="token punctuation">,</span> <span class="token string">'Helsinki'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p<span class="token punctuation">.</span>person_info<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token comment"># 输出</span>
Asabeneh Yetayeh今年250岁。他住在Finland的Helsinki。
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="对象默认方法" tabindex="-1"><a class="header-anchor" href="#对象默认方法" aria-hidden="true">#</a> 对象默认方法</h3>
<p>有时，你可能希望为对象方法提供默认值。如果我们为构造函数中的参数提供默认值，可以避免在不带参数调用或实例化类时出现错误。让我们看看这是什么样子：</p>
<p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">class</span> <span class="token class-name">Person</span><span class="token punctuation">:</span>
      <span class="token keyword">def</span> <span class="token function">__init__</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span> firstname<span class="token operator">=</span><span class="token string">'Asabeneh'</span><span class="token punctuation">,</span> lastname<span class="token operator">=</span><span class="token string">'Yetayeh'</span><span class="token punctuation">,</span> age<span class="token operator">=</span><span class="token number">250</span><span class="token punctuation">,</span> country<span class="token operator">=</span><span class="token string">'Finland'</span><span class="token punctuation">,</span> city<span class="token operator">=</span><span class="token string">'Helsinki'</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
          self<span class="token punctuation">.</span>firstname <span class="token operator">=</span> firstname
          self<span class="token punctuation">.</span>lastname <span class="token operator">=</span> lastname
          self<span class="token punctuation">.</span>age <span class="token operator">=</span> age
          self<span class="token punctuation">.</span>country <span class="token operator">=</span> country
          self<span class="token punctuation">.</span>city <span class="token operator">=</span> city

      <span class="token keyword">def</span> <span class="token function">person_info</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token keyword">return</span> <span class="token string-interpolation"><span class="token string">f'</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>firstname<span class="token punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>lastname<span class="token punctuation">}</span></span><span class="token string">今年</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>age<span class="token punctuation">}</span></span><span class="token string">岁。他住在</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>country<span class="token punctuation">}</span></span><span class="token string">的</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>city<span class="token punctuation">}</span></span><span class="token string">。'</span></span>

p1 <span class="token operator">=</span> Person<span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p1<span class="token punctuation">.</span>person_info<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
p2 <span class="token operator">=</span> Person<span class="token punctuation">(</span><span class="token string">'John'</span><span class="token punctuation">,</span> <span class="token string">'Doe'</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token string">'Nomanland'</span><span class="token punctuation">,</span> <span class="token string">'Noman city'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p2<span class="token punctuation">.</span>person_info<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token comment"># 输出</span>
Asabeneh Yetayeh今年250岁。他住在Finland的Helsinki。
John Doe今年30岁。他住在Nomanland的Noman city。
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="修改类默认值的方法" tabindex="-1"><a class="header-anchor" href="#修改类默认值的方法" aria-hidden="true">#</a> 修改类默认值的方法</h3>
<p>在下面的例子中，person类的所有构造函数参数都有默认值。此外，我们还有一个skills参数，可以通过方法访问。让我们创建一个add_skill方法，向skills列表添加技能。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">class</span> <span class="token class-name">Person</span><span class="token punctuation">:</span>
      <span class="token keyword">def</span> <span class="token function">__init__</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span> firstname<span class="token operator">=</span><span class="token string">'Asabeneh'</span><span class="token punctuation">,</span> lastname<span class="token operator">=</span><span class="token string">'Yetayeh'</span><span class="token punctuation">,</span> age<span class="token operator">=</span><span class="token number">250</span><span class="token punctuation">,</span> country<span class="token operator">=</span><span class="token string">'Finland'</span><span class="token punctuation">,</span> city<span class="token operator">=</span><span class="token string">'Helsinki'</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
          self<span class="token punctuation">.</span>firstname <span class="token operator">=</span> firstname
          self<span class="token punctuation">.</span>lastname <span class="token operator">=</span> lastname
          self<span class="token punctuation">.</span>age <span class="token operator">=</span> age
          self<span class="token punctuation">.</span>country <span class="token operator">=</span> country
          self<span class="token punctuation">.</span>city <span class="token operator">=</span> city
          self<span class="token punctuation">.</span>skills <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>

      <span class="token keyword">def</span> <span class="token function">person_info</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token keyword">return</span> <span class="token string-interpolation"><span class="token string">f'</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>firstname<span class="token punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>lastname<span class="token punctuation">}</span></span><span class="token string">今年</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>age<span class="token punctuation">}</span></span><span class="token string">岁。他住在</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>country<span class="token punctuation">}</span></span><span class="token string">的</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>city<span class="token punctuation">}</span></span><span class="token string">。'</span></span>
      <span class="token keyword">def</span> <span class="token function">add_skill</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span> skill<span class="token punctuation">)</span><span class="token punctuation">:</span>
          self<span class="token punctuation">.</span>skills<span class="token punctuation">.</span>append<span class="token punctuation">(</span>skill<span class="token punctuation">)</span>

p1 <span class="token operator">=</span> Person<span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p1<span class="token punctuation">.</span>person_info<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
p1<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'HTML'</span><span class="token punctuation">)</span>
p1<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'CSS'</span><span class="token punctuation">)</span>
p1<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'JavaScript'</span><span class="token punctuation">)</span>
p2 <span class="token operator">=</span> Person<span class="token punctuation">(</span><span class="token string">'John'</span><span class="token punctuation">,</span> <span class="token string">'Doe'</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token string">'Nomanland'</span><span class="token punctuation">,</span> <span class="token string">'Noman city'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p2<span class="token punctuation">.</span>person_info<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p1<span class="token punctuation">.</span>skills<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p2<span class="token punctuation">.</span>skills<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token comment"># 输出</span>
Asabeneh Yetayeh今年250岁。他住在Finland的Helsinki。
John Doe今年30岁。他住在Nomanland的Noman city。
<span class="token punctuation">[</span><span class="token string">'HTML'</span>, <span class="token string">'CSS'</span>, <span class="token string">'JavaScript'</span><span class="token punctuation">]</span>
<span class="token punctuation">[</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="继承" tabindex="-1"><a class="header-anchor" href="#继承" aria-hidden="true">#</a> 继承</h3>
<p>继承允许我们定义一个继承父类所有功能的类。它使代码可重用。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
<span class="token keyword">class</span> 子类名<span class="token punctuation">(</span>父类名<span class="token punctuation">)</span><span class="token punctuation">:</span>
    代码放在这里
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>让我们通过实际例子来看看继承的含义：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">class</span> <span class="token class-name">Student</span><span class="token punctuation">(</span>Person<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">pass</span>


s1 <span class="token operator">=</span> Student<span class="token punctuation">(</span><span class="token string">'Eyob'</span><span class="token punctuation">,</span> <span class="token string">'Yetayeh'</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token string">'Finland'</span><span class="token punctuation">,</span> <span class="token string">'Helsinki'</span><span class="token punctuation">)</span>
s2 <span class="token operator">=</span> Student<span class="token punctuation">(</span><span class="token string">'Lidiya'</span><span class="token punctuation">,</span> <span class="token string">'Teklemariam'</span><span class="token punctuation">,</span> <span class="token number">28</span><span class="token punctuation">,</span> <span class="token string">'Finland'</span><span class="token punctuation">,</span> <span class="token string">'Espoo'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>s1<span class="token punctuation">.</span>person_info<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
s1<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'JavaScript'</span><span class="token punctuation">)</span>
s1<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'React'</span><span class="token punctuation">)</span>
s1<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'Python'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>s1<span class="token punctuation">.</span>skills<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>s2<span class="token punctuation">.</span>person_info<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
s2<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'Organizing'</span><span class="token punctuation">)</span>
s2<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'Marketing'</span><span class="token punctuation">)</span>
s2<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'Digital Marketing'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>s2<span class="token punctuation">.</span>skills<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token comment"># 输出</span>
Eyob Yetayeh今年30岁。他住在Finland的Helsinki。
<span class="token punctuation">[</span><span class="token string">'JavaScript'</span>, <span class="token string">'React'</span>, <span class="token string">'Python'</span><span class="token punctuation">]</span>
Lidiya Teklemariam今年28岁。他住在Finland的Espoo。
<span class="token punctuation">[</span><span class="token string">'Organizing'</span>, <span class="token string">'Marketing'</span>, <span class="token string">'Digital Marketing'</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们没有在Student类中调用任何方法，但我们能够访问来自Parent类的所有方法。Student类继承了Person类的__init__构造函数和person_info方法。如果我们想要向子类添加一个特定于子类的新方法，我们必须编写子类并在子类中创建新的方法。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">class</span> <span class="token class-name">Student</span><span class="token punctuation">(</span>Person<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">def</span> <span class="token function">__init__</span> <span class="token punctuation">(</span>self<span class="token punctuation">,</span> firstname<span class="token operator">=</span><span class="token string">'Asabeneh'</span><span class="token punctuation">,</span> lastname<span class="token operator">=</span><span class="token string">'Yetayeh'</span><span class="token punctuation">,</span>age<span class="token operator">=</span><span class="token number">250</span><span class="token punctuation">,</span> country<span class="token operator">=</span><span class="token string">'Finland'</span><span class="token punctuation">,</span> city<span class="token operator">=</span><span class="token string">'Helsinki'</span><span class="token punctuation">,</span> gender<span class="token operator">=</span><span class="token string">'male'</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
        self<span class="token punctuation">.</span>gender <span class="token operator">=</span> gender
        <span class="token builtin">super</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>__init__<span class="token punctuation">(</span>firstname<span class="token punctuation">,</span> lastname<span class="token punctuation">,</span>age<span class="token punctuation">,</span> country<span class="token punctuation">,</span> city<span class="token punctuation">)</span>
    <span class="token keyword">def</span> <span class="token function">person_info</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        gender <span class="token operator">=</span> <span class="token string">'他'</span> <span class="token keyword">if</span> self<span class="token punctuation">.</span>gender <span class="token operator">==</span><span class="token string">'male'</span> <span class="token keyword">else</span> <span class="token string">'她'</span>
        <span class="token keyword">return</span> <span class="token string-interpolation"><span class="token string">f'</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>firstname<span class="token punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>lastname<span class="token punctuation">}</span></span><span class="token string">今年</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>age<span class="token punctuation">}</span></span><span class="token string">岁。</span><span class="token interpolation"><span class="token punctuation">{</span>gender<span class="token punctuation">}</span></span><span class="token string">住在</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>country<span class="token punctuation">}</span></span><span class="token string">的</span><span class="token interpolation"><span class="token punctuation">{</span>self<span class="token punctuation">.</span>city<span class="token punctuation">}</span></span><span class="token string">。'</span></span>


s1 <span class="token operator">=</span> Student<span class="token punctuation">(</span><span class="token string">'Eyob'</span><span class="token punctuation">,</span> <span class="token string">'Yetayeh'</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">,</span> <span class="token string">'Finland'</span><span class="token punctuation">,</span> <span class="token string">'Helsinki'</span><span class="token punctuation">,</span><span class="token string">'male'</span><span class="token punctuation">)</span>
s2 <span class="token operator">=</span> Student<span class="token punctuation">(</span><span class="token string">'Lidiya'</span><span class="token punctuation">,</span> <span class="token string">'Teklemariam'</span><span class="token punctuation">,</span> <span class="token number">28</span><span class="token punctuation">,</span> <span class="token string">'Finland'</span><span class="token punctuation">,</span> <span class="token string">'Espoo'</span><span class="token punctuation">,</span> <span class="token string">'female'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>s1<span class="token punctuation">.</span>person_info<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
s1<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'JavaScript'</span><span class="token punctuation">)</span>
s1<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'React'</span><span class="token punctuation">)</span>
s1<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'Python'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>s1<span class="token punctuation">.</span>skills<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>s2<span class="token punctuation">.</span>person_info<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
s2<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'Organizing'</span><span class="token punctuation">)</span>
s2<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'Marketing'</span><span class="token punctuation">)</span>
s2<span class="token punctuation">.</span>add_skill<span class="token punctuation">(</span><span class="token string">'Digital Marketing'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>s2<span class="token punctuation">.</span>skills<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token comment"># 输出</span>
Eyob Yetayeh今年30岁。他住在Finland的Helsinki。
<span class="token punctuation">[</span><span class="token string">'JavaScript'</span>, <span class="token string">'React'</span>, <span class="token string">'Python'</span><span class="token punctuation">]</span>
Lidiya Teklemariam今年28岁。她住在Finland的Espoo。
<span class="token punctuation">[</span><span class="token string">'Organizing'</span>, <span class="token string">'Marketing'</span>, <span class="token string">'Digital Marketing'</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们可以使用super()函数或父类名Person来自动继承父类的方法和属性。在上面的例子中，我们覆盖了父类方法。子类的person_info方法有不同的实现，即使方法名称与父类相同。</p>
<h3 id="覆盖父类方法" tabindex="-1"><a class="header-anchor" href="#覆盖父类方法" aria-hidden="true">#</a> 覆盖父类方法</h3>
<p>如上所示，我们可以通过创建与父类方法名称相同的子类方法来覆盖父类方法。</p>
<h2 id="💻-练习-第21天" tabindex="-1"><a class="header-anchor" href="#💻-练习-第21天" aria-hidden="true">#</a> 💻 练习：第21天</h2>
<h3 id="练习-级别1" tabindex="-1"><a class="header-anchor" href="#练习-级别1" aria-hidden="true">#</a> 练习：级别1</h3>
<ol>
<li>Python有一个名为_statistics_的模块，我们可以使用这个模块来计算统计数据。但是，让我们尝试开发一个可以计算均值、中位数、众数、标准差等统计数据的类。</li>
</ol>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">class</span> <span class="token class-name">Statistics</span><span class="token punctuation">:</span>
    <span class="token keyword">def</span> <span class="token function">__init__</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span> data<span class="token operator">=</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
        self<span class="token punctuation">.</span>data <span class="token operator">=</span> data

    <span class="token keyword">def</span> <span class="token function">count</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token comment"># 你自己的实现</span>
        <span class="token keyword">pass</span>
    
    <span class="token keyword">def</span> <span class="token function">sum</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token comment"># 你自己的实现</span>
        <span class="token keyword">pass</span>
    
    <span class="token keyword">def</span> <span class="token function">min</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token comment"># 你自己的实现</span>
        <span class="token keyword">pass</span>
    
    <span class="token keyword">def</span> <span class="token function">max</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token comment"># 你自己的实现</span>
        <span class="token keyword">pass</span>
    
    <span class="token keyword">def</span> <span class="token function">range</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token comment"># 你自己的实现</span>
        <span class="token keyword">pass</span>
    
    <span class="token keyword">def</span> <span class="token function">mean</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token comment"># 你自己的实现</span>
        <span class="token keyword">pass</span>
    
    <span class="token keyword">def</span> <span class="token function">median</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token comment"># 你自己的实现</span>
        <span class="token keyword">pass</span>
    
    <span class="token keyword">def</span> <span class="token function">mode</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token comment"># 你自己的实现</span>
        <span class="token keyword">pass</span>
    
    <span class="token keyword">def</span> <span class="token function">standard_deviation</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token comment"># 你自己的实现</span>
        <span class="token keyword">pass</span>
    
    <span class="token keyword">def</span> <span class="token function">variance</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token comment"># 你自己的实现</span>
        <span class="token keyword">pass</span>
    
    <span class="token keyword">def</span> <span class="token function">frequency_distribution</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token comment"># 你自己的实现</span>
        <span class="token keyword">pass</span>
    
    <span class="token keyword">def</span> <span class="token function">describe</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">:</span>
        <span class="token comment"># 你自己的实现</span>
        <span class="token keyword">pass</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 测试代码</span>
data <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">31</span><span class="token punctuation">,</span> <span class="token number">26</span><span class="token punctuation">,</span> <span class="token number">34</span><span class="token punctuation">,</span> <span class="token number">37</span><span class="token punctuation">,</span> <span class="token number">27</span><span class="token punctuation">,</span> <span class="token number">26</span><span class="token punctuation">,</span> <span class="token number">32</span><span class="token punctuation">,</span> <span class="token number">32</span><span class="token punctuation">,</span> <span class="token number">26</span><span class="token punctuation">,</span> <span class="token number">27</span><span class="token punctuation">,</span> <span class="token number">27</span><span class="token punctuation">,</span> <span class="token number">24</span><span class="token punctuation">,</span> <span class="token number">32</span><span class="token punctuation">,</span> <span class="token number">33</span><span class="token punctuation">,</span> <span class="token number">27</span><span class="token punctuation">,</span> <span class="token number">25</span><span class="token punctuation">,</span> <span class="token number">26</span><span class="token punctuation">,</span> <span class="token number">38</span><span class="token punctuation">,</span> <span class="token number">37</span><span class="token punctuation">,</span> <span class="token number">31</span><span class="token punctuation">,</span> <span class="token number">34</span><span class="token punctuation">,</span> <span class="token number">24</span><span class="token punctuation">,</span> <span class="token number">33</span><span class="token punctuation">,</span> <span class="token number">29</span><span class="token punctuation">,</span> <span class="token number">26</span><span class="token punctuation">]</span>
statistics <span class="token operator">=</span> Statistics<span class="token punctuation">(</span>data<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'Count:'</span><span class="token punctuation">,</span> statistics<span class="token punctuation">.</span>count<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># 25</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'Sum: '</span><span class="token punctuation">,</span> statistics<span class="token punctuation">.</span><span class="token builtin">sum</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># 730</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'Min: '</span><span class="token punctuation">,</span> statistics<span class="token punctuation">.</span><span class="token builtin">min</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># 24</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'Max: '</span><span class="token punctuation">,</span> statistics<span class="token punctuation">.</span><span class="token builtin">max</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># 38</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'Range: '</span><span class="token punctuation">,</span> statistics<span class="token punctuation">.</span><span class="token builtin">range</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># 14</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'Mean: '</span><span class="token punctuation">,</span> statistics<span class="token punctuation">.</span>mean<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># 29.2</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'Median: '</span><span class="token punctuation">,</span> statistics<span class="token punctuation">.</span>median<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># 27</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'Mode: '</span><span class="token punctuation">,</span> statistics<span class="token punctuation">.</span>mode<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># {'mode': 26, 'count': 5}</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'Standard Deviation: '</span><span class="token punctuation">,</span> statistics<span class="token punctuation">.</span>standard_deviation<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># 4.2</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'Variance: '</span><span class="token punctuation">,</span> statistics<span class="token punctuation">.</span>variance<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># 17.5</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'Frequency Distribution: '</span><span class="token punctuation">,</span> statistics<span class="token punctuation">.</span>frequency_distribution<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># [(24, 2), (25, 1), (26, 5), (27, 4), (29, 1), (31, 2), (32, 3), (33, 2), (34, 2), (37, 2), (38, 1)]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="练习-级别2" tabindex="-1"><a class="header-anchor" href="#练习-级别2" aria-hidden="true">#</a> 练习：级别2</h3>
<ol>
<li>创建一个名为PersonAccount的类。它有firstname、lastname、incomes、expenses属性和添加收入、添加支出以及账户余额方法。</li>
</ol>
<h3 id="练习-级别3" tabindex="-1"><a class="header-anchor" href="#练习-级别3" aria-hidden="true">#</a> 练习：级别3</h3>
<ol>
<li>以下是使用函数的方法。让我们将其转换为类</li>
</ol>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">def</span> <span class="token function">print_products</span><span class="token punctuation">(</span><span class="token operator">*</span>args<span class="token punctuation">,</span> <span class="token operator">**</span>kwargs<span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">for</span> product <span class="token keyword">in</span> args<span class="token punctuation">:</span>
        <span class="token keyword">print</span><span class="token punctuation">(</span>product<span class="token punctuation">)</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span>kwargs<span class="token punctuation">)</span>
    <span class="token keyword">for</span> key <span class="token keyword">in</span> kwargs<span class="token punctuation">:</span>
        <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string-interpolation"><span class="token string">f"</span><span class="token interpolation"><span class="token punctuation">{</span>key<span class="token punctuation">}</span></span><span class="token string">: </span><span class="token interpolation"><span class="token punctuation">{</span>kwargs<span class="token punctuation">[</span>key<span class="token punctuation">]</span><span class="token punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">)</span>

print_products<span class="token punctuation">(</span><span class="token string">"apple"</span><span class="token punctuation">,</span> <span class="token string">"banana"</span><span class="token punctuation">,</span> <span class="token string">"orange"</span><span class="token punctuation">,</span> vegetable<span class="token operator">=</span><span class="token string">"tomato"</span><span class="token punctuation">,</span> juice<span class="token operator">=</span><span class="token string">"orange"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>apple
banana
orange
<span class="token punctuation">{</span><span class="token string">'vegetable'</span><span class="token builtin class-name">:</span> <span class="token string">'tomato'</span>, <span class="token string">'juice'</span><span class="token builtin class-name">:</span> <span class="token string">'orange'</span><span class="token punctuation">}</span>
vegetable: tomato
juice: orange
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ol>
<li>在一个名为PersonAccount的类中，我们有属性：firstname、lastname、incomes、expenses。设计一个类，用于计算一个人的净收入。</li>
</ol>
<p>🎉 恭喜！🎉</p>
<p><RouterLink to="/docs/Python/20_python_package_manager_cn.html">&lt;&lt; 第 20 天</RouterLink> | <RouterLink to="/docs/Python/22_web_scraping_cn.html">第 22 天 &gt;&gt;</RouterLink></p>
</div></template>


