<template><div><h1 id="_07-字典" tabindex="-1"><a class="header-anchor" href="#_07-字典" aria-hidden="true">#</a> 07 字典</h1>
<h2 id="概念" tabindex="-1"><a class="header-anchor" href="#概念" aria-hidden="true">#</a> 概念</h2>
<p>字典是一种由无序、可修改（可变）的键值对组成的数据类型。</p>
<h3 id="创建字典" tabindex="-1"><a class="header-anchor" href="#创建字典" aria-hidden="true">#</a> 创建字典</h3>
<p>为了创建字典，我们使用大括号 {} 或内置函数 <em>dict()</em>。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
empty_dict <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
<span class="token comment"># 带数据值的字典</span>
dct <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'key1'</span><span class="token punctuation">:</span><span class="token string">'value1'</span><span class="token punctuation">,</span> <span class="token string">'key2'</span><span class="token punctuation">:</span><span class="token string">'value2'</span><span class="token punctuation">,</span> <span class="token string">'key3'</span><span class="token punctuation">:</span><span class="token string">'value3'</span><span class="token punctuation">,</span> <span class="token string">'key4'</span><span class="token punctuation">:</span><span class="token string">'value4'</span><span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>person <span class="token operator">=</span> <span class="token punctuation">{</span>
    <span class="token string">'first_name'</span><span class="token punctuation">:</span><span class="token string">'hua'</span><span class="token punctuation">,</span>
    <span class="token string">'last_name'</span><span class="token punctuation">:</span><span class="token string">'joffery'</span><span class="token punctuation">,</span>
    <span class="token string">'age'</span><span class="token punctuation">:</span><span class="token number">13</span><span class="token operator">&lt;&lt;</span><span class="token number">1</span><span class="token punctuation">,</span>
    <span class="token string">'country'</span><span class="token punctuation">:</span><span class="token string">'China'</span><span class="token punctuation">,</span>
    <span class="token string">'is_marred'</span><span class="token punctuation">:</span> <span class="token boolean">False</span><span class="token punctuation">,</span>
    <span class="token string">'skills'</span><span class="token punctuation">:</span><span class="token punctuation">[</span><span class="token string">'JavaScript'</span><span class="token punctuation">,</span> <span class="token string">'React'</span><span class="token punctuation">,</span> <span class="token string">'Vue'</span><span class="token punctuation">,</span> <span class="token string">'Python'</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token string">'address'</span><span class="token punctuation">:</span><span class="token punctuation">{</span>
        <span class="token string">'street'</span><span class="token punctuation">:</span><span class="token string">'star street'</span><span class="token punctuation">,</span>
        <span class="token string">'zipcode'</span><span class="token punctuation">:</span><span class="token string">'888888'</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面的字典显示，值可以是任何数据类型：字符串、布尔值、列表、元组、集合或字典。</p>
<h3 id="字典长度" tabindex="-1"><a class="header-anchor" href="#字典长度" aria-hidden="true">#</a> 字典长度</h3>
<p>它检查字典中的键值对的数量。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
dct <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'key1'</span><span class="token punctuation">:</span><span class="token string">'value1'</span><span class="token punctuation">,</span> <span class="token string">'key2'</span><span class="token punctuation">:</span><span class="token string">'value2'</span><span class="token punctuation">,</span> <span class="token string">'key3'</span><span class="token punctuation">:</span><span class="token string">'value3'</span><span class="token punctuation">,</span> <span class="token string">'key4'</span><span class="token punctuation">:</span><span class="token string">'value4'</span><span class="token punctuation">}</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token builtin">len</span><span class="token punctuation">(</span>dct<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># 4</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>person <span class="token operator">=</span> <span class="token punctuation">{</span>
    <span class="token string">'first_name'</span><span class="token punctuation">:</span><span class="token string">'hua'</span><span class="token punctuation">,</span>
    <span class="token string">'last_name'</span><span class="token punctuation">:</span><span class="token string">'joffery'</span><span class="token punctuation">,</span>
    <span class="token string">'age'</span><span class="token punctuation">:</span><span class="token number">13</span><span class="token operator">&lt;&lt;</span><span class="token number">1</span><span class="token punctuation">,</span>
    <span class="token string">'country'</span><span class="token punctuation">:</span><span class="token string">'China'</span><span class="token punctuation">,</span>
    <span class="token string">'is_marred'</span><span class="token punctuation">:</span> <span class="token boolean">False</span><span class="token punctuation">,</span>
    <span class="token string">'skills'</span><span class="token punctuation">:</span><span class="token punctuation">[</span><span class="token string">'JavaScript'</span><span class="token punctuation">,</span> <span class="token string">'React'</span><span class="token punctuation">,</span> <span class="token string">'Vue'</span><span class="token punctuation">,</span> <span class="token string">'Python'</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token string">'address'</span><span class="token punctuation">:</span><span class="token punctuation">{</span>
        <span class="token string">'street'</span><span class="token punctuation">:</span><span class="token string">'star street'</span><span class="token punctuation">,</span>
        <span class="token string">'zipcode'</span><span class="token punctuation">:</span><span class="token string">'888888'</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token builtin">len</span><span class="token punctuation">(</span>person<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># 7</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="访问字典项" tabindex="-1"><a class="header-anchor" href="#访问字典项" aria-hidden="true">#</a> 访问字典项</h3>
<p>我们可以通过参考其键名来访问字典项。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
dct <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'key1'</span><span class="token punctuation">:</span><span class="token string">'value1'</span><span class="token punctuation">,</span> <span class="token string">'key2'</span><span class="token punctuation">:</span><span class="token string">'value2'</span><span class="token punctuation">,</span> <span class="token string">'key3'</span><span class="token punctuation">:</span><span class="token string">'value3'</span><span class="token punctuation">,</span> <span class="token string">'key4'</span><span class="token punctuation">:</span><span class="token string">'value4'</span><span class="token punctuation">}</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>dct<span class="token punctuation">[</span><span class="token string">'key1'</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token comment"># value1</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>dct<span class="token punctuation">[</span><span class="token string">'key4'</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token comment"># value4</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>person <span class="token operator">=</span> <span class="token punctuation">{</span>
    <span class="token string">'first_name'</span><span class="token punctuation">:</span><span class="token string">'hua'</span><span class="token punctuation">,</span>
    <span class="token string">'last_name'</span><span class="token punctuation">:</span><span class="token string">'joffery'</span><span class="token punctuation">,</span>
    <span class="token string">'age'</span><span class="token punctuation">:</span><span class="token number">13</span><span class="token operator">&lt;&lt;</span><span class="token number">1</span><span class="token punctuation">,</span>
    <span class="token string">'country'</span><span class="token punctuation">:</span><span class="token string">'China'</span><span class="token punctuation">,</span>
    <span class="token string">'is_marred'</span><span class="token punctuation">:</span> <span class="token boolean">False</span><span class="token punctuation">,</span>
    <span class="token string">'skills'</span><span class="token punctuation">:</span><span class="token punctuation">[</span><span class="token string">'JavaScript'</span><span class="token punctuation">,</span> <span class="token string">'React'</span><span class="token punctuation">,</span> <span class="token string">'Vue'</span><span class="token punctuation">,</span> <span class="token string">'Python'</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token string">'address'</span><span class="token punctuation">:</span><span class="token punctuation">{</span>
        <span class="token string">'street'</span><span class="token punctuation">:</span><span class="token string">'star street'</span><span class="token punctuation">,</span>
        <span class="token string">'zipcode'</span><span class="token punctuation">:</span><span class="token string">'888888'</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>person<span class="token punctuation">[</span><span class="token string">'first_name'</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>person<span class="token punctuation">[</span><span class="token string">'country'</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>person<span class="token punctuation">[</span><span class="token string">'skills'</span><span class="token punctuation">]</span><span class="token punctuation">)</span>     
<span class="token keyword">print</span><span class="token punctuation">(</span>person<span class="token punctuation">[</span><span class="token string">'skills'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>person<span class="token punctuation">[</span><span class="token string">'address'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'street'</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>person<span class="token punctuation">[</span><span class="token string">'city'</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>通过键名访问项时，如果键不存在会引发错误。为了避免这个错误，我们首先要检查键是否存在，或者使用 <em>get</em> 方法。get 方法在键不存在时返回 None（这是 NoneType 对象数据类型）。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>person <span class="token operator">=</span> <span class="token punctuation">{</span>
    <span class="token string">'first_name'</span><span class="token punctuation">:</span><span class="token string">'hua'</span><span class="token punctuation">,</span>
    <span class="token string">'last_name'</span><span class="token punctuation">:</span><span class="token string">'joffery'</span><span class="token punctuation">,</span>
    <span class="token string">'age'</span><span class="token punctuation">:</span><span class="token number">13</span><span class="token operator">&lt;&lt;</span><span class="token number">1</span><span class="token punctuation">,</span>
    <span class="token string">'country'</span><span class="token punctuation">:</span><span class="token string">'China'</span><span class="token punctuation">,</span>
    <span class="token string">'is_marred'</span><span class="token punctuation">:</span> <span class="token boolean">False</span><span class="token punctuation">,</span>
    <span class="token string">'skills'</span><span class="token punctuation">:</span><span class="token punctuation">[</span><span class="token string">'JavaScript'</span><span class="token punctuation">,</span> <span class="token string">'React'</span><span class="token punctuation">,</span> <span class="token string">'Vue'</span><span class="token punctuation">,</span> <span class="token string">'Python'</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token string">'address'</span><span class="token punctuation">:</span><span class="token punctuation">{</span>
        <span class="token string">'street'</span><span class="token punctuation">:</span><span class="token string">'star street'</span><span class="token punctuation">,</span>
        <span class="token string">'zipcode'</span><span class="token punctuation">:</span><span class="token string">'888888'</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>person<span class="token punctuation">.</span>get<span class="token punctuation">(</span><span class="token string">'first_name'</span><span class="token punctuation">)</span><span class="token punctuation">)</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>person<span class="token punctuation">.</span>get<span class="token punctuation">(</span><span class="token string">'country'</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>person<span class="token punctuation">.</span>get<span class="token punctuation">(</span><span class="token string">'skills'</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>person<span class="token punctuation">.</span>get<span class="token punctuation">(</span><span class="token string">'city'</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="向字典添加项" tabindex="-1"><a class="header-anchor" href="#向字典添加项" aria-hidden="true">#</a> 向字典添加项</h3>
<p>我们可以向字典中添加新的键值对</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
dct <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'key1'</span><span class="token punctuation">:</span><span class="token string">'value1'</span><span class="token punctuation">,</span> <span class="token string">'key2'</span><span class="token punctuation">:</span><span class="token string">'value2'</span><span class="token punctuation">,</span> <span class="token string">'key3'</span><span class="token punctuation">:</span><span class="token string">'value3'</span><span class="token punctuation">,</span> <span class="token string">'key4'</span><span class="token punctuation">:</span><span class="token string">'value4'</span><span class="token punctuation">}</span>
dct<span class="token punctuation">[</span><span class="token string">'key5'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token string">'value5'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例：</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>person <span class="token operator">=</span> <span class="token punctuation">{</span>
    <span class="token string">'first_name'</span><span class="token punctuation">:</span><span class="token string">'hua'</span><span class="token punctuation">,</span>
    <span class="token string">'last_name'</span><span class="token punctuation">:</span><span class="token string">'joffery'</span><span class="token punctuation">,</span>
    <span class="token string">'age'</span><span class="token punctuation">:</span><span class="token number">13</span><span class="token operator">&lt;&lt;</span><span class="token number">1</span><span class="token punctuation">,</span>
    <span class="token string">'country'</span><span class="token punctuation">:</span><span class="token string">'China'</span><span class="token punctuation">,</span>
    <span class="token string">'is_marred'</span><span class="token punctuation">:</span> <span class="token boolean">False</span><span class="token punctuation">,</span>
    <span class="token string">'skills'</span><span class="token punctuation">:</span><span class="token punctuation">[</span><span class="token string">'JavaScript'</span><span class="token punctuation">,</span> <span class="token string">'React'</span><span class="token punctuation">,</span> <span class="token string">'Vue'</span><span class="token punctuation">,</span> <span class="token string">'Python'</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token string">'address'</span><span class="token punctuation">:</span><span class="token punctuation">{</span>
        <span class="token string">'street'</span><span class="token punctuation">:</span><span class="token string">'star street'</span><span class="token punctuation">,</span>
        <span class="token string">'zipcode'</span><span class="token punctuation">:</span><span class="token string">'888888'</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
person<span class="token punctuation">[</span><span class="token string">'job_title'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token string">'coder'</span>
person<span class="token punctuation">[</span><span class="token string">'skills'</span><span class="token punctuation">]</span><span class="token punctuation">.</span>append<span class="token punctuation">(</span><span class="token string">'HTML'</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>person<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="修改字典中的项目" tabindex="-1"><a class="header-anchor" href="#修改字典中的项目" aria-hidden="true">#</a> 修改字典中的项目</h3>
<p>我们可以修改字典中的项目</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
dct <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'key1'</span><span class="token punctuation">:</span><span class="token string">'value1'</span><span class="token punctuation">,</span> <span class="token string">'key2'</span><span class="token punctuation">:</span><span class="token string">'value2'</span><span class="token punctuation">,</span> <span class="token string">'key3'</span><span class="token punctuation">:</span><span class="token string">'value3'</span><span class="token punctuation">,</span> <span class="token string">'key4'</span><span class="token punctuation">:</span><span class="token string">'value4'</span><span class="token punctuation">}</span>
dct<span class="token punctuation">[</span><span class="token string">'key1'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token string">'value-one'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例:</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>person <span class="token operator">=</span> <span class="token punctuation">{</span>
    <span class="token string">'first_name'</span><span class="token punctuation">:</span><span class="token string">'hua'</span><span class="token punctuation">,</span>
    <span class="token string">'last_name'</span><span class="token punctuation">:</span><span class="token string">'joffery'</span><span class="token punctuation">,</span>
    <span class="token string">'age'</span><span class="token punctuation">:</span><span class="token number">13</span><span class="token operator">&lt;&lt;</span><span class="token number">1</span><span class="token punctuation">,</span>
    <span class="token string">'country'</span><span class="token punctuation">:</span><span class="token string">'China'</span><span class="token punctuation">,</span>
    <span class="token string">'is_marred'</span><span class="token punctuation">:</span> <span class="token boolean">False</span><span class="token punctuation">,</span>
    <span class="token string">'skills'</span><span class="token punctuation">:</span><span class="token punctuation">[</span><span class="token string">'JavaScript'</span><span class="token punctuation">,</span> <span class="token string">'React'</span><span class="token punctuation">,</span> <span class="token string">'Vue'</span><span class="token punctuation">,</span> <span class="token string">'Python'</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token string">'address'</span><span class="token punctuation">:</span><span class="token punctuation">{</span>
        <span class="token string">'street'</span><span class="token punctuation">:</span><span class="token string">'star street'</span><span class="token punctuation">,</span>
        <span class="token string">'zipcode'</span><span class="token punctuation">:</span><span class="token string">'888888'</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
person<span class="token punctuation">[</span><span class="token string">'age'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token number">66</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="检查字典中的键" tabindex="-1"><a class="header-anchor" href="#检查字典中的键" aria-hidden="true">#</a> 检查字典中的键</h3>
<p>我们使用 <em>in</em> 运算符来检查字典中是否存在某个键</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
dct <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'key1'</span><span class="token punctuation">:</span><span class="token string">'value1'</span><span class="token punctuation">,</span> <span class="token string">'key2'</span><span class="token punctuation">:</span><span class="token string">'value2'</span><span class="token punctuation">,</span> <span class="token string">'key3'</span><span class="token punctuation">:</span><span class="token string">'value3'</span><span class="token punctuation">,</span> <span class="token string">'key4'</span><span class="token punctuation">:</span><span class="token string">'value4'</span><span class="token punctuation">}</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'key2'</span> <span class="token keyword">in</span> dct<span class="token punctuation">)</span> <span class="token comment"># True</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'key5'</span> <span class="token keyword">in</span> dct<span class="token punctuation">)</span> <span class="token comment"># False</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="从字典中删除键值对" tabindex="-1"><a class="header-anchor" href="#从字典中删除键值对" aria-hidden="true">#</a> 从字典中删除键值对</h3>
<ul>
<li><em>pop(key)</em>: 删除具有指定键名的项目</li>
<li><em>popitem()</em>: 删除最后一个项目</li>
<li><em>del</em>: 删除具有指定键名的项目</li>
</ul>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
dct <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'key1'</span><span class="token punctuation">:</span><span class="token string">'value1'</span><span class="token punctuation">,</span> <span class="token string">'key2'</span><span class="token punctuation">:</span><span class="token string">'value2'</span><span class="token punctuation">,</span> <span class="token string">'key3'</span><span class="token punctuation">:</span><span class="token string">'value3'</span><span class="token punctuation">,</span> <span class="token string">'key4'</span><span class="token punctuation">:</span><span class="token string">'value4'</span><span class="token punctuation">}</span>
dct<span class="token punctuation">.</span>pop<span class="token punctuation">(</span><span class="token string">'key1'</span><span class="token punctuation">)</span> <span class="token comment"># 删除 key1 项目</span>
dct <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'key1'</span><span class="token punctuation">:</span><span class="token string">'value1'</span><span class="token punctuation">,</span> <span class="token string">'key2'</span><span class="token punctuation">:</span><span class="token string">'value2'</span><span class="token punctuation">,</span> <span class="token string">'key3'</span><span class="token punctuation">:</span><span class="token string">'value3'</span><span class="token punctuation">,</span> <span class="token string">'key4'</span><span class="token punctuation">:</span><span class="token string">'value4'</span><span class="token punctuation">}</span>
dct<span class="token punctuation">.</span>popitem<span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token comment"># 删除最后一项</span>
<span class="token keyword">del</span> dct<span class="token punctuation">[</span><span class="token string">'key2'</span><span class="token punctuation">]</span> <span class="token comment"># 删除 key2 项目</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>示例:</strong></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>person <span class="token operator">=</span> <span class="token punctuation">{</span>
    <span class="token string">'first_name'</span><span class="token punctuation">:</span><span class="token string">'hua'</span><span class="token punctuation">,</span>
    <span class="token string">'last_name'</span><span class="token punctuation">:</span><span class="token string">'joffery'</span><span class="token punctuation">,</span>
    <span class="token string">'age'</span><span class="token punctuation">:</span><span class="token number">13</span><span class="token operator">&lt;&lt;</span><span class="token number">1</span><span class="token punctuation">,</span>
    <span class="token string">'country'</span><span class="token punctuation">:</span><span class="token string">'China'</span><span class="token punctuation">,</span>
    <span class="token string">'is_marred'</span><span class="token punctuation">:</span> <span class="token boolean">False</span><span class="token punctuation">,</span>
    <span class="token string">'skills'</span><span class="token punctuation">:</span><span class="token punctuation">[</span><span class="token string">'JavaScript'</span><span class="token punctuation">,</span> <span class="token string">'React'</span><span class="token punctuation">,</span> <span class="token string">'Vue'</span><span class="token punctuation">,</span> <span class="token string">'Python'</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token string">'address'</span><span class="token punctuation">:</span><span class="token punctuation">{</span>
        <span class="token string">'street'</span><span class="token punctuation">:</span><span class="token string">'star street'</span><span class="token punctuation">,</span>
        <span class="token string">'zipcode'</span><span class="token punctuation">:</span><span class="token string">'888888'</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
person<span class="token punctuation">.</span>pop<span class="token punctuation">(</span><span class="token string">'first_name'</span><span class="token punctuation">)</span>  <span class="token comment"># 删除 firstname 项目</span>
person<span class="token punctuation">.</span>popitem<span class="token punctuation">(</span><span class="token punctuation">)</span>          <span class="token comment"># 删除 address 项目</span>
<span class="token keyword">del</span> person<span class="token punctuation">[</span><span class="token string">'is_married'</span><span class="token punctuation">]</span>  <span class="token comment"># 删除 is_married 项目</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="将字典改变为项目列表" tabindex="-1"><a class="header-anchor" href="#将字典改变为项目列表" aria-hidden="true">#</a> 将字典改变为项目列表</h3>
<p><em>items()</em> 方法将字典变成由元组组成的列表。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
dct <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'key1'</span><span class="token punctuation">:</span><span class="token string">'value1'</span><span class="token punctuation">,</span> <span class="token string">'key2'</span><span class="token punctuation">:</span><span class="token string">'value2'</span><span class="token punctuation">,</span> <span class="token string">'key3'</span><span class="token punctuation">:</span><span class="token string">'value3'</span><span class="token punctuation">,</span> <span class="token string">'key4'</span><span class="token punctuation">:</span><span class="token string">'value4'</span><span class="token punctuation">}</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>dct<span class="token punctuation">.</span>items<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># dict_items([('key1', 'value1'), ('key2', 'value2'), ('key3', 'value3'), ('key4', 'value4')])</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="清空字典" tabindex="-1"><a class="header-anchor" href="#清空字典" aria-hidden="true">#</a> 清空字典</h3>
<p>如果我们不需要字典中的项目，我们可以使用 <em>clear()</em> 方法来清空它们</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
dct <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'key1'</span><span class="token punctuation">:</span><span class="token string">'value1'</span><span class="token punctuation">,</span> <span class="token string">'key2'</span><span class="token punctuation">:</span><span class="token string">'value2'</span><span class="token punctuation">,</span> <span class="token string">'key3'</span><span class="token punctuation">:</span><span class="token string">'value3'</span><span class="token punctuation">,</span> <span class="token string">'key4'</span><span class="token punctuation">:</span><span class="token string">'value4'</span><span class="token punctuation">}</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>dct<span class="token punctuation">.</span>clear<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment"># None</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="删除字典" tabindex="-1"><a class="header-anchor" href="#删除字典" aria-hidden="true">#</a> 删除字典</h3>
<p>如果我们不再使用字典，我们可以完全删除它</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
dct <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'key1'</span><span class="token punctuation">:</span><span class="token string">'value1'</span><span class="token punctuation">,</span> <span class="token string">'key2'</span><span class="token punctuation">:</span><span class="token string">'value2'</span><span class="token punctuation">,</span> <span class="token string">'key3'</span><span class="token punctuation">:</span><span class="token string">'value3'</span><span class="token punctuation">,</span> <span class="token string">'key4'</span><span class="token punctuation">:</span><span class="token string">'value4'</span><span class="token punctuation">}</span>
<span class="token keyword">del</span> dct
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="复制字典" tabindex="-1"><a class="header-anchor" href="#复制字典" aria-hidden="true">#</a> 复制字典</h3>
<p>我们可以使用 <em>copy()</em> 方法复制一个字典。使用 copy 方法可以避免原始字典被修改。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
dct <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'key1'</span><span class="token punctuation">:</span><span class="token string">'value1'</span><span class="token punctuation">,</span> <span class="token string">'key2'</span><span class="token punctuation">:</span><span class="token string">'value2'</span><span class="token punctuation">,</span> <span class="token string">'key3'</span><span class="token punctuation">:</span><span class="token string">'value3'</span><span class="token punctuation">,</span> <span class="token string">'key4'</span><span class="token punctuation">:</span><span class="token string">'value4'</span><span class="token punctuation">}</span>
dct_copy <span class="token operator">=</span> dct<span class="token punctuation">.</span>copy<span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token comment"># {'key1':'value1', 'key2':'value2', 'key3':'value3', 'key4':'value4'}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="获取字典的键列表" tabindex="-1"><a class="header-anchor" href="#获取字典的键列表" aria-hidden="true">#</a> 获取字典的键列表</h3>
<p>keys() 方法给我们一个包含所有字典键的列表。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
dct <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'key1'</span><span class="token punctuation">:</span><span class="token string">'value1'</span><span class="token punctuation">,</span> <span class="token string">'key2'</span><span class="token punctuation">:</span><span class="token string">'value2'</span><span class="token punctuation">,</span> <span class="token string">'key3'</span><span class="token punctuation">:</span><span class="token string">'value3'</span><span class="token punctuation">,</span> <span class="token string">'key4'</span><span class="token punctuation">:</span><span class="token string">'value4'</span><span class="token punctuation">}</span>
keys <span class="token operator">=</span> dct<span class="token punctuation">.</span>keys<span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>keys<span class="token punctuation">)</span> <span class="token comment"># dict_keys(['key1', 'key2', 'key3', 'key4'])</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="获取字典的值列表" tabindex="-1"><a class="header-anchor" href="#获取字典的值列表" aria-hidden="true">#</a> 获取字典的值列表</h3>
<p>values 方法给我们一个包含所有字典值的列表。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token comment"># 语法</span>
dct <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'key1'</span><span class="token punctuation">:</span><span class="token string">'value1'</span><span class="token punctuation">,</span> <span class="token string">'key2'</span><span class="token punctuation">:</span><span class="token string">'value2'</span><span class="token punctuation">,</span> <span class="token string">'key3'</span><span class="token punctuation">:</span><span class="token string">'value3'</span><span class="token punctuation">,</span> <span class="token string">'key4'</span><span class="token punctuation">:</span><span class="token string">'value4'</span><span class="token punctuation">}</span>
values <span class="token operator">=</span> dct<span class="token punctuation">.</span>values<span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>values<span class="token punctuation">)</span> <span class="token comment"># dict_values(['value1', 'value2', 'value3', 'value4'])</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


